// Navigation partials generated from content/site.js and included by
// src/components/shared/header.htm, mobile-menu.htm and footer.htm.
import { AGENCY_PAGES, INDUSTRIES, agencyUrl, LOCATION_GROUPS, RESOURCES, SERVICE_GROUPS, industryUrl, locationUrl, resourceUrl, serviceUrl } from '../../content/site.js';
import { arrow, chipLink, eyebrow, icon, linkCard } from '../lib/ui.js';

const HEADER_NOTE = '<!-- Generated by scripts/build-pages.js from content/site.js, do not edit by hand. -->';

const chevron = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-3.5 opacity-55 transition-transform duration-300 group-hover:rotate-180" aria-hidden="true"><path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" /></svg>`;

const megaTrigger = (label, href) =>
  `<a href="${href}" data-nav-link class="site-nav-link inline-flex items-center gap-1.5" aria-haspopup="true">${label}${chevron}</a>`;

const megaFooter = (text, href, label) => `
      <div class="mt-2 flex items-center justify-between gap-4 rounded-xl border border-secondary/[0.08] bg-secondary/[0.03] px-4 py-3">
        <p class="text-tagline-3 text-secondary/55">${text}</p>
        <a href="${href}" class="link-arrow shrink-0 text-primary-600 hover:text-primary-700">${label}${arrow()}</a>
      </div>`;

// ---------------------------------------------------------------------------
export const navDesktop = () => `${HEADER_NOTE}
<!-- Services -->
<div class="group mega-wide flex h-full items-center">
  ${megaTrigger('Services', '/services/')}
  <div class="mega-panel w-[min(1080px,calc(100vw-2.5rem))]">
    <div class="mega-inner">
      <div class="grid grid-cols-4 gap-2 p-2">
        ${SERVICE_GROUPS.map(
          (g) => `
        <div>
          <p class="mega-col-title" style="color: color-mix(in srgb, ${g.accent} 70%, #0c1220)">${icon(g.icon, 'size-4')}${g.title}</p>
          ${g.services.map((s) => `<a href="${serviceUrl(s.slug)}" class="mega-mini-link">${s.name}</a>`).join('\n          ')}
        </div>`
        ).join('')}
      </div>
      ${megaFooter('Not sure which fits? We’ll scope it on a free 30-minute call.', '/services/', 'All services')}
    </div>
  </div>
</div>

<!-- Locations -->
<div class="group mega-wide flex h-full items-center">
  ${megaTrigger('Locations', '/locations/')}
  <div class="mega-panel w-[min(1080px,calc(100vw-2.5rem))]">
    <div class="mega-inner">
      <div class="grid grid-cols-5 gap-2 p-2">
        ${LOCATION_GROUPS.map(
          (g) => `
        <div>
          <p class="mega-col-title">${icon(g.key.startsWith('us-') ? 'pin' : 'globe', 'size-4 text-primary-600')}${g.title}</p>
          ${g.locations.map((l) => `<a href="${locationUrl(l.slug)}" class="mega-mini-link">${l.name}</a>`).join('\n          ')}
        </div>`
        ).join('')}
      </div>
      ${megaFooter('Remote-first, working in your time zone.', '/locations/', 'All locations')}
    </div>
  </div>
</div>

<!-- Industries -->
<div class="group mega-wide flex h-full items-center">
  ${megaTrigger('Industries', '/industries/')}
  <div class="mega-panel w-[min(640px,calc(100vw-2.5rem))]">
    <div class="mega-inner">
      <div class="grid grid-cols-2 gap-1 p-1">
        ${INDUSTRIES.map(
          (i) => `<a href="${industryUrl(i.slug)}" class="mega-link !py-2.5" style="--accent: ${i.accent}"><span class="mega-link__icon !size-8">${icon(i.icon, 'size-4')}</span><span class="mega-link__title self-center">${i.name}</span></a>`
        ).join('\n        ')}
      </div>
      ${megaFooter('Automation shaped around how your industry sells.', '/industries/', 'All industries')}
    </div>
  </div>
</div>

<!-- For Agencies -->
<div class="group mega-wide flex h-full items-center">
  ${megaTrigger('For Agencies', '/for-agencies/')}
  <div class="mega-panel w-[min(620px,calc(100vw-2.5rem))]">
    <div class="mega-inner">
      <div class="grid grid-cols-2 gap-1">
        ${AGENCY_PAGES.map(
          (a) => `<a href="${agencyUrl(a.slug)}" class="mega-link" style="--accent: ${a.accent}"><span class="mega-link__icon">${icon(a.icon, 'size-[18px]')}</span><span><span class="mega-link__title">${a.name}</span><span class="mega-link__desc">${a.short}</span></span></a>`
        ).join('\n        ')}
        <a href="${agencyUrl()}" class="mega-link" style="--accent: #0f9f93"><span class="mega-link__icon">${icon('briefcase', 'size-[18px]')}</span><span><span class="mega-link__title">Partner program overview</span><span class="mega-link__desc">How white label fulfillment with Voxil AI works.</span></span></a>
      </div>
      ${megaFooter('Your brand, your accounts. Your client never hears our name.', '/for-agencies/', 'For Agencies')}
    </div>
  </div>
</div>

<!-- Resources -->
<div class="group mega-wide flex h-full items-center">
  ${megaTrigger('Resources', '/resources/')}
  <div class="mega-panel w-[min(560px,calc(100vw-2.5rem))]">
    <div class="mega-inner grid grid-cols-2 gap-1">
      ${RESOURCES.map(
        (r) => `<a href="${resourceUrl(r.slug)}" class="mega-link" style="--accent: ${r.accent}"><span class="mega-link__icon">${icon(r.icon, 'size-[18px]')}</span><span><span class="mega-link__title">${r.name}</span><span class="mega-link__desc">${r.short}</span></span></a>`
      ).join('\n      ')}
      <a href="/blog/" class="mega-link" style="--accent: #38bdf8"><span class="mega-link__icon">${icon('book', 'size-[18px]')}</span><span><span class="mega-link__title">Blog</span><span class="mega-link__desc">AI statistics, guides and honest comparisons.</span></span></a>
      <a href="/resources/" class="mega-link" style="--accent: #2fc4b6"><span class="mega-link__icon">${icon('sparkles', 'size-[18px]')}</span><span><span class="mega-link__title">All free tools</span><span class="mega-link__desc">Every calculator, checklist and guide.</span></span></a>
    </div>
  </div>
</div>
`;

// ---------------------------------------------------------------------------
const mobileGroup = (title, inner, dot = '#2fc4b6') => `
<details class="mobile-group" style="--dot: ${dot}">
  <summary>${title}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-4 text-secondary/50 transition-transform duration-300" aria-hidden="true"><path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" /></svg></summary>
  <div class="pb-3">${inner}</div>
</details>`;

// The colored dot before each link is drawn in CSS (.site-mobile-sublink::before).
const sub = (href, label) => `<a href="${href}" class="site-mobile-sublink">${label}</a>`;

export const navMobile = () => `${HEADER_NOTE}
${mobileGroup(
  'Services',
  SERVICE_GROUPS.map((g) => `<p class="mobile-group__title">${g.title}</p>${g.services.map((s) => sub(serviceUrl(s.slug), s.name)).join('')}`).join('') +
    sub('/services/', 'All services')
)}
${mobileGroup(
  'Locations',
  LOCATION_GROUPS.map((g) => `<p class="mobile-group__title">${g.title}</p>${g.locations.map((l) => sub(locationUrl(l.slug), l.name)).join('')}`).join('') +
    sub('/locations/', 'All locations'),
  '#38bdf8'
)}
${mobileGroup('Industries', INDUSTRIES.map((i) => sub(industryUrl(i.slug), i.name)).join('') + sub('/industries/', 'All industries'), '#ff7a3d')}
${mobileGroup('For Agencies', sub(agencyUrl(), 'Partner program overview') + AGENCY_PAGES.map((a) => sub(agencyUrl(a.slug), a.name)).join(''))}
${mobileGroup('Resources', RESOURCES.map((r) => sub(resourceUrl(r.slug), r.name)).join('') + sub('/blog/', 'Blog') + sub('/resources/', 'All free tools'))}
`;

// ---------------------------------------------------------------------------
const footLink = (href, label) =>
  `<li><a href="${href}" class="footer-link">${label}</a></li>`;

const footCol = (title, links) => `
        <div>
          <p class="text-tagline-3 mb-4 font-semibold tracking-[0.12em] text-secondary/40 uppercase">${title}</p>
          <ul class="space-y-2.5">${links.join('')}</ul>
        </div>`;

// Footer service links, in the order and wording requested for the footer.
const FOOTER_SERVICES = [
  ['ai-calling-bots', 'AI Calling Bots (Vapi & Retell AI)'],
  ['ai-chatbots', 'AI Chatbots & WhatsApp Bots'],
  ['gohighlevel-automation', 'GoHighLevel Automation'],
  ['website-design', 'Website & Funnel Development'],
  ['seo-paid-ads', 'SEO & Paid Ads'],
  ['ghl-white-label-saas', 'GHL White Label SaaS'],
];

export const footerLinks = () => `${HEADER_NOTE}
<div class="grid grid-cols-2 gap-8 sm:grid-cols-4 lg:col-span-8">
  ${footCol('Services', [...FOOTER_SERVICES.map(([s, l]) => footLink(serviceUrl(s), l)), footLink('/services/', 'All services')])}
  ${footCol('Industries', INDUSTRIES.map((i) => footLink(industryUrl(i.slug), i.name)))}
  ${footCol('Free Resources', [
    footLink(resourceUrl('lead-loss-calculator'), 'Lead Loss Calculator'),
    footLink(resourceUrl('ai-statistics-2026'), 'AI Statistics 2026'),
    footLink(resourceUrl('ghl-setup-checklist'), 'GHL Setup Checklist'),
    footLink('/resources/', 'All Free Tools'),
    footLink(resourceUrl('media-kit'), 'Media Kit'),
    footLink('/blog/', 'Blog'),
  ])}
  ${footCol('Company', [
    footLink('/for-agencies/', 'For Agencies'),
    footLink('/portfolio/', 'Portfolio'),
    footLink('/about.html', 'About'),
    footLink('/case-studies/', 'Case Studies'),
    footLink('/testimonial.html', 'Testimonials'),
    footLink('/faq.html', 'FAQ'),
    footLink('/contact.html', 'Contact'),
    footLink('/book-meeting.html', 'Book a call'),
    footLink('/privacy-policy.html', 'Privacy Policy'),
    footLink('/terms-conditions.html', 'Terms &amp; Conditions'),
  ])}
</div>
`;

export const footerLocations = () => `${HEADER_NOTE}
<div class="mt-12 rounded-2xl border border-secondary/[0.08] bg-secondary/[0.025] p-5 md:p-6">
  <p class="text-tagline-3 mb-3 font-semibold tracking-[0.12em] text-secondary/40 uppercase">Locations we serve</p>
  <p class="loc-strip">
    ${LOCATION_GROUPS.flatMap((g) => g.locations)
      .map((l) => `<a href="${locationUrl(l.slug)}">${l.name}</a>`)
      .join(' ')}
  </p>
</div>
`;

// ---------------------------------------------------------------------------
// Home page "explore" band: industries, locations and latest research.
export const homeExplore = (posts) => `${HEADER_NOTE}
<section class="section-base section-pad section-seam">
  <span class="orb top-1/4 -right-24 size-[380px]" style="--orb: #0f9f93; --orb-opacity: 0.16" aria-hidden="true"></span>
  <div class="main-container relative z-10">
    <div class="grid gap-12 lg:grid-cols-2 lg:gap-16">
      <div>
        ${eyebrow('Industries')}
        <h2 data-reveal class="text-heading-5 sm:text-heading-4 font-semibold tracking-tight text-secondary">Built for <span class="text-gradient-teal">your industry</span></h2>
        <p data-reveal class="text-tagline-2 mt-4 text-secondary/55">Every industry leaks revenue in different places. See where, and what we build to fix it.</p>
        <div data-reveal class="mt-6 flex flex-wrap gap-2">${INDUSTRIES.map((i) => chipLink(industryUrl(i.slug), i.name, i.icon)).join('')}</div>
      </div>
      <div>
        ${eyebrow('Locations', '#38bdf8')}
        <h2 data-reveal class="text-heading-5 sm:text-heading-4 font-semibold tracking-tight text-secondary">Serving businesses <span class="text-gradient-sky">worldwide</span></h2>
        <p data-reveal class="text-tagline-2 mt-4 text-secondary/55">Remote-first, working in your time zone, with local context on languages and compliance.</p>
        <div data-reveal class="mt-6 flex flex-wrap gap-2">${LOCATION_GROUPS.flatMap((g) => g.locations).map((l) => chipLink(locationUrl(l.slug), l.name, 'pin')).join('')}</div>
      </div>
    </div>

    <div class="mt-16 flex flex-col items-start justify-between gap-4 md:flex-row md:items-end">
      <div>
        ${eyebrow('Research', '#ff7a3d')}
        <h2 data-reveal class="text-heading-5 sm:text-heading-4 font-semibold tracking-tight text-secondary">AI statistics &amp; <span class="text-gradient-warm">guides</span></h2>
      </div>
      <a data-reveal href="/blog/" class="cta cta-md cta-ghost shrink-0">All articles${arrow()}</a>
    </div>
    <div class="mt-8 grid gap-4 md:grid-cols-3">
      ${linkCard({ href: resourceUrl('ai-statistics-2026'), title: 'AI Statistics 2026', desc: 'Sourced numbers on AI adoption, customer service, agents and speed-to-lead.', icon: 'chart', accent: '#2fc4b6', cta: 'Explore', badge: 'Updated' })}
      ${posts.map((p) => linkCard({ href: `/blog/${p.slug}/`, title: p.title, desc: p.excerpt, icon: 'book', accent: '#ff7a3d', cta: 'Read' })).join('')}
    </div>
  </div>
</section>
`;
