// Industry page content. `noun` is the plural phrase used in headings
// ("HVAC companies"), so acronyms and slashes never get mangled.
const link = (href, text) => `<a href="${href}" class="text-primary-600 underline underline-offset-4">${text}</a>`;

export default {
  'real-estate': {
    noun: 'real-estate teams',
    title: 'AI for Real Estate | AI Voice Agents, Chatbots & Lead Follow-Up for Realtors | Voxil AI',
    description: 'AI automation for real-estate agents, brokerages and property managers: instant lead response, AI ISA calls, showing booking, WhatsApp bots and CRM follow-up that converts more leads.',
    h1: 'AI for real estate that <span class="text-gradient-teal">answers every lead</span>',
    lead: 'Instant response to portal and ad leads, AI ISA calls, showing booking and long-term nurture, so agents spend time with serious buyers and sellers, not chasing cold enquiries.',
    answer: '<strong>AI for real estate</strong> automates lead response and nurture for agents, brokerages and property managers. AI agents reply to portal, website and ad leads within seconds, qualify buyers, sellers and renters, book showings or valuations into agents’ calendars, and keep long-term leads warm until they’re ready to move.',
    facts: [
      { label: 'Lead response', value: 'Seconds' },
      { label: 'Channels', value: 'Call · SMS · WhatsApp' },
      { label: 'CRMs', value: 'FUB · GHL · HubSpot' },
      { label: 'Go-live', value: '2-4 weeks' },
    ],
    pills: ['AI ISA', 'Showing booking', 'Long-term nurture', 'Tenant FAQs'],
    painTitle: 'Where real-estate teams <span class="text-gradient-warm">lose deals</span>',
    painLead: 'Leads cost more every year. Most are lost to speed and follow-up, not price.',
    pains: [
      { title: 'Slow first response', desc: 'Portal leads contact several agents; the first to respond usually gets the conversation.' },
      { title: 'Long buying cycles', desc: 'Many leads aren’t ready for months, and nobody follows up long enough.' },
      { title: 'Showing coordination', desc: 'Back-and-forth scheduling eats agent time and loses momentum.' },
      { title: 'After-hours enquiries', desc: 'Evenings and weekends are when buyers browse, and when offices are closed.' },
    ],
    useLead: 'From first enquiry to closing-day reminders, these are the systems we build most for agents and brokerages.',
    uses: [
      { icon: 'bolt', title: 'Instant lead response', desc: 'Call or text new Zillow, Realtor.com, Rightmove or ad leads within seconds.' },
      { icon: 'phone', title: 'AI ISA', desc: 'Voice agents that qualify timeline, budget, pre-approval and motivation.' },
      { icon: 'calendar', title: 'Showing & valuation booking', desc: 'Book viewings and listing appointments straight into agents’ calendars.' },
      { icon: 'refresh', title: 'Long-term nurture', desc: 'Months of relevant follow-up, new listings, market updates, check-ins.' },
      { icon: 'bubble', title: 'Listing chatbots', desc: 'Answer questions about listings 24/7 on your site and WhatsApp.' },
      { icon: 'home', title: 'Property management', desc: 'Tenant FAQs, maintenance intake and renewal reminders automated.' },
    ],
    flowTitle: 'From portal lead to <span class="text-gradient-warm">booked showing</span>',
    flowLead: 'A typical flow for a buyer lead from a listing portal.',
    flow: [
      { title: 'Lead arrives', desc: 'New portal or ad lead lands in your CRM.' },
      { title: 'Instant contact', desc: 'AI calls or texts within seconds, referencing the listing.' },
      { title: 'Qualify', desc: 'Timeline, budget, financing and area captured as CRM fields.' },
      { title: 'Book or nurture', desc: 'Hot leads book a showing; others enter tailored nurture.' },
    ],
    caseStudy: { label: 'A 24/7 listing enquiry agent that books showings into the CRM.', href: '/case-study-real-estate.html' },
    services: ['ai-sdr-system', 'ai-follow-up-system', 'whatsapp-automation', 'ai-appointment-booking'],
    faqs: [
      { q: 'What is an AI ISA?', a: 'An AI inside sales agent is a voice or text agent that calls and messages new leads, qualifies them and books appointments for agents, the role traditionally done by a human ISA, available 24/7.' },
      { q: 'Does it work with Follow Up Boss?', a: 'Yes. We integrate with Follow Up Boss, GoHighLevel, HubSpot, kvCORE/BoldTrail, Lofty and other real-estate CRMs with APIs.' },
      { q: 'Is AI calling real-estate leads legal?', a: 'Calling leads who have enquired is generally permitted, but automated or AI-voice calls in the US require appropriate consent under the TCPA. We configure consent capture and calling windows and recommend confirming your lead sources’ consent language.' },
      { q: 'Can the AI answer questions about specific listings?', a: 'Yes, we connect listing data so the agent can answer questions about price, features, availability and viewing times.' },
    ],
  },

  'fitness-gyms': {
    noun: 'gyms and studios',
    title: 'AI for Gyms & Fitness Studios | Lead Follow-Up, Booking & Retention | Voxil AI',
    description: 'AI automation for gyms, fitness studios and personal trainers: instant lead response, trial and class booking, no-show recovery, membership retention and review automation.',
    h1: 'AI for gyms that <span class="text-gradient-teal">turns enquiries into members</span>',
    lead: 'Reply to every trial enquiry instantly, book classes and consults automatically, rescue no-shows, and keep members engaged so they don’t quietly cancel.',
    answer: '<strong>AI for gyms and fitness studios</strong> automates the membership funnel: instant replies to ad and website enquiries, trial and class booking, reminders and no-show follow-up, onboarding for new members, and retention campaigns that re-engage members who stop showing up.',
    facts: [
      { label: 'Lead response', value: 'Instant' },
      { label: 'Booking', value: 'Trials · Classes' },
      { label: 'Retention', value: 'Automated' },
      { label: 'Go-live', value: '2-3 weeks' },
    ],
    pills: ['Trial booking', 'No-show recovery', 'Member onboarding', 'Win-back'],
    painTitle: 'Where gyms <span class="text-gradient-warm">leak revenue</span>',
    painLead: 'Most gym revenue problems are follow-up problems.',
    pains: [
      { title: 'Ad leads go cold', desc: 'Leads from Meta ads expect a reply in minutes, front desks reply in hours.' },
      { title: 'Trial no-shows', desc: 'Booked trials don’t turn up, and nobody follows up.' },
      { title: 'Silent churn', desc: 'Members stop visiting weeks before they cancel.' },
      { title: 'Busy front desk', desc: 'Staff juggle check-ins, calls and DMs at peak hours.' },
    ],
    useLead: 'Systems that fill trials, protect bookings and keep members coming back.',
    uses: [
      { icon: 'bolt', title: 'Instant enquiry replies', desc: 'Text and DM replies to new leads within seconds, 24/7.' },
      { icon: 'calendar', title: 'Trial & class booking', desc: 'Book intro sessions and classes into your gym software.' },
      { icon: 'refresh', title: 'No-show recovery', desc: 'Automatic rebooking messages when a trial is missed.' },
      { icon: 'academic', title: 'Member onboarding', desc: 'First-30-day sequences that build the habit.' },
      { icon: 'heart', title: 'Retention alerts', desc: 'Flag members whose visits drop and trigger check-ins.' },
      { icon: 'star', title: 'Reviews & referrals', desc: 'Ask happy members for reviews and referrals at the right time.' },
    ],
    flowTitle: 'From Instagram ad to <span class="text-gradient-warm">first workout</span>',
    flowLead: 'A typical trial funnel for a studio or gym.',
    flow: [
      { title: 'Ad click', desc: 'Lead submits a form or DMs from Instagram.' },
      { title: 'Instant reply', desc: 'AI responds, answers questions and offers trial times.' },
      { title: 'Booked & reminded', desc: 'Trial booked with SMS reminders.' },
      { title: 'Convert', desc: 'Post-trial follow-up with membership offer.' },
    ],
    services: ['ai-chatbots', 'ai-follow-up-system', 'gohighlevel-automation', 'email-sms-marketing'],
    faqs: [
      { q: 'Does it integrate with Mindbody or Glofox?', a: 'We integrate with gym platforms that offer APIs or integrations, such as Mindbody, Glofox, ABC, PushPress and GoHighLevel, or use GHL as the booking layer.' },
      { q: 'Can AI reply to Instagram DMs?', a: 'Yes, through official Meta integrations, the AI can reply to Instagram and Facebook messages and book trials.' },
      { q: 'How does AI help retention?', a: 'By watching attendance patterns and triggering personal check-ins, challenges or trainer outreach before members cancel.' },
      { q: 'Is this only for big gyms?', a: 'No, boutique studios and personal trainers benefit most because they have the least admin time.' },
    ],
  },

  insurance: {
    noun: 'insurance agencies',
    title: 'AI for Insurance Agencies | Quote Follow-Up, AI Calling & Renewals | Voxil AI',
    description: 'AI automation for insurance agencies: instant quote-request response, AI qualification calls, renewal and cross-sell reminders, document collection and CRM/AMS integration.',
    h1: 'AI for insurance agencies that <span class="text-gradient-teal">quotes faster</span>',
    lead: 'Respond to quote requests in seconds, collect the details underwriting needs, follow up relentlessly on open quotes and automate renewals, without adding producers.',
    answer: '<strong>AI for insurance agencies</strong> automates the sales and service workload: instant response to quote requests, AI calls that collect rating information, follow-up on open quotes, renewal and cross-sell reminders, document collection and policy FAQs, integrated with your CRM or agency management system.',
    facts: [
      { label: 'Quote response', value: 'Seconds' },
      { label: 'Data capture', value: 'Structured' },
      { label: 'Renewals', value: 'Automated' },
      { label: 'Go-live', value: '3-5 weeks' },
    ],
    pills: ['Quote intake', 'AI calling', 'Renewals', 'Cross-sell'],
    painTitle: 'Where agencies <span class="text-gradient-warm">lose policies</span>',
    painLead: 'Shoppers request multiple quotes; speed and persistence win.',
    pains: [
      { title: 'Slow quote response', desc: 'Leads shop several agencies, the first callback often wins.' },
      { title: 'Incomplete information', desc: 'Back-and-forth for missing details delays quotes.' },
      { title: 'Open quotes forgotten', desc: 'Quotes sent but never followed up.' },
      { title: 'Renewal churn', desc: 'Clients shop at renewal when nobody checks in first.' },
    ],
    useLead: 'Automation across the full policy lifecycle.',
    uses: [
      { icon: 'bolt', title: 'Instant quote response', desc: 'Every quote request contacted within seconds.' },
      { icon: 'clipboard', title: 'Rating data capture', desc: 'AI collects drivers, vehicles, property details and coverage needs.' },
      { icon: 'refresh', title: 'Quote follow-up', desc: 'Persistent, friendly follow-up until a decision.' },
      { icon: 'calendar', title: 'Renewal outreach', desc: 'Reviews booked ahead of renewal dates.' },
      { icon: 'trending', title: 'Cross-sell', desc: 'Bundling opportunities flagged and offered automatically.' },
      { icon: 'document', title: 'Document collection', desc: 'Automated requests and reminders for signatures and documents.' },
    ],
    flowTitle: 'From quote request to <span class="text-gradient-warm">bound policy</span>',
    flowLead: 'A typical personal-lines flow.',
    flow: [
      { title: 'Request', desc: 'Web form or ad lead submitted.' },
      { title: 'AI intake', desc: 'AI call or text collects rating details.' },
      { title: 'Producer review', desc: 'Complete file handed to a licensed producer.' },
      { title: 'Follow-up', desc: 'Automated follow-up until bound or closed.' },
    ],
    caseStudy: { label: 'Automated lead qualification and CRM routing for a lending team.', href: '/case-study-finance.html' },
    services: ['ai-sdr-system', 'ai-calling-bots', 'ai-follow-up-system', 'crm-automation'],
    faqs: [
      { q: 'Can AI give insurance advice?', a: 'No, and it shouldn’t. We restrict agents to intake, scheduling and general information, and route anything that needs licensed advice to your producers.' },
      { q: 'Which systems do you integrate with?', a: 'CRMs like HubSpot, Salesforce and GoHighLevel, and agency management systems where APIs are available. We confirm your specific AMS during scoping.' },
      { q: 'Is AI calling compliant for insurance leads?', a: 'It can be with proper consent, disclosures and calling windows under the TCPA and state rules. We build consent tracking and full call logging.' },
      { q: 'Can it handle renewals?', a: 'Yes, reminders, review booking and re-quote requests triggered from policy expiry dates.' },
    ],
  },

  'law-firms': {
    noun: 'law firms',
    title: 'AI for Law Firms | AI Legal Intake, Receptionist & Client Follow-Up | Voxil AI',
    description: 'AI automation for law firms: 24/7 AI legal intake and receptionist, conflict-check prep, consultation booking, document collection and client updates, integrated with Clio and your CRM.',
    h1: 'AI for law firms that <span class="text-gradient-teal">never misses an intake</span>',
    lead: '24/7 AI intake and reception that captures case details, screens for fit, books consultations and keeps clients updated, while your attorneys practise law.',
    answer: '<strong>AI for law firms</strong> automates client intake and communication: an AI receptionist answers calls and chats 24/7, gathers case facts, screens against your practice areas, books consultations, collects documents and sends status updates, escalating urgent or sensitive matters to staff and never giving legal advice.',
    facts: [
      { label: 'Intake', value: '24/7' },
      { label: 'Integrations', value: 'Clio · CRMs' },
      { label: 'Legal advice', value: 'Never' },
      { label: 'Go-live', value: '2-4 weeks' },
    ],
    pills: ['AI intake', 'Consultation booking', 'Document collection', 'Client updates'],
    painTitle: 'Where firms <span class="text-gradient-warm">lose cases</span>',
    painLead: 'Prospective clients often call several firms, the one that answers wins.',
    pains: [
      { title: 'Missed calls', desc: 'Calls during court, meetings or after hours go to voicemail.' },
      { title: 'Unqualified consults', desc: 'Attorney time spent on matters outside your practice areas.' },
      { title: 'Document chasing', desc: 'Paralegals spend hours requesting and tracking documents.' },
      { title: '“Any update?” calls', desc: 'Clients call for status updates that could be automated.' },
    ],
    useLead: 'Intake and client-communication systems designed for legal workflows.',
    uses: [
      { icon: 'phone', title: 'AI legal receptionist', desc: 'Answers every call, captures matter details and urgency.' },
      { icon: 'funnel', title: 'Case screening', desc: 'Screens by practice area, jurisdiction and key facts you define.' },
      { icon: 'calendar', title: 'Consultation booking', desc: 'Books qualified prospects with the right attorney.' },
      { icon: 'document', title: 'Document collection', desc: 'Secure upload requests with automatic reminders.' },
      { icon: 'bubble', title: 'Status updates', desc: 'Proactive updates reduce inbound status calls.' },
      { icon: 'shield', title: 'Guardrails', desc: 'No legal advice; sensitive matters routed to staff.' },
    ],
    flowTitle: 'From first call to <span class="text-gradient-warm">signed engagement</span>',
    flowLead: 'A typical personal-injury or family-law intake flow.',
    flow: [
      { title: 'Call or chat', desc: 'Prospect contacts the firm any time.' },
      { title: 'Intake', desc: 'AI captures facts, dates, parties and urgency.' },
      { title: 'Screen & book', desc: 'Qualified matters booked; others referred politely.' },
      { title: 'Engage', desc: 'Engagement letter and documents requested automatically.' },
    ],
    services: ['ai-receptionist', 'ai-voice-agents', 'workflow-automation', 'ai-chatbots'],
    faqs: [
      { q: 'Will the AI give legal advice?', a: 'No. Agents are explicitly restricted to intake, scheduling and general firm information, and escalate anything resembling a request for advice.' },
      { q: 'Does it integrate with Clio?', a: 'Yes, we can create contacts and matters in Clio Grow/Manage and sync consultations, depending on your plan and API access.' },
      { q: 'How is confidentiality handled?', a: 'We scope data handling carefully, minimise stored data, use vendors with appropriate security commitments, and document everything for your review against professional-responsibility obligations.' },
      { q: 'Can it do conflict checks?', a: 'It can collect the party names and details needed for a conflict check and pass them to your team or system, the check itself stays with your firm.' },
    ],
  },

  'home-services': {
    noun: 'home-service businesses',
    title: 'AI for Home Service Businesses | AI Receptionist, Booking & Quote Follow-Up | Voxil AI',
    description: 'AI automation for plumbers, electricians, cleaners, landscapers and home-service businesses: 24/7 AI receptionist, job booking, missed-call text-back, quote follow-up and review requests.',
    h1: 'AI for home services that <span class="text-gradient-teal">books jobs while you work</span>',
    lead: 'Answer every call while you’re on the tools, book jobs into your field-service software, chase every quote and collect five-star reviews, automatically.',
    answer: '<strong>AI for home-service businesses</strong> answers calls and messages 24/7, captures job details and addresses, books jobs or estimates into field-service software, texts back missed calls, follows up on open quotes and requests reviews after completed jobs, so owner-operators stop losing work to unanswered phones.',
    facts: [
      { label: 'Answering', value: '24/7' },
      { label: 'Software', value: 'Jobber · HCP · ST' },
      { label: 'Reviews', value: 'Automated' },
      { label: 'Go-live', value: '1-3 weeks' },
    ],
    pills: ['AI receptionist', 'Job booking', 'Quote follow-up', 'Reviews'],
    painTitle: 'Where home-service businesses <span class="text-gradient-warm">lose jobs</span>',
    painLead: 'The phone rings while you’re under a sink. The customer calls the next company.',
    pains: [
      { title: 'Unanswered calls', desc: 'Calls on job sites go to voicemail, and most callers won’t leave one.' },
      { title: 'Quotes left hanging', desc: 'Estimates sent, never followed up.' },
      { title: 'Admin after hours', desc: 'Evenings spent returning calls and scheduling.' },
      { title: 'Too few reviews', desc: 'Happy customers rarely leave reviews unless asked.' },
    ],
    useLead: 'Built for owner-operators and growing crews alike.',
    uses: [
      { icon: 'phone', title: 'AI receptionist', desc: 'Answers, qualifies and books, or dispatches emergencies.' },
      { icon: 'bubble', title: 'Missed-call text-back', desc: 'Instant text to every missed caller to keep the lead.' },
      { icon: 'calendar', title: 'Job booking', desc: 'Books into Jobber, Housecall Pro or ServiceTitan.' },
      { icon: 'document', title: 'Quote follow-up', desc: 'Automatic nudges until the estimate is accepted.' },
      { icon: 'star', title: 'Review requests', desc: 'Timed asks after every completed job.' },
      { icon: 'refresh', title: 'Seasonal campaigns', desc: 'Maintenance reminders that fill quiet weeks.' },
    ],
    flowTitle: 'From missed call to <span class="text-gradient-warm">booked job</span>',
    flowLead: 'What happens when a customer calls while you’re working.',
    flow: [
      { title: 'Call comes in', desc: 'AI answers on the first ring.' },
      { title: 'Job details', desc: 'Issue, address, urgency and photos requested.' },
      { title: 'Book', desc: 'Slot booked in your software; confirmation sent.' },
      { title: 'After the job', desc: 'Invoice follow-up and review request automated.' },
    ],
    services: ['ai-phone-answering', 'ai-receptionist', 'ai-follow-up-system', 'gohighlevel-automation'],
    faqs: [
      { q: 'Does it work with Jobber, Housecall Pro or ServiceTitan?', a: 'Yes, we integrate with these and other field-service tools via their APIs or integration partners, depending on your plan.' },
      { q: 'Can the AI handle emergency calls?', a: 'Yes. It recognises emergencies you define (e.g. burst pipe, no heat) and immediately transfers or alerts your on-call tech.' },
      { q: 'Will it quote prices?', a: 'Only if you want it to, for example, fixed call-out fees or price ranges you approve. Otherwise it books an estimate.' },
      { q: 'What does it cost?', a: `A fixed setup fee plus low usage costs. Use our ${link('/resources/lead-loss-calculator/', 'lead loss calculator')} to see what missed calls may be costing you now.` },
    ],
  },

  'medical-clinics': {
    noun: 'medical practices',
    title: 'AI for Medical Clinics | AI Receptionist, Patient Scheduling & Reminders | Voxil AI',
    description: 'AI automation for medical clinics and practices: AI receptionist, patient scheduling, reminders, intake forms, FAQ handling and recall campaigns, HIPAA-aware and integrated with your practice software.',
    h1: 'AI for medical clinics that <span class="text-gradient-teal">frees the front desk</span>',
    lead: 'An AI receptionist that answers every patient call, books and reschedules, sends reminders and handles routine questions, with HIPAA-aware architecture and a clear path to staff.',
    answer: '<strong>AI for medical clinics</strong> automates patient communication: AI receptionists answer calls 24/7, schedule and reschedule appointments, send reminders, collect intake information, answer routine questions about hours, insurance and preparation, and route clinical or urgent matters to staff, using HIPAA-aware vendors and data practices.',
    facts: [
      { label: 'Phones', value: '24/7' },
      { label: 'Architecture', value: 'HIPAA-aware' },
      { label: 'Reminders', value: 'Automated' },
      { label: 'Go-live', value: '3-5 weeks' },
    ],
    pills: ['Patient scheduling', 'Reminders', 'Intake', 'Recall'],
    painTitle: 'Where clinics <span class="text-gradient-warm">lose patients</span>',
    painLead: 'Front desks are stretched thin; phones and no-shows suffer most.',
    pains: [
      { title: 'Hold times', desc: 'Patients hang up after waiting on hold during peak hours.' },
      { title: 'No-shows', desc: 'Missed appointments leave expensive gaps in schedules.' },
      { title: 'Repetitive questions', desc: 'Staff answer the same questions about hours, insurance and prep all day.' },
      { title: 'Recall gaps', desc: 'Patients due for follow-ups aren’t contacted consistently.' },
    ],
    useLead: 'Patient-communication automation with guardrails for healthcare.',
    uses: [
      { icon: 'phone', title: 'AI receptionist', desc: 'Answers every call; triages admin vs. clinical requests.' },
      { icon: 'calendar', title: 'Scheduling', desc: 'Books, reschedules and cancels in your scheduling system.' },
      { icon: 'clock', title: 'Reminders', desc: 'Confirmations and reminders with easy reschedule options.' },
      { icon: 'clipboard', title: 'Digital intake', desc: 'Pre-visit forms sent and chased automatically.' },
      { icon: 'question', title: 'Patient FAQs', desc: 'Hours, insurance accepted, directions and preparation.' },
      { icon: 'refresh', title: 'Recall campaigns', desc: 'Annual check-ups and follow-ups prompted on schedule.' },
    ],
    flowTitle: 'From phone call to <span class="text-gradient-warm">confirmed appointment</span>',
    flowLead: 'A typical new-patient booking flow.',
    flow: [
      { title: 'Patient calls', desc: 'AI answers instantly, no hold queue.' },
      { title: 'Identify need', desc: 'Appointment type and urgency determined; clinical questions routed.' },
      { title: 'Book', desc: 'Slot booked with the right provider.' },
      { title: 'Prepare', desc: 'Intake forms and reminders sent automatically.' },
    ],
    caseStudy: { label: 'Patient intake automation with chat and voice agents for multi-location clinics.', href: '/case-study-healthcare.html' },
    services: ['ai-receptionist', 'ai-appointment-booking', 'ai-customer-support', 'ai-voice-agents'],
    faqs: [
      { q: 'Is it HIPAA compliant?', a: 'HIPAA compliance depends on the whole system and your practices, not a single tool. We design HIPAA-aware architectures, use vendors willing to sign business associate agreements (BAAs), minimise stored PHI and document data flows for your compliance review.' },
      { q: 'Will the AI give medical advice?', a: 'No. It handles administrative tasks only and routes any clinical question or urgent symptom to staff or emergency guidance per your protocols.' },
      { q: 'Which practice-management systems do you integrate with?', a: 'It depends on API availability. We’ve integrated with scheduling tools and PM systems that expose APIs, and use staff-confirmation workflows where direct booking isn’t possible.' },
      { q: 'Can it handle multiple locations?', a: 'Yes, routing by location, provider and appointment type.' },
    ],
  },

  'med-spas': {
    noun: 'med spas',
    title: 'AI for Med Spas | Consultation Booking, Instagram DMs & Follow-Up | Voxil AI',
    description: 'AI automation for med spas and aesthetic clinics: instant replies to Instagram and ad leads, consultation booking with deposits, treatment reminders, rebooking and membership campaigns.',
    h1: 'AI for med spas that <span class="text-gradient-teal">books consultations 24/7</span>',
    lead: 'Reply to Instagram DMs and ad leads instantly, book consultations with deposits, remind clients when treatments are due and fill your calendar, without adding front-desk staff.',
    answer: '<strong>AI for med spas</strong> automates the client journey: AI agents reply instantly to Instagram, Facebook, website and ad enquiries, answer treatment and pricing questions within approved guidelines, book consultations with deposits, send pre- and post-care messages, and prompt clients to rebook when treatments are due.',
    facts: [
      { label: 'DM replies', value: 'Instant' },
      { label: 'Deposits', value: 'Supported' },
      { label: 'Rebooking', value: 'Automated' },
      { label: 'Go-live', value: '2-3 weeks' },
    ],
    pills: ['Instagram DMs', 'Consult booking', 'Deposits', 'Rebooking'],
    painTitle: 'Where med spas <span class="text-gradient-warm">lose clients</span>',
    painLead: 'Aesthetic clients are high-value, and they enquire with several clinics at once.',
    pains: [
      { title: 'Slow DM replies', desc: 'Late-night Instagram enquiries answered the next afternoon.' },
      { title: 'Consult no-shows', desc: 'Free consultations booked without commitment.' },
      { title: 'Missed rebooking', desc: 'Clients due for Botox or filler never get a reminder.' },
      { title: 'Ad spend waste', desc: 'Leads from paid ads left unworked.' },
    ],
    useLead: 'Premium, on-brand automation for aesthetic practices.',
    uses: [
      { icon: 'bubble', title: 'DM & chat replies', desc: 'Instant, on-brand replies across Instagram, Facebook and web.' },
      { icon: 'calendar', title: 'Consultation booking', desc: 'Book directly into Boulevard, Vagaro, GHL and more.' },
      { icon: 'currency', title: 'Deposits', desc: 'Payment links to cut consult no-shows.' },
      { icon: 'clock', title: 'Treatment reminders', desc: 'Rebooking prompts timed to each treatment’s cycle.' },
      { icon: 'sparkles', title: 'Memberships', desc: 'Membership offers and renewals automated.' },
      { icon: 'star', title: 'Reviews', desc: 'Post-treatment review requests at the right moment.' },
    ],
    flowTitle: 'From Instagram DM to <span class="text-gradient-warm">booked consultation</span>',
    flowLead: 'A typical injectables enquiry flow.',
    flow: [
      { title: 'DM arrives', desc: 'Client asks about lip filler at 11pm.' },
      { title: 'Instant reply', desc: 'AI answers approved FAQs and offers consult times.' },
      { title: 'Deposit & book', desc: 'Consult booked with deposit collected.' },
      { title: 'Nurture', desc: 'Reminders, prep info and rebooking later.' },
    ],
    services: ['ai-chatbots', 'ai-appointment-booking', 'gohighlevel-ai', 'marketing-automation'],
    faqs: [
      { q: 'Can the AI discuss treatments and pricing?', a: 'Within guidelines you approve, typically general treatment info and price ranges, with medical questions routed to your practitioners.' },
      { q: 'Does it work with Boulevard or Vagaro?', a: 'We integrate with booking platforms that offer APIs or integrations, including popular med-spa systems, or use GoHighLevel as the booking layer.' },
      { q: 'Can it reply to Instagram DMs?', a: 'Yes, via official Meta integrations for Instagram and Facebook messaging.' },
      { q: 'Will it sound on-brand?', a: 'Yes, we define tone, vocabulary and emoji use to match your brand, and review transcripts during the pilot.' },
    ],
  },

  roofing: {
    noun: 'roofing companies',
    title: 'AI for Roofing Companies | Storm Lead Response, Inspection Booking & Follow-Up | Voxil AI',
    description: 'AI automation for roofing contractors: instant storm-lead response, AI calls that qualify damage and insurance claims, inspection booking, estimate follow-up and review automation.',
    h1: 'AI for roofing companies that <span class="text-gradient-teal">wins the storm rush</span>',
    lead: 'When a storm hits, calls spike overnight. AI answers and calls back every lead in seconds, qualifies damage and insurance, books inspections and chases every estimate.',
    answer: '<strong>AI for roofing companies</strong> automates lead handling around storms and seasonal demand: AI agents answer and call back every lead instantly, ask about damage, roof age and insurance claims, book inspections, follow up on estimates and request reviews, scaling instantly when volume spikes.',
    facts: [
      { label: 'Storm scaling', value: 'Unlimited' },
      { label: 'Lead response', value: 'Seconds' },
      { label: 'Estimates', value: 'Followed up' },
      { label: 'Go-live', value: '2-3 weeks' },
    ],
    pills: ['Storm leads', 'Inspection booking', 'Insurance intake', 'Estimate follow-up'],
    painTitle: 'Where roofers <span class="text-gradient-warm">leave money on the roof</span>',
    painLead: 'Storm leads are worth a lot, and every competitor is calling them too.',
    pains: [
      { title: 'Storm surges', desc: 'Call volume spikes beyond what the office can answer.' },
      { title: 'Slow callbacks', desc: 'Homeowners sign with the first roofer who shows up.' },
      { title: 'Estimate drop-off', desc: 'Estimates delivered, then silence.' },
      { title: 'Review gaps', desc: 'Great jobs, few reviews, hurting local rankings.' },
    ],
    useLead: 'Automation designed around storm cycles and insurance jobs.',
    uses: [
      { icon: 'signal', title: 'Instant callbacks', desc: 'AI calls every form lead within seconds.' },
      { icon: 'clipboard', title: 'Damage & claim intake', desc: 'Captures damage type, roof age and insurer.' },
      { icon: 'calendar', title: 'Inspection booking', desc: 'Books inspections by territory and crew availability.' },
      { icon: 'document', title: 'Estimate follow-up', desc: 'Multi-week follow-up until signed.' },
      { icon: 'star', title: 'Review requests', desc: 'After every completed roof.' },
      { icon: 'refresh', title: 'Past-customer campaigns', desc: 'Post-storm check-ins with previous customers.' },
    ],
    flowTitle: 'From hail storm to <span class="text-gradient-warm">signed contract</span>',
    flowLead: 'What happens when your phones light up after a storm.',
    flow: [
      { title: 'Surge', desc: 'Dozens of calls and forms arrive in hours.' },
      { title: 'AI answers all', desc: 'Every lead contacted and qualified immediately.' },
      { title: 'Book inspections', desc: 'Routed by area to available inspectors.' },
      { title: 'Follow through', desc: 'Estimate and claim follow-up automated.' },
    ],
    services: ['ai-calling-bots', 'ai-phone-answering', 'ai-follow-up-system', 'gohighlevel-automation'],
    faqs: [
      { q: 'Can AI handle storm-season volume?', a: 'Yes, AI handles many calls at once, so surges don’t create hold queues or voicemail backlogs.' },
      { q: 'Does it integrate with AccuLynx or JobNimbus?', a: 'We integrate with roofing CRMs that offer APIs, including common platforms, or use GoHighLevel as the lead layer that syncs to your production system.' },
      { q: 'Is it compliant to call storm leads with AI?', a: 'Calling people who requested contact is generally fine, but AI-voice outbound calls require appropriate consent under the TCPA. We only call consented leads and respect calling hours.' },
      { q: 'Can it help with insurance claims?', a: 'It collects claim information and documents and schedules adjuster meetings, it doesn’t advise on claims.' },
    ],
  },

  solar: {
    noun: 'solar companies',
    title: 'AI for Solar Companies | Lead Qualification, Appointment Setting & Follow-Up | Voxil AI',
    description: 'AI automation for solar installers and sales teams: instant lead response, AI qualification of homeownership, roof and utility bill, consultation booking and long-cycle follow-up.',
    h1: 'AI for solar companies that <span class="text-gradient-teal">qualifies before you roll a truck</span>',
    lead: 'Respond to every solar lead instantly, qualify homeownership, roof and bill automatically, book consultations for serious homeowners and nurture the rest through a long buying cycle.',
    answer: '<strong>AI for solar companies</strong> automates lead response and appointment setting: AI agents contact new leads within seconds, qualify homeownership, roof suitability, average utility bill and credit readiness, book consultations with closers, and nurture unready leads over months, reducing wasted appointments and cost per sale.',
    facts: [
      { label: 'Lead response', value: 'Seconds' },
      { label: 'Qualification', value: 'Automated' },
      { label: 'Setters', value: 'AI + human' },
      { label: 'Go-live', value: '2-4 weeks' },
    ],
    pills: ['Appointment setting', 'Qualification', 'Long-term nurture', 'No-show recovery'],
    painTitle: 'Where solar <span class="text-gradient-warm">burns margin</span>',
    painLead: 'Solar leads are expensive, and many aren’t qualified.',
    pains: [
      { title: 'High cost per lead', desc: 'Paid leads go unworked or worked too slowly.' },
      { title: 'Unqualified appointments', desc: 'Renters, shaded roofs and tiny bills waste closer time.' },
      { title: 'Long buying cycles', desc: 'Homeowners take months to decide.' },
      { title: 'Appointment no-shows', desc: 'Booked consults don’t happen.' },
    ],
    useLead: 'AI appointment setting built for residential solar.',
    uses: [
      { icon: 'bolt', title: 'Speed-to-lead', desc: 'Every lead called or texted within seconds.' },
      { icon: 'funnel', title: 'Qualification', desc: 'Homeownership, roof, bill and timeline captured.' },
      { icon: 'calendar', title: 'Consult booking', desc: 'Qualified homeowners booked with closers.' },
      { icon: 'clock', title: 'No-show recovery', desc: 'Reminders and automatic rebooking.' },
      { icon: 'refresh', title: 'Long nurture', desc: 'Months of education and incentive updates.' },
      { icon: 'chart', title: 'Source ROI', desc: 'Cost per qualified appointment by lead vendor.' },
    ],
    flowTitle: 'From paid lead to <span class="text-gradient-warm">qualified consult</span>',
    flowLead: 'A typical residential solar funnel.',
    flow: [
      { title: 'Lead arrives', desc: 'From ads, vendors or your site.' },
      { title: 'AI contacts', desc: 'Call or text within seconds.' },
      { title: 'Qualify', desc: 'Ownership, roof, bill, timeline.' },
      { title: 'Book or nurture', desc: 'Consult booked or long-term nurture.' },
    ],
    services: ['ai-sdr-system', 'ai-calling-bots', 'ai-follow-up-system', 'lead-generation-funnel'],
    faqs: [
      { q: 'Can AI replace solar appointment setters?', a: 'It can handle first contact, qualification and booking at any volume; many teams keep human setters for complex conversations and let AI handle speed and scale.' },
      { q: 'Do you integrate with solar CRMs?', a: 'Yes, including GoHighLevel, HubSpot, Salesforce and solar-specific CRMs with APIs.' },
      { q: 'Is AI calling compliant for solar leads?', a: 'Solar has seen heavy TCPA enforcement. We only contact leads with documented consent, honour opt-outs and calling hours, and log everything.' },
      { q: 'Can the AI estimate savings?', a: 'It can share general information you approve; detailed proposals stay with your designers and closers.' },
    ],
  },

  'salons-beauty': {
    noun: 'salons and beauty businesses',
    title: 'AI for Salons & Beauty Businesses | AI Booking, Reminders & Rebooking | Voxil AI',
    description: 'AI automation for hair salons, barbers, nail and beauty studios: AI booking by phone, text and Instagram, reminders, rebooking prompts, gap filling and review requests.',
    h1: 'AI for salons that <span class="text-gradient-teal">keeps every chair full</span>',
    lead: 'Book appointments by phone, text and Instagram while stylists work, cut no-shows, prompt rebooking at the right time and fill last-minute gaps automatically.',
    answer: '<strong>AI for salons and beauty businesses</strong> handles bookings and client messaging automatically: AI answers calls and DMs, books services with the right stylist, sends reminders, prompts clients to rebook when they’re due, fills cancellations from a waitlist and requests reviews after appointments.',
    facts: [
      { label: 'Booking', value: 'Phone · DM · Web' },
      { label: 'Reminders', value: 'Automated' },
      { label: 'Gap filling', value: 'Waitlist' },
      { label: 'Go-live', value: '1-3 weeks' },
    ],
    pills: ['Phone & DM booking', 'Reminders', 'Rebooking', 'Gap filling'],
    painTitle: 'Where salons <span class="text-gradient-warm">lose bookings</span>',
    painLead: 'Stylists can’t answer phones mid-appointment.',
    pains: [
      { title: 'Missed calls', desc: 'Phones ring during appointments and go unanswered.' },
      { title: 'No-shows', desc: 'Empty chairs from forgotten appointments.' },
      { title: 'Late rebooking', desc: 'Clients drift to other salons between visits.' },
      { title: 'Last-minute gaps', desc: 'Cancellations leave chairs empty.' },
    ],
    useLead: 'Booking and retention automation for busy salons and studios.',
    uses: [
      { icon: 'phone', title: 'AI phone booking', desc: 'Books services and stylists while your team works.' },
      { icon: 'bubble', title: 'Instagram & text booking', desc: 'Books directly from DMs and texts.' },
      { icon: 'clock', title: 'Reminders', desc: 'Confirmations with easy rescheduling.' },
      { icon: 'refresh', title: 'Rebooking prompts', desc: 'Timed to each service’s cycle.' },
      { icon: 'users', title: 'Waitlist gap filling', desc: 'Offers cancelled slots instantly.' },
      { icon: 'star', title: 'Reviews', desc: 'Automatic review requests after visits.' },
    ],
    flowTitle: 'From Instagram DM to <span class="text-gradient-warm">booked chair</span>',
    flowLead: 'How a new client books without anyone picking up the phone.',
    flow: [
      { title: 'Enquiry', desc: 'Client DMs about balayage pricing.' },
      { title: 'AI replies', desc: 'Answers and offers available stylists and times.' },
      { title: 'Booked', desc: 'Appointment booked; deposit optional.' },
      { title: 'Retain', desc: 'Reminders and rebooking prompts later.' },
    ],
    services: ['ai-appointment-booking', 'ai-receptionist', 'email-sms-marketing', 'ai-chatbots'],
    faqs: [
      { q: 'Does it work with Vagaro, Fresha or Square Appointments?', a: 'We integrate with booking platforms that provide APIs or integrations and can use GoHighLevel as a booking layer where needed.' },
      { q: 'Can it book the right stylist for each service?', a: 'Yes, service-to-stylist rules, durations and processing times are configured.' },
      { q: 'Can clients rebook by text?', a: 'Yes, clients reply to reminders to confirm, cancel or reschedule.' },
      { q: 'Is it affordable for small salons?', a: 'Yes, setup is fixed-price and running costs scale with usage.' },
    ],
  },

  hvac: {
    noun: 'HVAC companies',
    title: 'AI for HVAC Companies | AI Receptionist, Dispatch Booking & Maintenance Plans | Voxil AI',
    description: 'AI automation for HVAC contractors: 24/7 AI receptionist: emergency triage, job booking, estimate follow-up, maintenance-plan renewals and seasonal tune-up campaigns.',
    h1: 'AI for HVAC companies that <span class="text-gradient-teal">answers every no-heat call</span>',
    lead: 'A 24/7 AI receptionist that triages emergencies, books service calls into your dispatch board, follows up on replacement estimates and fills quiet weeks with maintenance campaigns.',
    answer: '<strong>AI for HVAC companies</strong> answers every call day and night, triages emergencies like no heat or no cooling, books service calls and maintenance visits into field-service software, follows up on system-replacement estimates and runs seasonal tune-up and maintenance-plan campaigns to smooth demand.',
    facts: [
      { label: 'Answering', value: '24/7' },
      { label: 'Emergency triage', value: 'Built in' },
      { label: 'Software', value: 'ServiceTitan · HCP' },
      { label: 'Go-live', value: '2-3 weeks' },
    ],
    pills: ['Emergency triage', 'Service booking', 'Estimate follow-up', 'Maintenance plans'],
    painTitle: 'Where HVAC companies <span class="text-gradient-warm">lose revenue</span>',
    painLead: 'Demand swings with the weather, and so does the phone.',
    pains: [
      { title: 'Peak-season overload', desc: 'Heat waves and cold snaps overwhelm dispatch.' },
      { title: 'After-hours calls', desc: 'Emergency calls go to answering services that only take messages.' },
      { title: 'Replacement estimates', desc: 'High-value quotes not followed up.' },
      { title: 'Shoulder-season dips', desc: 'Quiet weeks between peaks.' },
    ],
    useLead: 'Automation that smooths the HVAC demand curve.',
    uses: [
      { icon: 'phone', title: 'AI receptionist', desc: 'Answers every call, 24/7, at any volume.' },
      { icon: 'bolt', title: 'Emergency triage', desc: 'Identifies no-heat/no-cool emergencies and dispatches.' },
      { icon: 'calendar', title: 'Service booking', desc: 'Books into ServiceTitan, Housecall Pro or Jobber.' },
      { icon: 'document', title: 'Estimate follow-up', desc: 'Nurtures replacement quotes to a decision.' },
      { icon: 'refresh', title: 'Maintenance plans', desc: 'Tune-up reminders and plan renewals.' },
      { icon: 'star', title: 'Reviews', desc: 'After every completed job.' },
    ],
    flowTitle: 'From 2am no-heat call to <span class="text-gradient-warm">dispatched tech</span>',
    flowLead: 'How emergencies are handled overnight.',
    flow: [
      { title: 'Call', desc: 'Homeowner calls at 2am with no heat.' },
      { title: 'Triage', desc: 'AI confirms emergency and collects details.' },
      { title: 'Dispatch', desc: 'On-call tech alerted; job created.' },
      { title: 'Follow-up', desc: 'Confirmation, ETA and review request after.' },
    ],
    services: ['ai-receptionist', 'ai-phone-answering', 'ai-follow-up-system', 'email-sms-marketing'],
    faqs: [
      { q: 'Does it integrate with ServiceTitan?', a: 'Yes, via ServiceTitan’s APIs or integration partners, depending on your account; Housecall Pro and Jobber are also supported.' },
      { q: 'Can it quote diagnostic fees?', a: 'Yes, if you want it to share fixed fees you approve.' },
      { q: 'How does emergency dispatch work?', a: 'You define emergency criteria; the AI alerts on-call staff by call and SMS and tells the customer what happens next.' },
      { q: 'Can it sell maintenance plans?', a: 'It can explain plans and book sign-up appointments or send payment links, using the plan details you provide.' },
    ],
  },

  chiropractic: {
    noun: 'chiropractic clinics',
    title: 'AI for Chiropractors | AI Receptionist, New Patient Booking & Reactivation | Voxil AI',
    description: 'AI automation for chiropractic clinics: AI receptionist, new-patient booking, reminders, care-plan follow-up, reactivation campaigns and review requests.',
    h1: 'AI for chiropractors that <span class="text-gradient-teal">keeps care plans on track</span>',
    lead: 'Answer every call, book new patients, reduce missed visits, follow up on care plans and reactivate inactive patients, without adding front-desk hours.',
    answer: '<strong>AI for chiropractic clinics</strong> automates patient communication: an AI receptionist answers calls and messages, books new-patient exams, sends reminders, follows up when patients fall off their care plans, runs reactivation campaigns for inactive patients and requests reviews, routing clinical questions to your team.',
    facts: [
      { label: 'Phones', value: '24/7' },
      { label: 'Care plans', value: 'Followed up' },
      { label: 'Reactivation', value: 'Automated' },
      { label: 'Go-live', value: '2-3 weeks' },
    ],
    pills: ['New patients', 'Reminders', 'Care-plan follow-up', 'Reactivation'],
    painTitle: 'Where chiropractic clinics <span class="text-gradient-warm">lose visits</span>',
    painLead: 'Patient retention through a care plan drives clinic revenue.',
    pains: [
      { title: 'Missed calls', desc: 'Busy adjustment hours mean unanswered phones.' },
      { title: 'Plan drop-off', desc: 'Patients stop attending before completing care.' },
      { title: 'Inactive patients', desc: 'Past patients rarely hear from the clinic.' },
      { title: 'Front-desk load', desc: 'Scheduling and reminders consume staff time.' },
    ],
    useLead: 'Patient-journey automation designed for chiropractic.',
    uses: [
      { icon: 'phone', title: 'AI receptionist', desc: 'Answers every call and books exams.' },
      { icon: 'calendar', title: 'New-patient booking', desc: 'From ads, web chat and phone.' },
      { icon: 'clock', title: 'Visit reminders', desc: 'Keep patients on schedule.' },
      { icon: 'refresh', title: 'Care-plan follow-up', desc: 'Detect missed visits and rebook.' },
      { icon: 'users', title: 'Reactivation', desc: 'Campaigns to inactive patients.' },
      { icon: 'star', title: 'Reviews', desc: 'Requests after positive visits.' },
    ],
    flowTitle: 'From Facebook ad to <span class="text-gradient-warm">care plan</span>',
    flowLead: 'A typical new-patient journey.',
    flow: [
      { title: 'Enquiry', desc: 'New patient responds to an offer.' },
      { title: 'Book exam', desc: 'AI books the first visit.' },
      { title: 'Stay on plan', desc: 'Reminders and missed-visit rebooking.' },
      { title: 'Reactivate', desc: 'Check-ins after the plan ends.' },
    ],
    services: ['ai-receptionist', 'ai-appointment-booking', 'gohighlevel-automation', 'ai-follow-up-system'],
    faqs: [
      { q: 'Does it integrate with ChiroTouch or Jane App?', a: 'We integrate with practice systems that offer APIs or integrations, and use staff-confirmation workflows where direct booking isn’t available.' },
      { q: 'Will it answer clinical questions?', a: 'No, clinical questions are routed to your team. The AI handles scheduling and general information.' },
      { q: 'Can it run reactivation campaigns?', a: 'Yes, targeted campaigns to patients who haven’t visited recently, with easy booking.' },
      { q: 'Is patient data protected?', a: 'We design HIPAA-aware systems using vendors that sign BAAs and minimise stored health data.' },
    ],
  },
};
