// Location page content. Each entry is unique local copy, markets, areas,
// industries and compliance notes, so no two pages are near-duplicates.
// Voxil AI is remote-first: never claim a local office or street address here.

const city = (name, state) => ({ '@type': 'City', name, containedInPlace: { '@type': 'State', name: state } });
const country = (name) => ({ '@type': 'Country', name });

const TCPA = 'Outbound AI calls and texts to US numbers fall under the TCPA and FCC rules, the FCC confirmed in 2024 that AI-generated voices count as "artificial" voices, so automated outbound calls need prior express consent.';

export default {
  // ------------------------------------------------------------- US EAST
  'new-york': {
    shortName: 'New York',
    description: 'AI automation agency serving New York City businesses: AI voice agents, receptionists, chatbots, GoHighLevel and CRM automation for finance, real estate, legal and healthcare teams.',
    lead: 'AI receptionists, voice agents, chatbots and CRM automation for New York businesses that can’t afford to miss a call or let a lead wait, built by a senior team working in Eastern Time.',
    answer: 'Voxil AI builds <strong>AI voice agents, chatbots and workflow automation for New York businesses</strong>, from Manhattan law firms and brokerages to Brooklyn clinics and Long Island home-service companies. Systems integrate with your CRM and calendar and go live in two to four weeks.',
    tzShort: 'Eastern Time',
    languages: 'EN · ES',
    pills: ['Manhattan', 'Brooklyn', 'Queens', 'Long Island'],
    marketTitle: 'In New York, response time is a competitive advantage',
    market: [
      'New York buyers expect answers now. Whether it’s a renter inquiring about a listing, a patient booking a same-week appointment or a prospect comparing three law firms, the first business to respond usually wins, and New York’s cost of staff makes 24/7 human coverage unrealistic for most firms.',
      'We see the strongest returns in brokerages, property managers, law firms, multi-location clinics and professional-services teams: AI answers every call and chat instantly, qualifies against your criteria, books into the right calendar and logs everything in your CRM. Bilingual English-Spanish agents are standard for teams serving the outer boroughs.',
    ],
    industries: ['real-estate', 'law-firms', 'medical-clinics', 'med-spas', 'insurance', 'fitness-gyms'],
    areas: ['Manhattan', 'Brooklyn', 'Queens', 'The Bronx', 'Staten Island', 'Long Island', 'Westchester', 'Jersey City & Hoboken'],
    services: ['ai-receptionist', 'ai-voice-agents', 'ai-chatbots', 'ai-sdr-system', 'crm-automation', 'ai-follow-up-system'],
    servicesLead: 'High-volume inquiries and expensive staff time make these the fastest payback projects for New York teams.',
    compliance: {
      title: 'New York compliance, designed in',
      text: `${TCPA} New York’s SHIELD Act also sets data-security expectations for businesses holding New Yorkers’ private information, and NYC regulates automated tools used in hiring decisions. We scope data retention, recording disclosures and consent handling up front.`,
    },
    faqs: [
      { q: 'Can an AI receptionist handle a busy New York office?', a: 'Yes. AI receptionists answer unlimited simultaneous calls, so lunch-hour spikes and after-hours inquiries never go to voicemail. Urgent calls transfer to your team; everything else is booked or summarized by text.' },
      { q: 'Do you build for New York real-estate teams?', a: 'Yes, listing-inquiry agents that answer questions, qualify renters and buyers, and book showings into agents’ calendars, integrated with CRMs like GoHighLevel, Follow Up Boss or HubSpot.' },
    ],
    schemaPlace: city('New York', 'New York'),
    nearby: ['philadelphia', 'charlotte'],
  },

  philadelphia: {
    description: 'AI automation for Philadelphia businesses: AI receptionists, voice agents, chatbots and CRM automation for healthcare, legal, education and home-service teams across Greater Philadelphia.',
    lead: 'Voice agents, chatbots and automation for Philadelphia’s healthcare, legal, education and home-service businesses, built to handle volume without adding headcount.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and automations for Philadelphia businesses</strong>, from Center City practices to Main Line and South Jersey service companies. Every system integrates with your existing tools and includes a supervised pilot before full launch.',
    tzShort: 'Eastern Time',
    languages: 'EN · ES',
    pills: ['Center City', 'University City', 'Main Line', 'South Jersey'],
    marketTitle: 'Eds, meds and the businesses that serve them',
    market: [
      'Philadelphia’s economy leans heavily on healthcare, life sciences, universities and the professional firms around them. That means appointment-heavy practices, intake-heavy law firms and patient- and student-facing teams fielding the same questions every day.',
      'Home-service companies across the suburbs and South Jersey face a different problem: calls arrive while crews are on jobs. AI phone answering and missed-call text-back recover those leads, and follow-up systems chase open estimates automatically.',
    ],
    industries: ['medical-clinics', 'law-firms', 'home-services', 'hvac', 'roofing', 'chiropractic'],
    areas: ['Center City', 'University City', 'Fishtown', 'King of Prussia', 'Main Line', 'Bucks County', 'Cherry Hill, NJ', 'Wilmington, DE'],
    services: ['ai-receptionist', 'ai-phone-answering', 'ai-appointment-booking', 'ai-customer-support', 'workflow-automation', 'ai-follow-up-system'],
    servicesLead: 'Appointment- and intake-heavy businesses see the fastest returns from these systems.',
    compliance: {
      title: 'Call-recording consent in Pennsylvania',
      text: `Pennsylvania is an all-party consent state for recording phone calls, so voice agents that record must disclose it at the start of the call. ${TCPA} We configure disclosures, consent capture and recording settings accordingly.`,
    },
    faqs: [
      { q: 'Can a voice agent legally record calls in Pennsylvania?', a: 'Yes, with proper disclosure. Because Pennsylvania requires all parties to consent to recording, we configure the agent to announce recording at the start of every call, or disable recording and keep transcripts only, depending on your needs and counsel’s advice.' },
      { q: 'Do you work with Philadelphia healthcare practices?', a: 'Yes, patient intake, appointment booking, reminders and FAQ handling, with HIPAA-aware architecture using vendors that sign business associate agreements.' },
    ],
    schemaPlace: city('Philadelphia', 'Pennsylvania'),
    nearby: ['new-york'],
  },

  charlotte: {
    description: 'AI automation agency serving Charlotte, NC: AI voice agents, chatbots, AI SDR systems and CRM automation for financial services, insurance, real estate and home-service businesses.',
    lead: 'AI SDRs, voice agents, chatbots and CRM automation for Charlotte’s financial services, insurance, real-estate and home-service businesses.',
    answer: 'Voxil AI builds <strong>AI voice agents, AI SDR systems and CRM automation for Charlotte businesses</strong>, helping banking, insurance, real-estate and home-service teams respond to every lead in seconds and keep pipelines moving without extra headcount.',
    tzShort: 'Eastern Time',
    languages: 'EN · ES',
    pills: ['Uptown', 'South End', 'Ballantyne', 'Lake Norman'],
    marketTitle: 'A finance city with a fast-growing service economy',
    market: [
      'Charlotte is one of the largest banking centers in the US, and the insurance agencies, mortgage brokers and advisors around it live and die by speed-to-lead and compliant follow-up. AI SDR systems and follow-up automation let small teams respond like big ones.',
      'Rapid population growth across Mecklenburg County and the surrounding region has also created intense demand for home services, roofing and real estate, businesses where missed calls translate directly into lost jobs.',
    ],
    industries: ['insurance', 'real-estate', 'home-services', 'roofing', 'hvac', 'law-firms'],
    areas: ['Uptown', 'South End', 'Ballantyne', 'Matthews', 'Huntersville', 'Concord', 'Mooresville', 'Rock Hill, SC'],
    services: ['ai-sdr-system', 'ai-calling-bots', 'crm-automation', 'ai-follow-up-system', 'ai-receptionist', 'lead-generation-funnel'],
    servicesLead: 'For lead-driven Charlotte businesses, speed and consistency of follow-up is where AI pays back first.',
    compliance: {
      title: 'Compliant outreach for financial services',
      text: `${TCPA} Insurance and financial-services teams also need careful record-keeping and approved messaging. We build consent tracking, approved talk tracks and full call logging into every system.`,
    },
    faqs: [
      { q: 'Can AI help Charlotte insurance agencies?', a: 'Yes, AI agents respond to quote requests instantly, collect underwriting details, book calls with licensed agents and run renewal and cross-sell reminders, all logged in your CRM or agency management system.' },
      { q: 'Do you integrate with Salesforce?', a: 'Yes. Many Charlotte financial firms run Salesforce; our agents create and update leads, log calls and trigger Flows.' },
    ],
    schemaPlace: city('Charlotte', 'North Carolina'),
    nearby: ['atlanta', 'nashville'],
  },

  atlanta: {
    description: 'AI automation agency serving Atlanta: AI receptionists, voice agents, chatbots, GoHighLevel and workflow automation for home services, real estate, logistics and healthcare businesses.',
    lead: 'AI receptionists, voice agents, GoHighLevel automation and workflow systems for Atlanta’s home-service, real-estate, healthcare and logistics businesses.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and GoHighLevel automation for Atlanta businesses</strong> across Metro Atlanta, from Buckhead brokerages to Alpharetta clinics and Gwinnett home-service companies, integrated with your CRM and live in weeks.',
    tzShort: 'Eastern Time',
    languages: 'EN · ES',
    pills: ['Buckhead', 'Midtown', 'Alpharetta', 'Marietta'],
    marketTitle: 'A sprawling metro where missed calls cost jobs',
    market: [
      'Metro Atlanta covers a huge area, and service businesses spend much of the day on the road. Calls come in while technicians are driving or on site, and callers who hit voicemail move on to the next result on Google.',
      'Atlanta is also a hub for logistics, payments and fintech, with plenty of B2B teams that benefit from AI SDRs and CRM automation. We build for both: phones answered for local service businesses, pipelines automated for B2B.',
    ],
    industries: ['home-services', 'hvac', 'roofing', 'real-estate', 'medical-clinics', 'fitness-gyms'],
    areas: ['Buckhead', 'Midtown', 'Downtown', 'Alpharetta', 'Marietta', 'Sandy Springs', 'Decatur', 'Gwinnett County'],
    services: ['ai-phone-answering', 'ai-receptionist', 'gohighlevel-automation', 'ai-follow-up-system', 'ai-sdr-system', 'workflow-automation'],
    servicesLead: 'Field-service and multi-location businesses in Atlanta get the fastest wins from phone and follow-up automation.',
    compliance: {
      title: 'Built for compliant calling and texting',
      text: `${TCPA} For SMS, US carriers require A2P 10DLC registration for business texting from standard numbers. We handle registration guidance, opt-outs and quiet hours.`,
    },
    faqs: [
      { q: 'Can AI answer calls for my Atlanta HVAC or plumbing company?', a: 'Yes. An AI receptionist answers every call, captures the address and issue, books the job into your field-service software and flags emergencies to your on-call tech.' },
      { q: 'Do you set up GoHighLevel for Atlanta businesses?', a: 'Yes, full GHL setup, automation, AI and snapshots, including missed-call text-back and review requests.' },
    ],
    schemaPlace: city('Atlanta', 'Georgia'),
    nearby: ['charlotte', 'nashville', 'miami'],
  },

  miami: {
    description: 'Bilingual AI automation for Miami businesses: English and Spanish AI voice agents, WhatsApp chatbots, receptionists and CRM automation for real estate, med spas, hospitality and trade.',
    lead: 'Bilingual English-Spanish voice agents, WhatsApp bots and CRM automation for Miami’s real-estate, med-spa, hospitality and international-trade businesses.',
    answer: 'Voxil AI builds <strong>bilingual AI voice agents, WhatsApp chatbots and CRM automation for Miami businesses</strong>. Agents switch between English and Spanish automatically, answer 24/7 and book directly into your calendar, ideal for South Florida’s international, always-on market.',
    tzShort: 'Eastern Time',
    languages: 'EN · ES · PT',
    pills: ['Brickell', 'Miami Beach', 'Coral Gables', 'Fort Lauderdale'],
    marketTitle: 'Bilingual by default, WhatsApp-first by habit',
    market: [
      'Miami businesses serve customers in English and Spanish every day, many of them international buyers and visitors who prefer WhatsApp to phone calls or email. An English-only, business-hours operation leaves money on the table.',
      'We see particularly strong results in luxury real estate, med spas and aesthetics, hospitality and import/export: bilingual agents answer instantly on phone and WhatsApp, qualify inquiries and book viewings or consultations while your team sleeps.',
    ],
    industries: ['real-estate', 'med-spas', 'salons-beauty', 'law-firms', 'insurance', 'medical-clinics'],
    areas: ['Brickell', 'Downtown', 'Miami Beach', 'Coral Gables', 'Doral', 'Aventura', 'Fort Lauderdale', 'Boca Raton'],
    services: ['ai-voice-agents', 'whatsapp-automation', 'ai-chatbots', 'ai-appointment-booking', 'ai-receptionist', 'marketing-automation'],
    servicesLead: 'For Miami’s bilingual, international customer base, these deliver the biggest lift.',
    compliance: {
      title: 'Florida calling and recording rules',
      text: `Florida requires all-party consent to record calls and has its own telemarketing law (the Florida Telephone Solicitation Act) on top of federal rules. ${TCPA} We configure disclosures, consent and calling windows for Florida.`,
    },
    faqs: [
      { q: 'Can the AI speak Spanish?', a: 'Yes. Our voice and chat agents detect the caller’s language and respond in fluent Spanish or English, and we can add Portuguese for Brazilian clients.' },
      { q: 'Is WhatsApp automation useful in Miami?', a: 'Very. Many Miami customers, especially international buyers, prefer WhatsApp. We set up the official WhatsApp Business Platform with an AI assistant connected to your CRM.' },
    ],
    schemaPlace: city('Miami', 'Florida'),
    nearby: ['atlanta'],
  },

  nashville: {
    description: 'AI automation agency serving Nashville: AI receptionists, voice agents, chatbots and CRM automation for healthcare, home services, real estate, hospitality and entertainment businesses.',
    lead: 'AI receptionists, voice agents and automation for Nashville’s healthcare, home-service, real-estate and hospitality businesses, growing as fast as the city.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for Nashville businesses</strong> in Middle Tennessee, helping practices, service companies and real-estate teams answer every inquiry and book appointments automatically.',
    tzShort: 'Central Time',
    languages: 'EN · ES',
    pills: ['Downtown', 'The Gulch', 'Brentwood', 'Franklin'],
    marketTitle: 'A boomtown with more demand than front desks',
    market: [
      'Nashville is a national center for healthcare management and one of the fastest-growing metros in the country. Practices, clinics and healthcare-adjacent businesses face constant scheduling demand, and hiring front-desk staff fast enough is hard.',
      'Growth also means construction, home services and real estate booming across Williamson and Rutherford counties. AI phone answering, quote follow-up and review automation help these businesses keep up without burning out their teams.',
    ],
    industries: ['medical-clinics', 'home-services', 'real-estate', 'chiropractic', 'roofing', 'fitness-gyms'],
    areas: ['Downtown', 'The Gulch', 'East Nashville', 'Brentwood', 'Franklin', 'Murfreesboro', 'Hendersonville', 'Mount Juliet'],
    services: ['ai-receptionist', 'ai-appointment-booking', 'ai-phone-answering', 'ai-customer-support', 'gohighlevel-automation', 'email-sms-marketing'],
    servicesLead: 'Scheduling-heavy and field-service businesses in Middle Tennessee see the quickest payback here.',
    compliance: {
      title: 'Healthcare-ready by design',
      text: `For Nashville’s healthcare businesses, we design HIPAA-aware architectures using vendors that sign business associate agreements and minimize stored health data. ${TCPA}`,
    },
    faqs: [
      { q: 'Can an AI receptionist book patients into our practice software?', a: 'Often, yes, if your practice-management or scheduling software offers an API or integration. If not, the agent captures requests for one-click confirmation by staff.' },
      { q: 'Do you work in Central Time?', a: 'Yes. We schedule calls and working sessions inside Central Time business hours.' },
    ],
    schemaPlace: city('Nashville', 'Tennessee'),
    nearby: ['atlanta', 'charlotte', 'chicago'],
  },

  // ---------------------------------------------------------- US CENTRAL
  chicago: {
    description: 'AI automation agency serving Chicago: AI voice agents, chatbots, workflow and CRM automation for professional services, healthcare, logistics, real estate and home-service businesses.',
    lead: 'Voice agents, chatbots and workflow automation for Chicago’s professional-services, healthcare, logistics and home-service businesses, built with Illinois’ strict privacy rules in mind.',
    answer: 'Voxil AI builds <strong>AI voice agents, chatbots, workflow and CRM automation for Chicago businesses</strong>, from Loop law firms and River North agencies to suburban clinics and contractors, designed around Illinois’ biometric and recording-consent laws.',
    tzShort: 'Central Time',
    languages: 'EN · ES · PL',
    pills: ['The Loop', 'River North', 'Naperville', 'Schaumburg'],
    marketTitle: 'A diverse economy with serious operations work',
    market: [
      'Chicago’s economy is unusually broad, trading and finance, manufacturing, logistics, healthcare, legal and a deep bench of professional-services firms. The common thread is process-heavy operations where workflow automation removes hours of manual work every week.',
      'For customer-facing businesses, Chicago’s winters and dense suburbs drive huge seasonal swings in call volume for HVAC, roofing and home services. AI phone answering absorbs the spikes without temporary staff.',
    ],
    industries: ['law-firms', 'medical-clinics', 'hvac', 'insurance', 'real-estate', 'home-services'],
    areas: ['The Loop', 'River North', 'West Loop', 'Lincoln Park', 'Evanston', 'Oak Brook', 'Naperville', 'Schaumburg'],
    services: ['workflow-automation', 'ai-voice-agents', 'ai-phone-answering', 'crm-automation', 'ai-customer-support', 'n8n-automation'],
    servicesLead: 'Operations-heavy Chicago businesses get the most from workflow and voice automation.',
    compliance: {
      title: 'Illinois BIPA and recording consent',
      text: 'Illinois’ Biometric Information Privacy Act (BIPA) covers voiceprints, so voice systems must not create speaker-identification profiles without informed written consent. Illinois also restricts recording private conversations without all parties’ consent. We design voice agents that avoid voiceprint biometrics and disclose recording clearly.',
    },
    faqs: [
      { q: 'Are AI voice agents allowed under Illinois BIPA?', a: 'Standard voice agents that transcribe speech and don’t build voiceprints for identification generally avoid BIPA’s biometric scope, but you should confirm with counsel. We deliberately avoid speaker-identification features for Illinois clients and document data handling.' },
      { q: 'Can you automate back-office work for Chicago firms?', a: 'Yes, document intake, data extraction, CRM updates, approvals and reporting using Make.com, n8n or custom integrations.' },
    ],
    schemaPlace: city('Chicago', 'Illinois'),
    nearby: ['nashville', 'dallas', 'denver'],
  },

  dallas: {
    description: 'AI automation agency serving Dallas-Fort Worth: AI voice agents, AI SDR systems, chatbots, GoHighLevel and CRM automation for real estate, insurance, roofing, HVAC and corporate teams.',
    lead: 'AI SDRs, voice agents, GoHighLevel and CRM automation for DFW’s real-estate, insurance, roofing, HVAC and corporate sales teams.',
    answer: 'Voxil AI builds <strong>AI voice agents, AI SDR systems and CRM automation for Dallas-Fort Worth businesses</strong>, from Uptown brokerages and Plano sales teams to roofing and HVAC companies across the Metroplex, integrated with your stack and live in weeks.',
    tzShort: 'Central Time',
    languages: 'EN · ES',
    pills: ['Uptown', 'Plano', 'Frisco', 'Fort Worth'],
    marketTitle: 'Big market, big competition, short attention spans',
    market: [
      'DFW is home to a dense concentration of corporate headquarters and sales teams, plus one of the most active housing and construction markets in the country. In both worlds, the fastest responder wins.',
      'North Texas storms also drive surges in roofing and restoration leads. AI calling bots and follow-up systems let contractors respond to every storm lead in minutes, qualify for insurance claims and book inspections automatically.',
    ],
    industries: ['real-estate', 'roofing', 'insurance', 'hvac', 'solar', 'home-services'],
    areas: ['Uptown', 'Downtown', 'Plano', 'Frisco', 'Irving', 'Arlington', 'McKinney', 'Fort Worth'],
    services: ['ai-sdr-system', 'ai-calling-bots', 'gohighlevel-automation', 'ai-follow-up-system', 'crm-automation', 'ai-receptionist'],
    servicesLead: 'Lead-heavy DFW businesses get the most out of speed-to-lead and follow-up automation.',
    compliance: {
      title: 'Texas privacy and calling rules',
      text: `Texas’ Data Privacy and Security Act (in effect since 2024) adds consumer-data obligations, and Texas has its own telemarketing registration rules. ${TCPA} We build consent, opt-out and data-minimization into every build.`,
    },
    faqs: [
      { q: 'Can AI handle storm-season roofing leads?', a: 'Yes. AI calling bots contact new leads within seconds, ask about damage and insurance, and book inspections, scaling instantly when storm volume spikes.' },
      { q: 'Do you build AI SDRs for B2B teams in Dallas?', a: 'Yes, inbound lead response, qualification and meeting booking integrated with Salesforce, HubSpot or your CRM.' },
    ],
    schemaPlace: city('Dallas', 'Texas'),
    nearby: ['houston', 'austin', 'san-antonio'],
  },

  houston: {
    description: 'AI automation agency serving Houston: AI receptionists, voice agents, chatbots and CRM automation for healthcare, energy, home services, HVAC, roofing and legal businesses.',
    lead: 'AI receptionists, bilingual voice agents and automation for Houston’s healthcare, energy, home-service and legal businesses.',
    answer: 'Voxil AI builds <strong>AI receptionists, bilingual voice agents, chatbots and CRM automation for Houston businesses</strong>, from Texas Medical Center-area practices to HVAC, roofing and legal teams across Greater Houston, answering every call in English or Spanish, 24/7.',
    tzShort: 'Central Time',
    languages: 'EN · ES · VI',
    pills: ['Galleria', 'The Woodlands', 'Katy', 'Sugar Land'],
    marketTitle: 'Healthcare, energy and a relentless service economy',
    market: [
      'Houston is home to the world’s largest medical complex and a vast network of clinics and practices around it, businesses where scheduling, reminders and intake consume enormous staff time.',
      'Heat and hurricane seasons make HVAC, roofing and restoration critical services, with call volumes that spike overnight. And Houston’s diversity means bilingual service is a must. AI agents answer every call in English or Spanish and scale instantly with demand.',
    ],
    industries: ['medical-clinics', 'hvac', 'roofing', 'law-firms', 'home-services', 'insurance'],
    areas: ['Downtown', 'Galleria / Uptown', 'Medical Center', 'The Woodlands', 'Katy', 'Sugar Land', 'Pearland', 'Cypress'],
    services: ['ai-receptionist', 'ai-voice-agents', 'ai-phone-answering', 'ai-appointment-booking', 'ai-follow-up-system', 'ai-customer-support'],
    servicesLead: 'Call-heavy Houston businesses, clinics, HVAC and legal, see the fastest payback here.',
    compliance: {
      title: 'Texas privacy, healthcare and calling rules',
      text: `We build HIPAA-aware systems for Houston healthcare providers and follow Texas’ Data Privacy and Security Act. ${TCPA}`,
    },
    faqs: [
      { q: 'Can the AI receptionist handle Spanish-speaking callers?', a: 'Yes, it detects language automatically and responds fluently in Spanish or English. We can add Vietnamese and other languages common in Houston.' },
      { q: 'Can AI handle HVAC emergency calls in a heat wave?', a: 'Yes. It answers unlimited calls at once, identifies emergencies, dispatches on-call techs and books routine jobs, so no-cooling calls are never lost.' },
    ],
    schemaPlace: city('Houston', 'Texas'),
    nearby: ['dallas', 'austin', 'san-antonio'],
  },

  'san-antonio': {
    description: 'Bilingual AI automation for San Antonio businesses: English and Spanish AI receptionists, voice agents, chatbots and CRM automation for healthcare, home services, legal and hospitality.',
    lead: 'Bilingual AI receptionists, voice agents and automation for San Antonio’s healthcare, home-service, legal and hospitality businesses.',
    answer: 'Voxil AI builds <strong>bilingual AI receptionists, voice agents and automation for San Antonio businesses</strong>. Agents answer in English or Spanish, book appointments and follow up automatically, ideal for a city where bilingual service is the norm.',
    tzShort: 'Central Time',
    languages: 'EN · ES',
    pills: ['Downtown', 'Stone Oak', 'Alamo Heights', 'New Braunfels'],
    marketTitle: 'Bilingual service is table stakes here',
    market: [
      'San Antonio is one of the largest majority-Hispanic metros in the US, and many customers prefer Spanish on the phone. Bilingual AI agents give every caller a natural conversation in their language without the challenge of hiring bilingual staff for every shift.',
      'Healthcare and bioscience, military-connected services, tourism and a fast-growing suburban housing market drive demand for scheduling, intake and home-service automation.',
    ],
    industries: ['medical-clinics', 'home-services', 'law-firms', 'hvac', 'chiropractic', 'insurance'],
    areas: ['Downtown', 'Alamo Heights', 'Stone Oak', 'Medical Center', 'New Braunfels', 'Boerne', 'Schertz', 'Helotes'],
    services: ['ai-receptionist', 'ai-voice-agents', 'ai-appointment-booking', 'ai-phone-answering', 'whatsapp-automation', 'crm-setup'],
    servicesLead: 'Bilingual voice and booking automation delivers the quickest wins in San Antonio.',
    compliance: {
      title: 'Texas rules, bilingual disclosures',
      text: `We deliver consent and recording disclosures in both English and Spanish, and follow Texas privacy law. ${TCPA}`,
    },
    faqs: [
      { q: 'Does the Spanish voice sound natural?', a: 'Yes. We select native-quality Spanish voices and tune pronunciation for local names and places, then test with real callers during the pilot.' },
      { q: 'Can personal-injury law firms use AI intake?', a: 'Yes, 24/7 intake that captures case details, screens for fit, and books consultations, with sensitive topics routed to your team.' },
    ],
    schemaPlace: city('San Antonio', 'Texas'),
    nearby: ['austin', 'houston', 'dallas'],
  },

  austin: {
    description: 'AI automation agency serving Austin: AI agents, chatbots, n8n and API automation, AI SaaS development and CRM automation for startups, tech companies and fast-growing service businesses.',
    lead: 'AI agents, SaaS builds, n8n and API automation for Austin startups, plus voice and chat automation for the service businesses keeping up with the city’s growth.',
    answer: 'Voxil AI builds <strong>AI agents, AI SaaS products, n8n workflows and CRM automation for Austin businesses</strong>, from Domain-area startups adding AI features to Round Rock and Cedar Park service companies automating calls and follow-up.',
    tzShort: 'Central Time',
    languages: 'EN · ES',
    pills: ['Downtown', 'The Domain', 'Round Rock', 'Cedar Park'],
    marketTitle: 'Tech-forward buyers, rapid growth',
    market: [
      'Austin’s startup and tech scene means many clients want more than off-the-shelf tools: custom AI features in their product, self-hosted n8n agents, and integrations engineered to scale. We work as an extension of your engineering team.',
      'At the same time, the region’s rapid growth has stretched home-service, real-estate and healthcare businesses thin. AI receptionists and follow-up systems help them serve more customers without proportional hiring.',
    ],
    industries: ['real-estate', 'home-services', 'fitness-gyms', 'med-spas', 'solar', 'medical-clinics'],
    areas: ['Downtown', 'The Domain', 'East Austin', 'Round Rock', 'Cedar Park', 'Georgetown', 'Pflugerville', 'San Marcos'],
    services: ['ai-saas-development', 'ai-chatbot-developer', 'n8n-automation', 'api-integration', 'ai-receptionist', 'ai-sdr-system'],
    servicesLead: 'Austin clients split between product-level AI engineering and customer-facing automation.',
    compliance: {
      title: 'Secure engineering for tech teams',
      text: `We follow secure development practices, secrets management, least-privilege access, audit logging, and Texas privacy law. For outbound calling, ${TCPA.charAt(0).toLowerCase() + TCPA.slice(1)}`,
    },
    faqs: [
      { q: 'Can you add AI features to our SaaS product?', a: 'Yes, RAG search, AI assistants, agents with tool calling and voice features, built in your codebase with evaluations and cost controls.' },
      { q: 'Do you self-host n8n?', a: 'Yes. We deploy n8n on your cloud with SSO, backups and queue-mode scaling, then build workflows and AI agents on it.' },
    ],
    schemaPlace: city('Austin', 'Texas'),
    nearby: ['san-antonio', 'dallas', 'houston'],
  },

  // ------------------------------------------------------------- US WEST
  'los-angeles': {
    description: 'AI automation agency serving Los Angeles: bilingual AI voice agents, chatbots, WhatsApp and CRM automation for med spas, real estate, entertainment, ecommerce and legal businesses.',
    lead: 'Bilingual voice agents, chatbots and CRM automation for LA’s med-spa, real-estate, entertainment, ecommerce and legal businesses, California-compliant by design.',
    answer: 'Voxil AI builds <strong>bilingual AI voice agents, chatbots and CRM automation for Los Angeles businesses</strong>, from Beverly Hills med spas and Santa Monica brands to Pasadena law firms, configured for California’s bot-disclosure, recording and privacy laws.',
    tzShort: 'Pacific Time',
    languages: 'EN · ES · KO',
    pills: ['Santa Monica', 'Beverly Hills', 'Pasadena', 'Orange County'],
    marketTitle: 'High-value customers who expect instant, polished service',
    market: [
      'LA’s aesthetics, med-spa and wellness market is among the most competitive in the world. Prospects inquire with several clinics at once, often late at night on Instagram, the clinic that replies and books first wins the consultation.',
      'Real estate, entertainment, DTC ecommerce and legal services share the same pattern: high-value leads, high expectations, and lots of after-hours inquiries. AI agents give every lead an instant, on-brand response in English or Spanish.',
    ],
    industries: ['med-spas', 'real-estate', 'salons-beauty', 'law-firms', 'fitness-gyms', 'solar'],
    areas: ['Downtown LA', 'Santa Monica', 'Beverly Hills', 'West Hollywood', 'Pasadena', 'Burbank', 'Long Beach', 'Irvine / OC'],
    services: ['ai-chatbots', 'ai-voice-agents', 'ai-appointment-booking', 'marketing-automation', 'whatsapp-automation', 'gohighlevel-ai'],
    servicesLead: 'For LA’s high-touch businesses, instant response and effortless booking move the needle most.',
    compliance: {
      title: 'California bot disclosure, recording and privacy',
      text: 'California requires bots to disclose they are bots when used to incentivize a sale in online communications, requires all-party consent to record calls, and grants consumers rights under the CCPA/CPRA. We configure clear AI disclosure, recording notices and data-handling documentation for every California deployment.',
    },
    faqs: [
      { q: 'Does California require AI chatbots to disclose they are bots?', a: 'California’s bot-disclosure law requires clear disclosure when a bot is used to incentivize a purchase or influence a vote in online communications. We make disclosure explicit by default for all California clients.' },
      { q: 'Can AI book consultations for med spas?', a: 'Yes, from Instagram, website chat, WhatsApp or phone, directly into Boulevard, Vagaro, GoHighLevel or your booking tool, with deposit collection if you want it.' },
    ],
    schemaPlace: city('Los Angeles', 'California'),
    nearby: ['san-diego', 'san-francisco', 'phoenix'],
  },

  'san-francisco': {
    description: 'AI automation and AI engineering for San Francisco Bay Area companies: AI agents, RAG chatbots, AI SaaS development, API and n8n automation, plus voice and CRM automation.',
    lead: 'Senior AI engineering for Bay Area startups and scale-ups, agents, RAG, SaaS features and integrations, plus voice, chat and CRM automation for customer-facing teams.',
    answer: 'Voxil AI provides <strong>AI engineering and automation for San Francisco Bay Area companies</strong>: production AI agents, RAG chatbots, AI SaaS features, API integrations and self-hosted automation, delivered by a senior team that ships, at a fraction of Bay Area hiring costs.',
    tzShort: 'Pacific Time',
    languages: 'EN · ES · ZH',
    pills: ['SoMa', 'Financial District', 'Oakland', 'Palo Alto'],
    marketTitle: 'Where AI is the product, not a feature',
    market: [
      'The Bay Area is the center of AI development, and many local companies need extra senior hands to ship AI features, agents with tool calling, retrieval over large document sets, evaluation pipelines and cost controls. We slot into your repo and process.',
      'For go-to-market teams, AI SDRs and CRM automation help lean startups respond to inbound demand instantly and keep pipelines clean without adding ops headcount.',
    ],
    industries: ['real-estate', 'law-firms', 'medical-clinics', 'insurance', 'fitness-gyms', 'med-spas'],
    areas: ['SoMa', 'Financial District', 'Mission', 'Oakland', 'Berkeley', 'Palo Alto', 'Walnut Creek', 'San Mateo'],
    services: ['ai-chatbot-developer', 'ai-saas-development', 'api-integration', 'n8n-automation', 'ai-sdr-system', 'crm-automation'],
    servicesLead: 'Bay Area clients mostly engage us for AI engineering and GTM automation.',
    compliance: {
      title: 'California privacy and AI transparency',
      text: 'We design for CCPA/CPRA obligations, California’s bot-disclosure and all-party recording-consent rules, and your own security requirements, with data-processing documentation and least-privilege access.',
    },
    faqs: [
      { q: 'Can you work inside our existing engineering process?', a: 'Yes, your repo, your CI, pull requests reviewed by your team, and your ticketing system.' },
      { q: 'Do you build evaluation pipelines for LLM features?', a: 'Yes. We create test sets and automated scoring for retrieval and answer quality, run on every change.' },
    ],
    schemaPlace: city('San Francisco', 'California'),
    nearby: ['san-jose', 'los-angeles', 'seattle'],
  },

  'san-jose': {
    description: 'AI automation for San Jose and Silicon Valley: AI agents, chatbots, API integration, AI SaaS development and workflow automation for tech companies and local service businesses.',
    lead: 'AI agents, integrations and workflow automation for Silicon Valley companies, and voice and chat automation for the South Bay businesses that serve them.',
    answer: 'Voxil AI builds <strong>AI agents, chatbots, API integrations and workflow automation for San Jose and Silicon Valley businesses</strong>, engineering-grade systems for tech teams and practical voice and chat automation for South Bay service providers.',
    tzShort: 'Pacific Time',
    languages: 'EN · ES · VI',
    pills: ['Downtown SJ', 'Santa Clara', 'Sunnyvale', 'Mountain View'],
    marketTitle: 'Engineering culture meets everyday service demand',
    market: [
      'Silicon Valley hardware, semiconductor and enterprise-software companies often need internal AI tools: document assistants, support agents and automated workflows between engineering, sales and support systems.',
      'Meanwhile, South Bay households keep clinics, dental practices, home-service and real-estate businesses busy. AI receptionists and booking agents help them handle demand in multiple languages.',
    ],
    industries: ['medical-clinics', 'real-estate', 'home-services', 'law-firms', 'hvac', 'chiropractic'],
    areas: ['Downtown San José', 'Santa Clara', 'Sunnyvale', 'Mountain View', 'Cupertino', 'Milpitas', 'Campbell', 'Los Gatos'],
    services: ['api-integration', 'ai-chatbot-developer', 'workflow-automation', 'ai-customer-support', 'ai-receptionist', 'ai-saas-development'],
    servicesLead: 'Tech and service businesses in the South Bay lean on these most.',
    compliance: {
      title: 'California privacy by design',
      text: 'CCPA/CPRA, bot disclosure and all-party recording consent are built into every California deployment, with documented data flows for your security review.',
    },
    faqs: [
      { q: 'Can you build internal AI assistants for our team?', a: 'Yes, secure assistants over your docs, tickets and wikis, with permissions that respect who can see what.' },
      { q: 'Do you support Vietnamese-speaking callers?', a: 'Yes, our voice agents can handle Vietnamese alongside English and Spanish.' },
    ],
    schemaPlace: city('San Jose', 'California'),
    nearby: ['san-francisco', 'los-angeles', 'san-diego'],
  },

  'san-diego': {
    description: 'AI automation agency serving San Diego: bilingual AI receptionists, voice agents, chatbots and CRM automation for healthcare, biotech, real estate, hospitality and home-service businesses.',
    lead: 'Bilingual AI receptionists, voice agents and automation for San Diego’s healthcare, life-science, real-estate, hospitality and home-service businesses.',
    answer: 'Voxil AI builds <strong>bilingual AI receptionists, voice agents, chatbots and CRM automation for San Diego businesses</strong>, from La Jolla practices to North County contractors, California-compliant and live in weeks.',
    tzShort: 'Pacific Time',
    languages: 'EN · ES',
    pills: ['Downtown', 'La Jolla', 'Carlsbad', 'Chula Vista'],
    marketTitle: 'Healthcare, life sciences and a border-region customer base',
    market: [
      'San Diego’s life-science and healthcare clusters create strong demand for patient intake, scheduling and support automation, and for secure internal AI tools in research-driven organizations.',
      'Hospitality, military-connected families and cross-border customers make bilingual, always-on service important. AI agents cover every hour and language without stretching your team.',
    ],
    industries: ['medical-clinics', 'real-estate', 'med-spas', 'home-services', 'solar', 'chiropractic'],
    areas: ['Downtown', 'La Jolla', 'Mission Valley', 'Carlsbad', 'Oceanside', 'Escondido', 'Chula Vista', 'El Cajon'],
    services: ['ai-receptionist', 'ai-appointment-booking', 'ai-voice-agents', 'ai-customer-support', 'ai-chatbots', 'lead-generation-funnel'],
    servicesLead: 'For San Diego’s appointment-driven businesses, these systems pay back fastest.',
    compliance: {
      title: 'California rules, healthcare-aware',
      text: 'All-party recording consent, bot disclosure and CCPA/CPRA obligations are handled by default; healthcare deployments use HIPAA-aware architectures and BAA-signing vendors.',
    },
    faqs: [
      { q: 'Can solar companies in San Diego use AI follow-up?', a: 'Yes, instant response to quote requests, qualification (roof, bill, ownership), and automated follow-up until the consultation is booked.' },
      { q: 'Is bilingual support included?', a: 'Yes. English and Spanish are standard for San Diego deployments.' },
    ],
    schemaPlace: city('San Diego', 'California'),
    nearby: ['los-angeles', 'phoenix', 'san-jose'],
  },

  seattle: {
    description: 'AI automation agency serving Seattle: AI agents, chatbots, voice agents, workflow and CRM automation for tech, healthcare, professional services and home-service businesses.',
    lead: 'AI agents, chatbots and workflow automation for Seattle’s tech, healthcare and professional-services companies, with Washington’s health-data and recording laws built in.',
    answer: 'Voxil AI builds <strong>AI agents, chatbots, voice agents and workflow automation for Seattle businesses</strong>, from South Lake Union tech teams to Bellevue clinics and Eastside contractors, designed around Washington’s privacy and recording-consent rules.',
    tzShort: 'Pacific Time',
    languages: 'EN · ES · ZH',
    pills: ['South Lake Union', 'Bellevue', 'Redmond', 'Tacoma'],
    marketTitle: 'Cloud-native buyers with high standards',
    market: [
      'Seattle and the Eastside are home to some of the world’s largest cloud and software companies, and a broad ecosystem of startups and suppliers. Teams here expect well-engineered, secure systems, not fragile hacks.',
      'Healthcare, professional services and home services round out demand. Long, dark winters bring seasonal spikes in HVAC and roofing calls that AI phone answering handles smoothly.',
    ],
    industries: ['medical-clinics', 'home-services', 'hvac', 'real-estate', 'law-firms', 'fitness-gyms'],
    areas: ['Downtown', 'South Lake Union', 'Capitol Hill', 'Bellevue', 'Redmond', 'Kirkland', 'Tacoma', 'Everett'],
    services: ['ai-chatbot-developer', 'workflow-automation', 'ai-customer-support', 'ai-receptionist', 'api-integration', 'crm-automation'],
    servicesLead: 'Seattle clients value engineering quality, these are our most common builds.',
    compliance: {
      title: 'Washington health data and recording rules',
      text: 'Washington’s My Health My Data Act regulates consumer health data broadly, and the state requires all-party consent to record calls. We minimize sensitive data collection, document data flows and configure recording disclosures for Washington deployments.',
    },
    faqs: [
      { q: 'How does My Health My Data affect AI chatbots?', a: 'If a chatbot collects consumer health data (even outside HIPAA), Washington’s law may require consent and specific disclosures. We design flows that avoid unnecessary health data and support consent where needed; confirm with counsel.' },
      { q: 'Do you deploy on AWS or Azure?', a: 'Yes, whichever cloud your team prefers.' },
    ],
    schemaPlace: city('Seattle', 'Washington'),
    nearby: ['san-francisco', 'denver'],
  },

  phoenix: {
    description: 'AI automation agency serving Phoenix: AI receptionists, voice agents, GoHighLevel and CRM automation for HVAC, solar, roofing, real estate and home-service businesses in the Valley.',
    lead: 'AI receptionists, voice agents and GoHighLevel automation for the Valley’s HVAC, solar, roofing, real-estate and home-service businesses.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, GoHighLevel and CRM automation for Phoenix-area businesses</strong>, helping HVAC, solar, roofing and real-estate teams across the Valley answer every call and book every job, even in peak summer.',
    tzShort: 'Mountain Standard Time',
    languages: 'EN · ES',
    pills: ['Scottsdale', 'Tempe', 'Mesa', 'Chandler'],
    marketTitle: 'Extreme heat, extreme call volume',
    market: [
      'In the Valley, a broken AC in July is an emergency, and HVAC companies can receive more calls in a single afternoon than their dispatch team can answer. AI phone answering captures every one, flags emergencies and books the rest.',
      'Abundant sunshine and rapid population growth also fuel solar, roofing, pool and real-estate businesses, all of which rely on fast lead response and persistent follow-up.',
    ],
    industries: ['hvac', 'solar', 'roofing', 'real-estate', 'home-services', 'med-spas'],
    areas: ['Phoenix', 'Scottsdale', 'Tempe', 'Mesa', 'Chandler', 'Gilbert', 'Glendale', 'Peoria'],
    services: ['ai-phone-answering', 'ai-receptionist', 'ai-calling-bots', 'gohighlevel-automation', 'ai-follow-up-system', 'lead-generation-funnel'],
    servicesLead: 'For Valley service businesses, phone coverage and follow-up are the biggest revenue levers.',
    compliance: {
      title: 'Compliant calling, texting and recording',
      text: `Arizona observes Mountain Standard Time year-round, so we schedule calling windows carefully. ${TCPA} SMS requires A2P 10DLC registration.`,
    },
    faqs: [
      { q: 'Does Phoenix change clocks for daylight saving?', a: 'No, most of Arizona stays on Mountain Standard Time all year. We configure calling hours and reminders accordingly so nothing goes out at the wrong time.' },
      { q: 'Can AI qualify solar leads?', a: 'Yes, homeownership, roof type, average bill and timeline captured automatically, with consultations booked for qualified homeowners.' },
    ],
    schemaPlace: city('Phoenix', 'Arizona'),
    nearby: ['denver', 'los-angeles', 'san-diego'],
  },

  denver: {
    description: 'AI automation agency serving Denver: AI voice agents, chatbots, workflow and CRM automation for home services, healthcare, real estate, fitness and tech businesses along the Front Range.',
    lead: 'Voice agents, chatbots and workflow automation for Denver and Front Range businesses, home services, healthcare, real estate, fitness and tech.',
    answer: 'Voxil AI builds <strong>AI voice agents, chatbots, workflow and CRM automation for Denver businesses</strong> across the Front Range, from Cherry Creek practices to Boulder startups and Aurora contractors, with Colorado’s emerging AI rules in mind.',
    tzShort: 'Mountain Time',
    languages: 'EN · ES',
    pills: ['LoDo', 'Cherry Creek', 'Boulder', 'Aurora'],
    marketTitle: 'An active, growing, outdoorsy market',
    market: [
      'Denver’s growth has created strong demand for home services, roofing (hail season is real), real estate and healthcare, businesses where after-hours calls and slow follow-up quietly cost revenue.',
      'The Front Range also has a thriving fitness and wellness scene and a growing tech sector. We build membership follow-up and booking automation for gyms and studios, and custom AI tooling for tech teams.',
    ],
    industries: ['roofing', 'home-services', 'fitness-gyms', 'medical-clinics', 'real-estate', 'solar'],
    areas: ['Downtown / LoDo', 'Cherry Creek', 'Highlands', 'Aurora', 'Lakewood', 'Littleton', 'Boulder', 'Colorado Springs'],
    services: ['ai-voice-agents', 'ai-phone-answering', 'ai-follow-up-system', 'workflow-automation', 'marketing-automation', 'crm-automation'],
    servicesLead: 'Denver service businesses see the fastest returns from voice and follow-up automation.',
    compliance: {
      title: 'Colorado’s AI and privacy rules',
      text: `Colorado has passed one of the first comprehensive state AI laws, aimed at "high-risk" AI used in consequential decisions, alongside the Colorado Privacy Act. Customer-service and booking agents are typically lower-risk, but we document how systems make decisions and keep humans in the loop. ${TCPA}`,
    },
    faqs: [
      { q: 'Does the Colorado AI Act affect chatbots?', a: 'The law focuses on high-risk AI systems that make consequential decisions (e.g. lending, employment, housing). Typical support and booking bots are less likely to be in scope, but disclosures and documentation are still good practice. Confirm with counsel.' },
      { q: 'Can AI help roofing companies during hail season?', a: 'Yes, it answers surge call volume, qualifies damage and insurance details, and books inspections automatically.' },
    ],
    schemaPlace: city('Denver', 'Colorado'),
    nearby: ['phoenix', 'dallas', 'chicago'],
  },

  // -------------------------------------------------------- INTERNATIONAL
  'united-kingdom': {
    shortName: 'the UK',
    title: 'AI Automation Agency UK | Voice Agents & Chatbots | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">the United Kingdom</span>',
    description: 'AI automation for UK businesses: AI voice agents, receptionists, WhatsApp chatbots, GoHighLevel and CRM automation, built for UK GDPR and PECR. Serving London, Manchester, Birmingham and beyond.',
    lead: 'AI receptionists, voice agents, WhatsApp bots and CRM automation for UK businesses, UK GDPR- and PECR-aware, with British voices and working sessions in UK hours.',
    answer: 'Voxil AI builds <strong>AI voice agents, receptionists, WhatsApp chatbots and CRM automation for UK businesses</strong>, in London, Manchester, Birmingham, Leeds, Glasgow and across the country, designed around UK GDPR, the Data Protection Act 2018 and PECR.',
    tzShort: 'UK time (GMT/BST)',
    languages: 'EN-GB',
    pills: ['London', 'Manchester', 'Birmingham', 'Glasgow'],
    marketTitle: 'WhatsApp-first customers and strict marketing rules',
    market: [
      'UK customers use WhatsApp heavily for everyday communication, and increasingly expect businesses to be reachable there. Pairing WhatsApp automation with an AI phone agent covers the two channels most inquiries arrive on.',
      'UK rules on marketing calls and texts (PECR) and data protection (UK GDPR) are stricter than in the US. We design consent, lawful basis and data retention in from the start, and use British English voices and spellings so the experience feels local.',
    ],
    industries: ['home-services', 'law-firms', 'real-estate', 'med-spas', 'fitness-gyms', 'medical-clinics'],
    areas: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool', 'Bristol', 'Glasgow', 'Edinburgh'],
    services: ['ai-receptionist', 'whatsapp-automation', 'ai-voice-agents', 'ai-chatbots', 'gohighlevel-automation', 'crm-automation'],
    servicesLead: 'UK clients most often start with phone coverage and WhatsApp automation.',
    compliance: {
      title: 'UK GDPR, DPA 2018 and PECR',
      text: 'We document lawful basis, data processing and retention under UK GDPR and the Data Protection Act 2018, respect PECR for marketing texts and emails, and screen outbound calling against the Telephone Preference Service (TPS) where relevant.',
    },
    faqs: [
      { q: 'Do your AI voices sound British?', a: 'Yes, we use natural British English voices and tune pronunciation for UK place names, postcodes and spellings.' },
      { q: 'Can we use AI for outbound calls in the UK?', a: 'Automated marketing calls in the UK generally require prior consent under PECR, and live marketing calls must respect TPS. We focus outbound AI on consented contacts, reminders and service calls.' },
    ],
    schemaPlace: country('United Kingdom'),
    nearby: ['dubai-uae', 'canada', 'australia'],
  },

  'dubai-uae': {
    shortName: 'Dubai & the UAE',
    title: 'AI Automation Agency Dubai & UAE | Arabic AI | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Dubai & the UAE</span>',
    description: 'AI automation for Dubai and UAE businesses: Arabic and English AI voice agents, WhatsApp chatbots, CRM and GoHighLevel automation for real estate, clinics, hospitality and retail.',
    lead: 'Arabic and English voice agents, WhatsApp chatbots and CRM automation for real-estate, healthcare, hospitality and retail businesses in Dubai, Abu Dhabi and across the Emirates.',
    answer: 'Voxil AI builds <strong>Arabic-English AI voice agents, WhatsApp chatbots and CRM automation for businesses in Dubai and the UAE</strong>. Systems handle inquiries around the clock on WhatsApp and phone, qualify leads and book viewings or appointments, built with the UAE PDPL in mind.',
    tzShort: 'Gulf Standard Time',
    languages: 'EN · AR · HI · UR',
    pills: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ras Al Khaimah'],
    marketTitle: 'WhatsApp is the storefront',
    market: [
      'In the UAE, customers expect to message businesses on WhatsApp and get an answer quickly, often in Arabic, English, Hindi or Urdu. Real-estate brokerages, clinics, salons and hospitality businesses receive inquiries at every hour from local and international customers.',
      'AI agents answer instantly in the customer’s language, qualify buyers and tenants, share listings or services, and book viewings and appointments, all synced to your CRM so your team follows up on qualified leads only.',
    ],
    industries: ['real-estate', 'medical-clinics', 'med-spas', 'salons-beauty', 'fitness-gyms', 'home-services'],
    areas: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain', 'DIFC & Business Bay'],
    services: ['whatsapp-automation', 'ai-voice-agents', 'ai-chatbots', 'ai-appointment-booking', 'crm-setup', 'gohighlevel-ai'],
    servicesLead: 'For UAE businesses, WhatsApp and multilingual voice automation deliver the fastest wins.',
    compliance: {
      title: 'UAE PDPL and free-zone data rules',
      text: 'We design for the UAE Personal Data Protection Law (Federal Decree-Law No. 45 of 2021) and, where relevant, the separate data-protection regimes of the DIFC and ADGM free zones, documenting consent, data processing and cross-border transfers.',
    },
    faqs: [
      { q: 'Can the AI speak Arabic?', a: 'Yes. Our agents understand and respond in Arabic and English, and can handle Hindi and Urdu for many UAE customers. We test dialect handling during the pilot.' },
      { q: 'Do you work in UAE business hours?', a: 'Yes, we schedule calls and working sessions within Gulf Standard Time, and the UAE’s Monday-to-Friday working week.' },
    ],
    schemaPlace: country('United Arab Emirates'),
    nearby: ['pakistan', 'united-kingdom'],
  },

  canada: {
    shortName: 'Canada',
    title: 'AI Automation Agency Canada | AI Voice Agents | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Canada</span>',
    description: 'AI automation for Canadian businesses: English and French AI voice agents, receptionists, chatbots and CRM automation, built for PIPEDA, Quebec Law 25 and CASL. Toronto, Vancouver, Montreal and more.',
    lead: 'English and French voice agents, AI receptionists, chatbots and CRM automation for Canadian businesses, designed around PIPEDA, Quebec’s Law 25 and CASL.',
    answer: 'Voxil AI builds <strong>AI voice agents, receptionists, chatbots and CRM automation for Canadian businesses</strong> in Toronto, Vancouver, Montreal, Calgary, Ottawa and beyond, bilingual English-French where needed and compliant with Canada’s privacy and anti-spam laws.',
    tzShort: 'ET · CT · MT · PT',
    languages: 'EN · FR',
    pills: ['Toronto', 'Vancouver', 'Montreal', 'Calgary'],
    marketTitle: 'Bilingual service and some of the world’s strictest anti-spam rules',
    market: [
      'Canadian businesses often need to serve customers in English and French, and across six time zones. AI agents make bilingual, around-the-clock coverage realistic for small and mid-sized teams.',
      'Canada’s Anti-Spam Legislation (CASL) is stricter than US email rules, consent requirements are explicit and penalties can be significant, so follow-up and marketing automation must be built carefully. We design consent capture and records into every system.',
    ],
    industries: ['real-estate', 'home-services', 'medical-clinics', 'law-firms', 'insurance', 'hvac'],
    areas: ['Toronto & GTA', 'Vancouver', 'Montreal', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Halifax'],
    services: ['ai-receptionist', 'ai-voice-agents', 'ai-chatbots', 'email-sms-marketing', 'crm-automation', 'ai-follow-up-system'],
    servicesLead: 'Canadian clients often start with bilingual phone coverage and compliant follow-up.',
    compliance: {
      title: 'PIPEDA, Law 25 and CASL',
      text: 'We design for PIPEDA and provincial privacy laws including Quebec’s Law 25, build CASL-compliant consent and unsubscribe handling into email and SMS, and respect CRTC telemarketing rules and the National Do Not Call List for outbound calls.',
    },
    faqs: [
      { q: 'Can the AI speak French?', a: 'Yes, including Canadian French. Agents detect language automatically and respond in English or French.' },
      { q: 'Is SMS follow-up allowed under CASL?', a: 'Yes, with valid express or implied consent, clear identification and an easy unsubscribe. We build consent tracking so you can prove it.' },
    ],
    schemaPlace: country('Canada'),
    nearby: ['united-kingdom', 'australia', 'seattle'],
  },

  australia: {
    shortName: 'Australia',
    title: 'AI Automation Agency Australia | AI Receptionists | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Australia</span>',
    description: 'AI automation for Australian businesses: AI receptionists, voice agents, chatbots, GoHighLevel and CRM automation built for the Privacy Act, Spam Act and Do Not Call Register. Sydney, Melbourne, Brisbane, Perth.',
    lead: 'AI receptionists, voice agents, chatbots and GoHighLevel automation for Australian tradies, clinics, real-estate agencies and service businesses, with Australian voices and compliance built in.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for Australian businesses</strong> in Sydney, Melbourne, Brisbane, Perth, Adelaide and regional centers, with Australian-accented voices and systems designed around the Privacy Act, Spam Act and Do Not Call Register.',
    tzShort: 'AEST · ACST · AWST',
    languages: 'EN-AU',
    pills: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
    marketTitle: 'Tradies on the tools, calls going unanswered',
    market: [
      'Australia’s trades and home-service businesses are often owner-operated, the person answering the phone is also on the roof, under the sink or behind the wheel. AI receptionists and missed-call text-back make sure every inquiry is captured and booked.',
      'Real-estate agencies, allied-health clinics and fitness studios face the same pressure. We use Australian English voices and spelling, and schedule sessions across AEST, ACST and AWST with async updates in between.',
    ],
    industries: ['home-services', 'real-estate', 'medical-clinics', 'fitness-gyms', 'solar', 'roofing'],
    areas: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle'],
    services: ['ai-receptionist', 'ai-phone-answering', 'gohighlevel-automation', 'ai-appointment-booking', 'ai-follow-up-system', 'website-design'],
    servicesLead: 'Australian service businesses get the quickest wins from phone coverage and booking automation.',
    compliance: {
      title: 'Privacy Act, Spam Act and Do Not Call Register',
      text: 'We design for the Privacy Act 1988 and Australian Privacy Principles, build Spam Act 2003 consent and unsubscribe handling into email and SMS, and respect the Do Not Call Register for telemarketing calls.',
    },
    faqs: [
      { q: 'Do your voices sound Australian?', a: 'Yes, we use natural Australian English voices and tune for local suburbs, spelling and phrasing.' },
      { q: 'Can you work across Australian time zones?', a: 'Yes. We schedule live sessions in overlapping hours and keep work moving with async updates and recorded demos.' },
    ],
    schemaPlace: country('Australia'),
    nearby: ['united-kingdom', 'canada', 'pakistan'],
  },

  pakistan: {
    shortName: 'Pakistan',
    title: 'AI Automation Agency Pakistan | Urdu AI Chatbots | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Pakistan</span>',
    description: 'AI automation for Pakistani businesses: Urdu and English WhatsApp chatbots, AI voice agents, CRM and workflow automation for real estate, education, healthcare, ecommerce and exporters in Karachi, Lahore and Islamabad.',
    lead: 'Urdu-English WhatsApp chatbots, voice agents and CRM automation for Pakistan’s real-estate, education, healthcare, ecommerce and export businesses.',
    answer: 'Voxil AI builds <strong>Urdu and English WhatsApp chatbots, AI voice agents and CRM automation for businesses in Pakistan</strong>, in Karachi, Lahore, Islamabad and beyond, so inquiries on WhatsApp and phone are answered instantly and every lead is tracked.',
    tzShort: 'Pakistan Standard Time',
    languages: 'UR · EN',
    pills: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi'],
    marketTitle: 'Business in Pakistan runs on WhatsApp',
    market: [
      'For most Pakistani businesses, WhatsApp is the main sales and support channel, real-estate projects, schools and academies, clinics, ecommerce stores and service providers all receive a flood of messages, often in Roman Urdu.',
      'AI chatbots that understand Urdu, Roman Urdu and English reply instantly, share prices and brochures, qualify buyers, book visits and hand hot leads to your sales team, with every conversation logged in a CRM instead of scattered across staff phones.',
    ],
    industries: ['real-estate', 'medical-clinics', 'salons-beauty', 'fitness-gyms', 'home-services', 'solar'],
    areas: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Sialkot'],
    services: ['whatsapp-automation', 'ai-chatbots', 'crm-setup', 'ai-voice-agents', 'workflow-automation', 'website-design'],
    servicesLead: 'Pakistani businesses usually start with WhatsApp automation and a proper CRM.',
    compliance: {
      title: 'Data handling and local payments',
      text: 'Pakistan’s dedicated data-protection law is still evolving, with the Prevention of Electronic Crimes Act (PECA) 2016 currently relevant. We follow international best practice for consent and data minimization, and can integrate local payment options such as JazzCash and Easypaisa where supported.',
    },
    faqs: [
      { q: 'Can the chatbot understand Roman Urdu?', a: 'Yes. Our assistants understand Urdu script, Roman Urdu and English, and reply in the customer’s preferred style.' },
      { q: 'Do you build for overseas Pakistanis buying property?', a: 'Yes, real-estate bots that answer in English or Urdu across time zones, share project details and book calls with your sales team.' },
    ],
    schemaPlace: country('Pakistan'),
    nearby: ['dubai-uae', 'united-kingdom'],
  },
  // ------------------------------------------------------------ UK & EUROPE
  london: {
    description: 'AI automation agency serving London: AI receptionists, voice agents, WhatsApp chatbots, GoHighLevel and CRM automation for professional services, property, clinics and hospitality. UK GDPR and PECR aware.',
    lead: 'AI receptionists, voice agents, WhatsApp bots and CRM automation for London firms that can’t afford to miss a call, a viewing request or a new client inquiry.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, WhatsApp chatbots and CRM automation for London businesses</strong>, from City law firms and West End clinics to estate and lettings agents across Greater London, designed around UK GDPR and PECR and live in two to four weeks.',
    tzShort: 'UK time (GMT/BST)',
    languages: 'EN-GB',
    pills: ['City of London', 'Canary Wharf', 'Shoreditch', 'Westminster'],
    marketTitle: 'London moves fast, and so do your competitors',
    market: [
      'London buyers compare several firms at once. A prospective client emails three law firms, a tenant messages four letting agents, a patient calls two private clinics. The business that replies first, clearly and at any hour, usually wins the work.',
      'We see the strongest returns in professional services, estate and lettings agencies, private healthcare and aesthetics, and hospitality. AI answers every call and WhatsApp message instantly, qualifies the inquiry, books into the right diary and logs everything in your CRM, so your team spends its time with serious clients.',
    ],
    industries: ['law-firms', 'real-estate', 'medical-clinics', 'med-spas', 'fitness-gyms', 'home-services'],
    areas: ['City of London', 'Canary Wharf', 'Shoreditch', 'Westminster', 'Camden', 'Kensington & Chelsea', 'Croydon', 'Richmond'],
    services: ['ai-receptionist', 'whatsapp-automation', 'ai-voice-agents', 'ai-chatbots', 'crm-automation', 'ai-follow-up-system'],
    servicesLead: 'For London firms handling high inquiry volumes, these systems pay back fastest.',
    compliance: {
      title: 'UK GDPR, PECR and call recording',
      text: 'We document lawful basis, retention and processors under UK GDPR and the Data Protection Act 2018, follow PECR for marketing texts and emails, screen marketing calls against the Telephone Preference Service, and configure clear call-recording and AI disclosures.',
    },
    faqs: [
      { q: 'Can an AI receptionist handle a busy London office?', a: 'Yes. It answers unlimited calls at once, so lunchtime peaks and evening inquiries never go to voicemail. Urgent calls transfer to your team and everything else is booked or summarized by text or email.' },
      { q: 'Do you work with London estate and letting agents?', a: 'Yes. We build agents that answer listing questions, qualify applicants and book viewings into your diary, integrated with GoHighLevel, HubSpot or your property CRM where an API is available.' },
    ],
    schemaPlace: city('London', 'England'),
    nearby: ['united-kingdom', 'manchester', 'europe'],
  },

  manchester: {
    description: 'AI automation agency serving Manchester and the North West: AI receptionists, voice agents, chatbots, GoHighLevel and workflow automation for home services, professional services, clinics and digital businesses.',
    lead: 'AI receptionists, voice agents and workflow automation for Manchester businesses, from home-service trades to professional firms and fast-growing digital companies.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and workflow automation for Manchester and North West businesses</strong>, answering every call and inquiry instantly, booking jobs and appointments, and keeping your CRM up to date, all designed around UK GDPR and PECR.',
    tzShort: 'UK time (GMT/BST)',
    languages: 'EN-GB',
    pills: ['City Centre', 'Salford', 'Trafford', 'Stockport'],
    marketTitle: 'A growing northern economy with busy phones',
    market: [
      'Greater Manchester has one of the UK’s fastest-growing business communities, with a strong digital and media sector around Salford and a large base of professional services, trades and healthcare providers across the region.',
      'For trades and home-service companies, the problem is simple: calls arrive while the team is on site. AI phone answering and missed-call text-back capture those jobs. For professional firms and clinics, AI intake and booking free up staff time without adding headcount.',
    ],
    industries: ['home-services', 'law-firms', 'medical-clinics', 'real-estate', 'fitness-gyms', 'roofing'],
    areas: ['Manchester City Centre', 'Salford', 'Trafford', 'Stockport', 'Bolton', 'Oldham', 'Altrincham', 'Wigan'],
    services: ['ai-phone-answering', 'ai-receptionist', 'workflow-automation', 'gohighlevel-automation', 'ai-follow-up-system', 'crm-setup'],
    servicesLead: 'Manchester businesses usually start with phone coverage and follow-up.',
    compliance: {
      title: 'UK GDPR, PECR and TPS',
      text: 'We design for UK GDPR and the Data Protection Act 2018, follow PECR for marketing messages, respect the Telephone Preference Service for marketing calls, and configure recording and AI disclosures on every voice agent.',
    },
    faqs: [
      { q: 'Can AI answer calls for a Manchester trades business?', a: 'Yes. An AI receptionist answers while you work, captures the job details and postcode, books the visit and texts you a summary, and flags emergencies so you can call straight back.' },
      { q: 'Do your voice agents sound British?', a: 'Yes. We use natural British English voices and tune pronunciation for local place names.' },
    ],
    schemaPlace: city('Manchester', 'England'),
    nearby: ['united-kingdom', 'london', 'ireland'],
  },

  europe: {
    shortName: 'Europe',
    title: 'AI Automation Agency Europe | GDPR-Ready AI | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Europe</span>',
    description: 'GDPR-ready AI automation for European businesses: multilingual AI voice agents, receptionists, WhatsApp chatbots and CRM automation, designed around GDPR and the EU AI Act. Serving Ireland, the Netherlands, Germany and across the EU.',
    lead: 'Multilingual AI voice agents, receptionists, WhatsApp chatbots and CRM automation for European businesses, designed around GDPR and the EU AI Act from day one.',
    answer: 'Voxil AI builds <strong>GDPR-ready AI voice agents, chatbots and automation for businesses across the European Union</strong>. Agents speak your customers’ languages, disclose that they are AI as the EU AI Act requires, keep data handling documented, and connect to your CRM and calendar.',
    tzShort: 'CET · GMT · EET',
    languages: 'EN · DE · FR · NL · ES',
    pills: ['GDPR-ready', 'EU AI Act aware', 'Multilingual', 'WhatsApp-first'],
    marketTitle: 'Multilingual customers and the world’s strictest data rules',
    market: [
      'European businesses serve customers across languages and borders, often on WhatsApp rather than phone or email. An AI agent that answers instantly in German, Dutch, French, Spanish or English removes the need to staff every language on every shift.',
      'Europe also has the strictest rules for data and AI. That is an advantage when your systems are built properly: documented processing, data minimization, clear AI disclosure and human escalation. We design all of that in from the start, so compliance is a feature your customers can trust, not a risk.',
    ],
    industries: ['medical-clinics', 'real-estate', 'law-firms', 'home-services', 'med-spas', 'fitness-gyms'],
    areas: ['Ireland', 'Netherlands', 'Germany', 'France', 'Spain', 'Belgium', 'Nordics', 'Portugal'],
    services: ['ai-voice-agents', 'whatsapp-automation', 'ai-chatbots', 'ai-customer-support', 'crm-automation', 'ai-automation-consultant'],
    servicesLead: 'European businesses most often start with multilingual chat, WhatsApp and phone coverage.',
    compliance: {
      title: 'GDPR and the EU AI Act',
      text: 'We document lawful basis, processors, retention and cross-border transfers under the GDPR, and follow the EU AI Act’s transparency rules, which apply from August 2026 and require that people are told when they are interacting with an AI system. Marketing calls and messages also follow each country’s ePrivacy rules.',
    },
    faqs: [
      { q: 'Are AI voice agents GDPR compliant?', a: 'They can be, when designed properly: a documented lawful basis, data processing agreements with providers, data minimization, sensible retention and clear disclosures. We scope all of this with you and document it for your records.' },
      { q: 'What does the EU AI Act mean for chatbots and voice agents?', a: 'Customer-facing chatbots and voice agents generally fall under the Act’s transparency obligations: people must be informed they are talking to an AI. We build that disclosure into every European deployment. Confirm your specific obligations with counsel.' },
    ],
    schemaPlace: { '@type': 'Place', name: 'European Union' },
    nearby: ['ireland', 'netherlands', 'germany', 'united-kingdom'],
  },

  ireland: {
    shortName: 'Ireland',
    title: 'AI Automation Agency Ireland | AI Voice Agents | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Ireland</span>',
    description: 'AI automation for Irish businesses: AI receptionists, voice agents, WhatsApp chatbots, GoHighLevel and CRM automation, GDPR-ready and serving Dublin, Cork, Galway and Limerick.',
    lead: 'AI receptionists, voice agents, WhatsApp chatbots and CRM automation for Irish businesses, GDPR-ready and built for customers who expect a fast, friendly reply.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for businesses in Ireland</strong>, from Dublin clinics and law firms to trades and property businesses in Cork, Galway and Limerick, with GDPR-ready data handling and natural English voices.',
    tzShort: 'Irish time (GMT/IST)',
    languages: 'EN',
    pills: ['Dublin', 'Cork', 'Galway', 'Limerick'],
    marketTitle: 'A small market where reputation travels fast',
    market: [
      'In Ireland, word of mouth matters. A missed call or a slow reply isn’t just one lost customer; it’s a story told to friends. AI receptionists and instant WhatsApp replies make sure every inquiry gets a prompt, courteous answer, even out of hours.',
      'Dublin is also the European base for many global tech companies, and Irish businesses are used to high standards on data protection. We design every system with GDPR documentation, data minimization and clear AI disclosure.',
    ],
    industries: ['medical-clinics', 'law-firms', 'home-services', 'real-estate', 'med-spas', 'fitness-gyms'],
    areas: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kilkenny', 'Drogheda', 'Swords'],
    services: ['ai-receptionist', 'whatsapp-automation', 'ai-voice-agents', 'ai-appointment-booking', 'crm-setup', 'gohighlevel-automation'],
    servicesLead: 'Irish businesses usually start with phone coverage and WhatsApp.',
    compliance: {
      title: 'GDPR, Irish ePrivacy rules and the EU AI Act',
      text: 'We design for the GDPR and Ireland’s Data Protection Act 2018, follow Irish ePrivacy rules for marketing calls, texts and emails, and include the AI disclosure the EU AI Act requires for customer-facing agents.',
    },
    faqs: [
      { q: 'Do your voice agents understand Irish accents?', a: 'Modern speech recognition handles Irish English well. We test with real callers during the pilot and tune vocabulary for local names and places.' },
      { q: 'Can the AI book appointments for Irish clinics?', a: 'Yes, if your practice software offers an API or integration. Otherwise the agent captures requests for one-click confirmation by staff.' },
    ],
    schemaPlace: country('Ireland'),
    nearby: ['united-kingdom', 'europe', 'london'],
  },

  netherlands: {
    shortName: 'the Netherlands',
    title: 'AI Automation Agency Netherlands | Dutch AI | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">the Netherlands</span>',
    description: 'AI automation for Dutch businesses: Dutch and English AI voice agents, WhatsApp chatbots, receptionists and CRM automation, GDPR-ready. Serving Amsterdam, Rotterdam, The Hague, Utrecht and Eindhoven.',
    lead: 'Dutch and English voice agents, WhatsApp chatbots and CRM automation for businesses in the Netherlands, GDPR-ready and built for WhatsApp-first customers.',
    answer: 'Voxil AI builds <strong>Dutch and English AI voice agents, WhatsApp chatbots and CRM automation for businesses in the Netherlands</strong>. Agents reply instantly on WhatsApp and phone, qualify inquiries, book appointments and connect to your CRM, with GDPR-ready data handling.',
    tzShort: 'Central European Time',
    languages: 'NL · EN',
    pills: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
    marketTitle: 'WhatsApp-first customers, bilingual by default',
    market: [
      'Dutch customers use WhatsApp for almost everything, including contacting businesses, and many switch comfortably between Dutch and English. An AI agent that answers in either language, on WhatsApp and phone, meets them where they already are.',
      'The Netherlands also has an international business community around Amsterdam, Rotterdam and Eindhoven. We build agents for clinics, property businesses, service companies and B2B teams that need fast, multilingual responses and clean CRM data.',
    ],
    industries: ['real-estate', 'medical-clinics', 'home-services', 'fitness-gyms', 'salons-beauty', 'law-firms'],
    areas: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Haarlem', 'Groningen', 'Leiden'],
    services: ['whatsapp-automation', 'ai-voice-agents', 'ai-chatbots', 'ai-appointment-booking', 'crm-automation', 'ai-customer-support'],
    servicesLead: 'Dutch businesses almost always start with WhatsApp automation.',
    compliance: {
      title: 'GDPR, opt-in telemarketing and the EU AI Act',
      text: 'We design for the GDPR and the Dutch data protection authority’s guidance. Since 2021 the Netherlands requires opt-in consent for telemarketing calls to consumers, so outbound AI calls only go to people who agreed to be contacted, and every agent discloses that it is AI as the EU AI Act requires.',
    },
    faqs: [
      { q: 'Can the AI speak Dutch?', a: 'Yes. Our agents understand and reply in Dutch and English and can switch mid-conversation. We test Dutch voices and phrasing during the pilot.' },
      { q: 'Can AI make outbound calls in the Netherlands?', a: 'Only to people who have given prior consent, because Dutch rules require opt-in for telemarketing to consumers. Inbound answering, reminders and follow-up to people who asked to be contacted are the usual starting points.' },
    ],
    schemaPlace: country('Netherlands'),
    nearby: ['europe', 'germany', 'ireland'],
  },

  germany: {
    shortName: 'Germany',
    title: 'AI Automation Agency Germany | German AI Agents | Voxil AI',
    h1: 'AI automation agency serving <span class="text-gradient-teal">Germany</span>',
    description: 'GDPR-ready AI automation for German businesses: German and English AI voice agents, chatbots, receptionists and CRM automation built for strict data protection. Serving Berlin, Munich, Hamburg, Frankfurt and Cologne.',
    lead: 'German and English AI voice agents, chatbots and CRM automation for businesses in Germany, built for strict data protection and clear consent from the start.',
    answer: 'Voxil AI builds <strong>German and English AI voice agents, chatbots and CRM automation for businesses in Germany</strong>. Systems follow GDPR and German consent rules for calls and recording, disclose that they are AI, and connect to your CRM and calendar.',
    tzShort: 'Central European Time',
    languages: 'DE · EN',
    pills: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
    marketTitle: 'High expectations for quality and data protection',
    market: [
      'German customers expect precise, reliable service and take data protection seriously. AI that answers accurately in German, knows exactly what it may and may not do, and hands over cleanly to a person earns trust rather than eroding it.',
      'Practices, trades, property businesses and B2B companies across Germany face growing inquiry volumes and a shortage of skilled staff. AI receptionists, booking agents and CRM automation absorb routine work so your team can focus on customers who need a person.',
    ],
    industries: ['medical-clinics', 'home-services', 'real-estate', 'law-firms', 'insurance', 'hvac'],
    areas: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Düsseldorf', 'Stuttgart', 'Leipzig'],
    services: ['ai-voice-agents', 'ai-receptionist', 'ai-chatbots', 'ai-customer-support', 'crm-automation', 'workflow-automation'],
    servicesLead: 'German businesses usually start with phone coverage and support automation.',
    compliance: {
      title: 'GDPR, German consent rules and the EU AI Act',
      text: 'We design for the GDPR and Germany’s Federal Data Protection Act (BDSG). German law requires prior consent for advertising calls to consumers and makes recording a conversation without consent a criminal offense, so our agents only call consented contacts and ask before recording. Every agent discloses that it is AI, as the EU AI Act requires.',
    },
    faqs: [
      { q: 'Can the AI speak German naturally?', a: 'Yes. We use high-quality German voices and test formal and informal address (Sie and du) to match your brand during the pilot.' },
      { q: 'Can calls be recorded in Germany?', a: 'Only with consent. We configure agents to ask permission before recording, or to keep transcripts only, depending on your needs and your data protection officer’s advice.' },
    ],
    schemaPlace: country('Germany'),
    nearby: ['europe', 'netherlands', 'ireland'],
  },

  // ------------------------------------------------ CANADA & AUSTRALIA CITIES
  toronto: {
    description: 'AI automation agency serving Toronto and the GTA: AI receptionists, voice agents, chatbots, GoHighLevel and CRM automation for real estate, clinics, legal, finance and home services. PIPEDA and CASL aware.',
    lead: 'AI receptionists, voice agents and CRM automation for Toronto and GTA businesses, from Bay Street firms to clinics, brokerages and home-service companies.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for Toronto and GTA businesses</strong>, answering every call and inquiry instantly, booking appointments and following up automatically, designed around PIPEDA and CASL.',
    tzShort: 'Eastern Time',
    languages: 'EN · FR',
    pills: ['Downtown', 'Mississauga', 'Markham', 'Vaughan'],
    marketTitle: 'Canada’s biggest market, and its most competitive',
    market: [
      'Toronto is Canada’s financial and business center, with a huge concentration of real-estate brokerages, clinics, law firms and service businesses competing for the same customers. Speed of response is often the deciding factor.',
      'The GTA is also one of the most multicultural regions in the world. AI agents that answer in the caller’s language, around the clock, help businesses serve customers they would otherwise miss.',
    ],
    industries: ['real-estate', 'medical-clinics', 'law-firms', 'insurance', 'home-services', 'hvac'],
    areas: ['Downtown Toronto', 'North York', 'Scarborough', 'Etobicoke', 'Mississauga', 'Brampton', 'Markham', 'Vaughan'],
    services: ['ai-receptionist', 'ai-voice-agents', 'ai-sdr-system', 'ai-follow-up-system', 'crm-automation', 'email-sms-marketing'],
    servicesLead: 'GTA businesses see the fastest returns from phone coverage and compliant follow-up.',
    compliance: {
      title: 'PIPEDA, CASL and the National DNCL',
      text: 'We design for PIPEDA, build CASL-compliant consent and unsubscribe handling into every email and SMS flow, and respect CRTC telemarketing rules and the National Do Not Call List for outbound calls.',
    },
    faqs: [
      { q: 'Can AI help Toronto real-estate teams?', a: 'Yes. Agents respond to listing and portal inquiries instantly, qualify buyers and renters, and book showings into agents’ calendars, all logged in your CRM.' },
      { q: 'Is SMS follow-up allowed under CASL?', a: 'Yes, with valid consent, clear identification and an easy unsubscribe. We build consent tracking so you can prove it.' },
    ],
    schemaPlace: city('Toronto', 'Ontario'),
    nearby: ['canada', 'vancouver', 'new-york'],
  },

  vancouver: {
    description: 'AI automation agency serving Vancouver and the Lower Mainland: multilingual AI receptionists, voice agents, chatbots and CRM automation for real estate, clinics, tech and hospitality. BC PIPA and CASL aware.',
    lead: 'Multilingual AI receptionists, voice agents and CRM automation for Vancouver businesses, from real-estate teams and clinics to tech and hospitality.',
    answer: 'Voxil AI builds <strong>multilingual AI receptionists, voice agents, chatbots and CRM automation for Vancouver and Lower Mainland businesses</strong>, answering in English, Mandarin, Cantonese, Punjabi and more, and designed around BC privacy law and CASL.',
    tzShort: 'Pacific Time',
    languages: 'EN · ZH · PA',
    pills: ['Downtown', 'Burnaby', 'Richmond', 'Surrey'],
    marketTitle: 'A multilingual, high-value market',
    market: [
      'Metro Vancouver has one of the highest shares of multilingual households in Canada. Real-estate teams, clinics and service businesses regularly serve customers in Mandarin, Cantonese and Punjabi as well as English.',
      'AI agents that switch languages automatically and answer around the clock help businesses serve every customer consistently, without staffing every language on every shift.',
    ],
    industries: ['real-estate', 'medical-clinics', 'med-spas', 'home-services', 'law-firms', 'fitness-gyms'],
    areas: ['Downtown Vancouver', 'Burnaby', 'Richmond', 'Surrey', 'North Vancouver', 'Coquitlam', 'Langley', 'Delta'],
    services: ['ai-voice-agents', 'ai-receptionist', 'ai-chatbots', 'whatsapp-automation', 'ai-appointment-booking', 'crm-automation'],
    servicesLead: 'Vancouver clients most often start with multilingual voice and chat.',
    compliance: {
      title: 'BC PIPA, PIPEDA and CASL',
      text: 'British Columbia has its own private-sector privacy law (PIPA). We design for it alongside PIPEDA where it applies, build CASL-compliant consent into messaging, and respect the National Do Not Call List for outbound calls.',
    },
    faqs: [
      { q: 'Can the AI speak Mandarin or Punjabi?', a: 'Yes. Our agents can detect the caller’s language and respond in Mandarin, Cantonese, Punjabi and many others. We test language quality with real callers during the pilot.' },
      { q: 'Do you work in Pacific Time?', a: 'Yes. We schedule calls and working sessions inside Pacific Time business hours.' },
    ],
    schemaPlace: city('Vancouver', 'British Columbia'),
    nearby: ['canada', 'toronto', 'seattle'],
  },

  sydney: {
    description: 'AI automation agency serving Sydney: AI receptionists, voice agents, chatbots, GoHighLevel and CRM automation for trades, clinics, real estate and professional services. Built for the Privacy Act, Spam Act and DNCR.',
    lead: 'AI receptionists, voice agents and GoHighLevel automation for Sydney tradies, clinics, real-estate agencies and professional firms, with Australian voices and compliance built in.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for Sydney businesses</strong>, from Parramatta trades to North Shore clinics and CBD firms, with Australian-accented voices and systems designed around the Privacy Act, Spam Act and Do Not Call Register.',
    tzShort: 'AEST/AEDT',
    languages: 'EN-AU',
    pills: ['CBD', 'Parramatta', 'North Sydney', 'Chatswood'],
    marketTitle: 'Australia’s biggest city, and its busiest phones',
    market: [
      'Sydney tradies, clinics and agencies all face the same problem: the phone rings while everyone is busy. Callers who reach voicemail ring the next business on Google. AI answering captures every one of those calls and books the job.',
      'Real-estate agencies, allied-health clinics and professional firms across Greater Sydney also use AI to respond to inquiries instantly, qualify leads and keep follow-up consistent, without adding front-desk staff.',
    ],
    industries: ['home-services', 'real-estate', 'medical-clinics', 'roofing', 'solar', 'law-firms'],
    areas: ['Sydney CBD', 'Parramatta', 'North Sydney', 'Chatswood', 'Bondi', 'Penrith', 'Liverpool', 'Sutherland Shire'],
    services: ['ai-receptionist', 'ai-phone-answering', 'gohighlevel-automation', 'ai-appointment-booking', 'ai-follow-up-system', 'website-design'],
    servicesLead: 'Sydney service businesses get the quickest wins from phone coverage and booking.',
    compliance: {
      title: 'Privacy Act, Spam Act and Do Not Call Register',
      text: 'We design for the Privacy Act 1988 and Australian Privacy Principles, build Spam Act 2003 consent and unsubscribe handling into email and SMS, and respect the Do Not Call Register for telemarketing calls.',
    },
    faqs: [
      { q: 'Do your voices sound Australian?', a: 'Yes. We use natural Australian English voices and tune for local suburbs and phrasing.' },
      { q: 'Can AI book jobs for Sydney tradies?', a: 'Yes. It captures the job, suburb and urgency, books into your job software or calendar, and texts you a summary so you never miss work while on the tools.' },
    ],
    schemaPlace: city('Sydney', 'New South Wales'),
    nearby: ['australia', 'melbourne'],
  },

  melbourne: {
    description: 'AI automation agency serving Melbourne: AI receptionists, voice agents, chatbots, GoHighLevel and CRM automation for trades, healthcare, hospitality, education and real estate. Built for Australian privacy and spam rules.',
    lead: 'AI receptionists, voice agents and CRM automation for Melbourne businesses, from trades and clinics to hospitality, education and real estate.',
    answer: 'Voxil AI builds <strong>AI receptionists, voice agents, chatbots and CRM automation for Melbourne businesses</strong>, answering every call and inquiry instantly, booking appointments and jobs, and following up automatically, with Australian voices and compliance built in.',
    tzShort: 'AEST/AEDT',
    languages: 'EN-AU',
    pills: ['CBD', 'Southbank', 'Richmond', 'St Kilda'],
    marketTitle: 'A service economy that never stops',
    market: [
      'Melbourne’s hospitality, healthcare, education and trades sectors run on bookings and inquiries. When staff are with customers, calls go unanswered and those customers book elsewhere.',
      'AI receptionists and booking agents cover every call and message, day and night. Clinics fill cancellations from a waitlist, trades capture jobs while on site, and property teams respond to inquiries before the competition does.',
    ],
    industries: ['medical-clinics', 'home-services', 'fitness-gyms', 'real-estate', 'salons-beauty', 'hvac'],
    areas: ['Melbourne CBD', 'Southbank', 'Richmond', 'St Kilda', 'Docklands', 'Box Hill', 'Frankston', 'Geelong'],
    services: ['ai-receptionist', 'ai-appointment-booking', 'ai-phone-answering', 'gohighlevel-automation', 'email-sms-marketing', 'ai-chatbots'],
    servicesLead: 'Melbourne businesses usually start with booking and phone coverage.',
    compliance: {
      title: 'Privacy Act, Spam Act and Do Not Call Register',
      text: 'We design for the Privacy Act 1988 and Australian Privacy Principles, build Spam Act 2003 consent and unsubscribe handling into messaging, and respect the Do Not Call Register for telemarketing calls.',
    },
    faqs: [
      { q: 'Can AI fill last-minute cancellations?', a: 'Yes. When an appointment is canceled, the agent can offer the slot to your waitlist automatically by SMS and book the first person who accepts.' },
      { q: 'Do you work in Melbourne time?', a: 'Yes. We schedule live sessions in overlapping hours and keep work moving with async updates and recorded demos.' },
    ],
    schemaPlace: city('Melbourne', 'Victoria'),
    nearby: ['australia', 'sydney'],
  },
};
