// Portfolio demo funnels. Each entry becomes a complete, working demo funnel at
// /portfolio/<slug>/ and a card in the "Websites" tab of /portfolio/.
//
// These are DEMO designs for fictional businesses, built to show the kind of
// funnel Voxil AI delivers. Pages are labeled as demos, set to noindex and
// excluded from the sitemap, so they never compete with real pages in search.
// Keep brand names clearly fictional and avoid real company names.

export default [
  {
    slug: 'real-estate-funnel',
    industry: 'real-estate',
    label: 'Real Estate',
    card: { title: 'Luxury Real Estate Automation Funnel', desc: 'Home valuation funnel with AI lead capture, instant follow-up and a GoHighLevel pipeline for every seller inquiry.' },
    brand: 'Northgate Realty',
    accent: '#0f766e',
    accent2: '#14b8a6',
    icon: 'home',
    heroTitle: 'What is your home really worth in today’s market?',
    heroSub: 'Get a free, no-obligation valuation from a local agent within 24 hours, based on recent sales on your street.',
    offer: 'Free home valuation',
    questions: [
      { q: 'When are you thinking of selling?', options: ['Within 3 months', '3 to 6 months', '6 to 12 months', 'Just curious'] },
      { q: 'What type of property is it?', options: ['Single-family home', 'Condo or apartment', 'Townhouse', 'Land or other'] },
    ],
    benefits: [
      { icon: 'chart', title: 'Accurate local pricing', desc: 'Your valuation uses recent sales in your neighborhood, not a generic online estimate.' },
      { icon: 'calendar', title: 'Showings on autopilot', desc: 'Buyers book viewings online and get instant confirmations and reminders.' },
      { icon: 'bubble', title: 'Answers around the clock', desc: 'Our assistant replies to buyer and seller questions day and night.' },
    ],
    steps: ['Tell us about your property', 'Get your valuation within 24 hours', 'Meet your agent and plan your sale'],
    testimonials: [
      { quote: 'We had a valuation the same evening and three viewings booked by the weekend.', name: 'Sample client', role: 'Home seller' },
      { quote: 'Every question got an answer, even at 11pm. It made choosing an agent easy.', name: 'Sample client', role: 'First-time seller' },
    ],
    faqs: [
      { q: 'Is the valuation really free?', a: 'Yes. There is no cost and no obligation to list with us.' },
      { q: 'How accurate is it?', a: 'It is based on recent comparable sales near your home and reviewed by a local agent.' },
      { q: 'How soon will I hear back?', a: 'You get an instant confirmation and your valuation within 24 hours.' },
    ],
  },
  {
    slug: 'fitness-studio-funnel',
    industry: 'fitness-gyms',
    label: 'Fitness & Gym',
    card: { title: 'Fitness Studio Growth System', desc: 'Free trial funnel with AI follow-up, class booking and retention messages that turn trials into paying members.' },
    brand: 'Forge Fitness Studio',
    accent: '#c2410c',
    accent2: '#fb923c',
    icon: 'fire',
    heroTitle: 'Your first week at Forge is on us',
    heroSub: 'Claim a free 7-day pass with unlimited classes, a personal goal session and a coach who actually checks in.',
    offer: 'Free 7-day pass',
    questions: [
      { q: 'What is your main goal?', options: ['Lose weight', 'Build strength', 'Get fit and feel better', 'Train for an event'] },
      { q: 'When do you prefer to train?', options: ['Early morning', 'Lunchtime', 'Evenings', 'Weekends'] },
    ],
    benefits: [
      { icon: 'users', title: 'Coached small classes', desc: 'Every class is capped so coaches can correct your form and track progress.' },
      { icon: 'calendar', title: 'Book in seconds', desc: 'Reserve classes from your phone and get reminders so you never miss one.' },
      { icon: 'trending', title: 'Progress you can see', desc: 'Monthly check-ins keep you on track and motivated.' },
    ],
    steps: ['Claim your free pass', 'Book your goal session', 'Train with a coach for 7 days'],
    testimonials: [
      { quote: 'The reminders got me through the first week, and now I haven’t missed a class in two months.', name: 'Sample member', role: 'Member' },
      { quote: 'Booking a trial took less than a minute and a coach texted me right away.', name: 'Sample member', role: 'Trial member' },
    ],
    faqs: [
      { q: 'Do I need to be fit already?', a: 'No. Every class has options for all levels.' },
      { q: 'Is there a contract after the trial?', a: 'No. You can choose a membership or simply walk away.' },
      { q: 'What should I bring?', a: 'Comfortable clothes, trainers and a water bottle.' },
    ],
  },
  {
    slug: 'insurance-agency-funnel',
    industry: 'insurance',
    label: 'Insurance',
    card: { title: 'Insurance Agency Full Automation', desc: 'Quote funnel with an AI qualification step, pipeline automation, renewal reminders and compliant follow-up.' },
    brand: 'Clearpath Insurance Group',
    accent: '#1d4ed8',
    accent2: '#60a5fa',
    icon: 'shield',
    heroTitle: 'Compare quotes and save on your insurance in minutes',
    heroSub: 'Answer a few questions and a licensed agent will send you personalized quotes from multiple carriers.',
    offer: 'Free quote comparison',
    questions: [
      { q: 'What do you need to insure?', options: ['Auto', 'Home', 'Auto and home', 'Life'] },
      { q: 'When does your current policy renew?', options: ['Within 30 days', '1 to 3 months', 'Later this year', 'I don’t have one'] },
    ],
    benefits: [
      { icon: 'currency', title: 'Multiple carriers', desc: 'We compare options so you don’t have to call around.' },
      { icon: 'clock', title: 'Quotes the same day', desc: 'Most requests get personalized quotes within hours.' },
      { icon: 'shield', title: 'Licensed advice', desc: 'A licensed agent reviews every quote before it reaches you.' },
    ],
    steps: ['Answer a few quick questions', 'Get quotes from a licensed agent', 'Choose your coverage and save'],
    testimonials: [
      { quote: 'I had three quotes before lunch and switched the same week.', name: 'Sample client', role: 'Auto and home' },
      { quote: 'Simple questions, fast answers and a real person when I needed one.', name: 'Sample client', role: 'Renter' },
    ],
    faqs: [
      { q: 'Is the quote comparison free?', a: 'Yes. Comparing quotes costs nothing and there is no obligation to buy.' },
      { q: 'How long does it take?', a: 'About two minutes to answer the questions.' },
      { q: 'Will I be spammed with calls?', a: 'No. One agent follows up by your preferred method.' },
    ],
  },
  {
    slug: 'law-firm-funnel',
    industry: 'law-firms',
    label: 'Legal / Law Firm',
    card: { title: 'Law Firm Client Intake System', desc: 'Case evaluation funnel with AI intake, case-type qualification and consultation booking straight into the calendar.' },
    brand: 'Whitmore & Hale Law',
    accent: '#334155',
    accent2: '#94a3b8',
    icon: 'scale',
    heroTitle: 'Injured? Find out what your case may be worth',
    heroSub: 'Request a free, confidential case review. An attorney will contact you within one business day.',
    offer: 'Free case review',
    questions: [
      { q: 'What type of case is it?', options: ['Car accident', 'Workplace injury', 'Slip and fall', 'Something else'] },
      { q: 'When did it happen?', options: ['In the last month', '1 to 6 months ago', '6 to 12 months ago', 'Over a year ago'] },
    ],
    benefits: [
      { icon: 'scale', title: 'Experienced attorneys', desc: 'Your review is handled by an attorney, not a call center.' },
      { icon: 'shield', title: 'Confidential', desc: 'Everything you share is kept private.' },
      { icon: 'currency', title: 'No fee unless you win', desc: 'Illustrative offer shown for this demo funnel.' },
    ],
    steps: ['Tell us what happened', 'Get a confidential case review', 'Speak with an attorney'],
    testimonials: [
      { quote: 'I got a call back the next morning and finally understood my options.', name: 'Sample client', role: 'Personal injury' },
      { quote: 'The online form was simple and they booked my consultation right away.', name: 'Sample client', role: 'Workplace injury' },
    ],
    faqs: [
      { q: 'Is the case review really free?', a: 'Yes, there is no cost for the initial review.' },
      { q: 'Is my information confidential?', a: 'Yes. Only the legal team sees what you submit.' },
      { q: 'Is this page legal advice?', a: 'No. This is a demo page; a real firm would add its own disclaimers here.' },
    ],
  },
  {
    slug: 'home-services-funnel',
    industry: 'home-services',
    label: 'Home Services',
    card: { title: 'Home Services Lead Automation', desc: '60-second AI lead response, 24/7 job booking, quote follow-up and automatic review requests after every job.' },
    brand: 'BrightSpark Home Services',
    accent: '#b45309',
    accent2: '#fbbf24',
    icon: 'wrench',
    heroTitle: 'Plumbing and electrical help, booked in 60 seconds',
    heroSub: 'Tell us what’s wrong and pick a time. Licensed technicians, upfront pricing, and a text when we’re on the way.',
    offer: 'Book a service visit',
    questions: [
      { q: 'What do you need help with?', options: ['Plumbing', 'Electrical', 'Heating or cooling', 'General repair'] },
      { q: 'How urgent is it?', options: ['Emergency, today', 'This week', 'Next week', 'Just getting a quote'] },
    ],
    benefits: [
      { icon: 'clock', title: 'Same-day slots', desc: 'See real availability and book the first open time.' },
      { icon: 'currency', title: 'Upfront pricing', desc: 'Know the price before any work begins.' },
      { icon: 'star', title: 'Guaranteed work', desc: 'Illustrative guarantee shown for this demo funnel.' },
    ],
    steps: ['Describe the problem', 'Pick a time that suits you', 'Get a text when we’re on the way'],
    testimonials: [
      { quote: 'Booked online at 9pm and a technician was here the next morning.', name: 'Sample customer', role: 'Homeowner' },
      { quote: 'Clear price, on time, and a thank-you text afterward. Easy.', name: 'Sample customer', role: 'Homeowner' },
    ],
    faqs: [
      { q: 'Do you handle emergencies?', a: 'Yes. Choose "Emergency" and we prioritize your request.' },
      { q: 'Is there a call-out fee?', a: 'Pricing is shown before booking in a real version of this funnel.' },
      { q: 'Which areas do you cover?', a: 'A real business would list its service area here.' },
    ],
  },
  {
    slug: 'medical-clinic-funnel',
    industry: 'medical-clinics',
    label: 'Medical / Clinics',
    card: { title: 'Medical Clinic Patient Growth System', desc: 'New patient intake funnel with AI appointment booking, automated reminders and recall campaigns.' },
    brand: 'Riverside Family Clinic',
    accent: '#0e7490',
    accent2: '#67e8f9',
    icon: 'heart',
    heroTitle: 'New patients welcome, with appointments this week',
    heroSub: 'Book a visit with our family doctors online in under a minute. Most insurance accepted.',
    offer: 'Book a new patient visit',
    questions: [
      { q: 'What is the visit for?', options: ['Annual checkup', 'Illness or injury', 'Ongoing condition', 'Something else'] },
      { q: 'Who is the appointment for?', options: ['Me', 'My child', 'My partner', 'Another family member'] },
    ],
    benefits: [
      { icon: 'calendar', title: 'Online booking', desc: 'See open slots and book instantly, day or night.' },
      { icon: 'clipboard', title: 'Forms before you arrive', desc: 'Complete intake forms online and skip the clipboard.' },
      { icon: 'clock', title: 'Reminders that help', desc: 'Get reminders and reschedule by text if plans change.' },
    ],
    steps: ['Choose your visit type', 'Pick an appointment time', 'Complete forms online'],
    testimonials: [
      { quote: 'Booked on my phone in a minute and the reminder text saved me.', name: 'Sample patient', role: 'New patient' },
      { quote: 'Forms were done before I arrived, so the visit started on time.', name: 'Sample patient', role: 'Parent' },
    ],
    faqs: [
      { q: 'Do you accept my insurance?', a: 'A real clinic would list accepted plans here.' },
      { q: 'Can I book for my child?', a: 'Yes, choose "My child" when booking.' },
      { q: 'Is this for emergencies?', a: 'No. For emergencies, call your local emergency number.' },
    ],
  },
  {
    slug: 'med-spa-funnel',
    industry: 'med-spas',
    label: 'Med Spa',
    card: { title: 'Med Spa Consultation Funnel', desc: 'Consultation booking funnel with deposits, Instagram DM automation and rebooking reminders timed to each treatment.' },
    brand: 'Lumière Aesthetics',
    accent: '#9d174d',
    accent2: '#f9a8d4',
    icon: 'sparkles',
    heroTitle: 'Look refreshed, not overdone',
    heroSub: 'Book a complimentary consultation with a licensed injector and get a personalized treatment plan.',
    offer: 'Complimentary consultation',
    questions: [
      { q: 'Which treatment interests you?', options: ['Wrinkle relaxers', 'Dermal fillers', 'Skin rejuvenation', 'Not sure yet'] },
      { q: 'Have you had this treatment before?', options: ['Yes, regularly', 'Once or twice', 'Never', 'Prefer not to say'] },
    ],
    benefits: [
      { icon: 'sparkles', title: 'Natural results', desc: 'Plans designed around your features and goals.' },
      { icon: 'user', title: 'Licensed injectors', desc: 'Every treatment is performed by a licensed professional.' },
      { icon: 'calendar', title: 'Easy rebooking', desc: 'Friendly reminders when it’s time for your next visit.' },
    ],
    steps: ['Tell us your goals', 'Book your consultation', 'Get your personalized plan'],
    testimonials: [
      { quote: 'They answered my Instagram message in minutes and booked me the same day.', name: 'Sample client', role: 'Client' },
      { quote: 'The consultation was relaxed and the reminders are so helpful.', name: 'Sample client', role: 'Returning client' },
    ],
    faqs: [
      { q: 'Is the consultation free?', a: 'Yes, in this demo the consultation is complimentary.' },
      { q: 'Is a deposit required?', a: 'Some real clinics take a small deposit to secure the slot.' },
      { q: 'Who performs treatments?', a: 'Licensed professionals, as a real clinic would state here.' },
    ],
  },
  {
    slug: 'roofing-funnel',
    industry: 'roofing',
    label: 'Roofing',
    card: { title: 'Roofing Storm Lead Funnel', desc: 'Free inspection funnel with instant AI callbacks, insurance claim questions and inspection booking by territory.' },
    brand: 'Summit Peak Roofing',
    accent: '#7c2d12',
    accent2: '#f97316',
    icon: 'building',
    heroTitle: 'Storm damage? Get a free roof inspection this week',
    heroSub: 'Our inspectors document damage for your insurance claim and give you a clear repair or replacement plan.',
    offer: 'Free roof inspection',
    questions: [
      { q: 'What happened to your roof?', options: ['Hail damage', 'Wind damage', 'Leak', 'Just getting it checked'] },
      { q: 'Are you filing an insurance claim?', options: ['Yes', 'Not yet', 'Not sure', 'No'] },
    ],
    benefits: [
      { icon: 'search', title: 'Detailed inspection', desc: 'Photos and notes you can share with your insurer.' },
      { icon: 'clipboard', title: 'Claim support', desc: 'We explain what your insurer needs to see.' },
      { icon: 'calendar', title: 'Fast scheduling', desc: 'Pick an inspection time that suits you.' },
    ],
    steps: ['Tell us about the damage', 'Book your free inspection', 'Get your repair plan'],
    testimonials: [
      { quote: 'They called me back within a minute after the storm and inspected the next day.', name: 'Sample customer', role: 'Homeowner' },
      { quote: 'The photo report made my insurance claim straightforward.', name: 'Sample customer', role: 'Homeowner' },
    ],
    faqs: [
      { q: 'Is the inspection free?', a: 'Yes, in this demo the inspection is free.' },
      { q: 'Do you work with insurance?', a: 'We document damage and explain the claim process.' },
      { q: 'How long does an inspection take?', a: 'Usually under an hour.' },
    ],
  },
  {
    slug: 'solar-funnel',
    industry: 'solar',
    label: 'Solar',
    card: { title: 'Solar Savings Qualification Funnel', desc: 'Savings estimate funnel that qualifies homeownership, roof and bill before booking consultations with closers.' },
    brand: 'SunHarbor Solar',
    accent: '#a16207',
    accent2: '#facc15',
    icon: 'sun',
    heroTitle: 'See how much solar could save on your power bill',
    heroSub: 'Answer three quick questions to get a personalized savings estimate and a no-pressure consultation.',
    offer: 'Free savings estimate',
    questions: [
      { q: 'Do you own your home?', options: ['Yes', 'No, I rent', 'Buying soon', 'Not sure'] },
      { q: 'What is your average monthly power bill?', options: ['Under $100', '$100 to $200', '$200 to $300', 'Over $300'] },
    ],
    benefits: [
      { icon: 'currency', title: 'Personalized estimate', desc: 'Based on your bill, roof and local sunshine.' },
      { icon: 'sun', title: 'Clear options', desc: 'Compare buying, financing and leasing side by side.' },
      { icon: 'user', title: 'No pressure', desc: 'A consultant walks you through the numbers, you decide.' },
    ],
    steps: ['Answer three questions', 'Get your savings estimate', 'Talk through options with a consultant'],
    testimonials: [
      { quote: 'The estimate was ready right away and the consultant was actually helpful.', name: 'Sample customer', role: 'Homeowner' },
      { quote: 'Simple questions and no pushy sales calls.', name: 'Sample customer', role: 'Homeowner' },
    ],
    faqs: [
      { q: 'Is the estimate free?', a: 'Yes, and there is no obligation.' },
      { q: 'Do I need to own my home?', a: 'Most solar options require homeownership.' },
      { q: 'How accurate is the estimate?', a: 'It is a starting point; a consultant confirms the details.' },
    ],
  },
  {
    slug: 'salon-funnel',
    industry: 'salons-beauty',
    label: 'Salon & Beauty',
    card: { title: 'Salon Booking & Rebooking System', desc: 'New client offer funnel with online booking, reminders, rebooking prompts and last-minute gap filling.' },
    brand: 'Velvet & Vine Salon',
    accent: '#6d28d9',
    accent2: '#c4b5fd',
    icon: 'scissors',
    heroTitle: 'Your new favorite salon, now booking online',
    heroSub: 'New clients get a complimentary treatment with their first cut or color. Pick your stylist and time in seconds.',
    offer: 'New client offer',
    questions: [
      { q: 'What would you like to book?', options: ['Cut and style', 'Color', 'Cut and color', 'Treatment'] },
      { q: 'Do you have a stylist preference?', options: ['First available', 'Senior stylist', 'Color specialist', 'Not sure'] },
    ],
    benefits: [
      { icon: 'calendar', title: 'Book any time', desc: 'Real-time availability for every stylist.' },
      { icon: 'clock', title: 'Friendly reminders', desc: 'Confirm or reschedule with a single tap.' },
      { icon: 'star', title: 'Rebook in seconds', desc: 'We remind you when it’s time for your next visit.' },
    ],
    steps: ['Choose your service', 'Pick your stylist and time', 'Relax, we’ll remind you'],
    testimonials: [
      { quote: 'Booking on Instagram was so easy, and I love the reminder texts.', name: 'Sample client', role: 'Client' },
      { quote: 'Got a last-minute slot from the waitlist the same afternoon.', name: 'Sample client', role: 'Regular' },
    ],
    faqs: [
      { q: 'Can I choose my stylist?', a: 'Yes, pick a stylist or the first available.' },
      { q: 'What is the new client offer?', a: 'A complimentary treatment in this demo.' },
      { q: 'Can I reschedule?', a: 'Yes, reply to your reminder text to change your time.' },
    ],
  },
  {
    slug: 'hvac-funnel',
    industry: 'hvac',
    label: 'HVAC',
    card: { title: 'HVAC Service & Maintenance Funnel', desc: 'Emergency and tune-up booking funnel with 24/7 AI answering, dispatch triage and maintenance plan signups.' },
    brand: 'ComfortCore Heating & Air',
    accent: '#0369a1',
    accent2: '#38bdf8',
    icon: 'bolt',
    heroTitle: 'No heat? No cool? Get a technician today',
    heroSub: 'Book emergency service or a seasonal tune-up online. Real-time availability and upfront pricing.',
    offer: 'Book HVAC service',
    questions: [
      { q: 'What do you need?', options: ['No heat', 'No cooling', 'Seasonal tune-up', 'New system quote'] },
      { q: 'How old is your system?', options: ['Under 5 years', '5 to 10 years', 'Over 10 years', 'Not sure'] },
    ],
    benefits: [
      { icon: 'bolt', title: '24/7 emergency service', desc: 'Urgent calls go straight to the on-call technician.' },
      { icon: 'calendar', title: 'Tune-ups on schedule', desc: 'Seasonal reminders keep your system efficient.' },
      { icon: 'currency', title: 'Maintenance plans', desc: 'Priority service and discounts for plan members.' },
    ],
    steps: ['Tell us what’s wrong', 'Pick a time or request emergency service', 'Track your technician by text'],
    testimonials: [
      { quote: 'Booked at 2am when our heat went out and someone was here by morning.', name: 'Sample customer', role: 'Homeowner' },
      { quote: 'The tune-up reminder is the reason our system still runs well.', name: 'Sample customer', role: 'Plan member' },
    ],
    faqs: [
      { q: 'Do you offer emergency service?', a: 'Yes, choose "No heat" or "No cooling" for priority booking.' },
      { q: 'What is a maintenance plan?', a: 'Regular tune-ups plus priority service, shown here as a demo.' },
      { q: 'Do you give quotes for new systems?', a: 'Yes, choose "New system quote" to request one.' },
    ],
  },
  {
    slug: 'chiropractic-funnel',
    industry: 'chiropractic',
    label: 'Chiropractic',
    card: { title: 'Chiropractic New Patient Funnel', desc: 'New patient offer funnel with AI booking, care-plan follow-up and reactivation campaigns for inactive patients.' },
    brand: 'AlignWell Chiropractic',
    accent: '#15803d',
    accent2: '#86efac',
    icon: 'user',
    heroTitle: 'Back pain holding you back? Start feeling better',
    heroSub: 'Book a new patient exam with a licensed chiropractor and leave with a clear plan for relief.',
    offer: 'New patient exam',
    questions: [
      { q: 'Where do you feel pain?', options: ['Lower back', 'Neck and shoulders', 'Headaches', 'Somewhere else'] },
      { q: 'How long have you had it?', options: ['Days', 'Weeks', 'Months', 'Years'] },
    ],
    benefits: [
      { icon: 'user', title: 'Thorough first exam', desc: 'We find the cause, not just the symptom.' },
      { icon: 'clipboard', title: 'A clear care plan', desc: 'Know exactly what to expect and for how long.' },
      { icon: 'calendar', title: 'Visits that fit your week', desc: 'Book and reschedule online at any time.' },
    ],
    steps: ['Tell us where it hurts', 'Book your exam', 'Get your care plan'],
    testimonials: [
      { quote: 'Booked an exam online the same night and felt better after the first week.', name: 'Sample patient', role: 'New patient' },
      { quote: 'The reminders keep me on my plan, and rescheduling is easy.', name: 'Sample patient', role: 'Patient' },
    ],
    faqs: [
      { q: 'What happens at the first visit?', a: 'A consultation, exam and a discussion of your options.' },
      { q: 'Do I need a referral?', a: 'Usually not; a real clinic would confirm here.' },
      { q: 'Is this medical advice?', a: 'No. This is a demo page for illustration only.' },
    ],
  },
];
