// AI agent and automation services: custom agents, knowledge-base chatbots,
// document processing, email automation and speed-to-lead systems.
export default {
  'ai-agent-development': {
    title: 'Custom AI Agent Development for Business | Voxil AI',
    description: 'Custom AI agent development: agents that use your tools and data to complete multi-step work, research, update systems, draft and route, with guardrails and human approval.',
    h1: 'Custom AI agents that <span class="text-gradient-teal">get work done</span>',
    lead: 'Not just chat. AI agents that read your data, use your tools and complete multi-step tasks, with clear limits on what they may do alone and when a person must approve.',
    answer: 'A <strong>custom AI agent</strong> is software that uses a language model to plan and complete tasks by calling tools such as your CRM, database, email or internal APIs. We design agents for specific jobs, like qualifying leads, preparing quotes or triaging tickets, with guardrails, logging and human approval for sensitive actions.',
    serviceType: 'Custom AI agent development',
    facts: [
      { label: 'Tools', value: 'Your APIs' },
      { label: 'Guardrails', value: 'Built in' },
      { label: 'Setup', value: '3-8 weeks' },
      { label: 'Hosting', value: 'Cloud or self-hosted' },
    ],
    pills: ['Tool calling', 'Multi-step workflows', 'Human approval', 'Evaluation'],
    whatIs: {
      title: 'When a chatbot isn’t enough',
      paras: [
        'Chatbots answer questions. Agents do work: they look up a customer, check stock, draft a quote, update the CRM, send a follow-up and report back. That makes them powerful, and it means they need careful design.',
        'We build agents around one well-defined job, give them only the tools and data that job requires, and add checks: limits on actions, human approval steps, logging of every decision and tests that run before each change. The result is automation you can trust in production.',
      ],
    },
    included: [
      'Use-case design with clear success criteria',
      'Tool and API integrations with least-privilege access',
      'Guardrails, approval steps and fallback rules',
      'Evaluation test set and automated checks',
      'Logging and monitoring of agent actions',
      'Documentation and handover to your team',
    ],
    featuresTitle: 'Agents built for <span class="text-gradient-teal">production</span>',
    featuresLead: 'The difference between a demo and a dependable agent is engineering discipline.',
    features: [
      { icon: 'puzzle', title: 'Tool calling', desc: 'Agents call your CRM, databases, calendars and internal APIs to complete tasks.' },
      { icon: 'shield', title: 'Guardrails', desc: 'Action limits, input validation and refusal rules for anything out of scope.' },
      { icon: 'user', title: 'Human in the loop', desc: 'Approvals for refunds, large quotes, outbound messages or any action you choose.' },
      { icon: 'clipboard', title: 'Evaluations', desc: 'Test sets catch regressions before prompt or model changes go live.' },
      { icon: 'chart', title: 'Observability', desc: 'Every step, tool call and cost is logged for review and debugging.' },
      { icon: 'server', title: 'Flexible hosting', desc: 'Run on managed platforms, your cloud, or self-hosted n8n.' },
    ],
    steps: [
      { title: 'Pick the job', desc: 'We choose one task with clear inputs, outputs and value.' },
      { title: 'Design tools and limits', desc: 'Define what the agent may read, write and decide alone.' },
      { title: 'Build and evaluate', desc: 'Build the agent with a test set that measures accuracy and safety.' },
      { title: 'Launch with oversight', desc: 'Start with human review, then reduce it as accuracy is proven.' },
    ],
    compare: {
      title: 'AI agents vs. <span class="text-gradient-teal">chatbots and fixed automations</span>',
      head: ['', 'AI agent', 'Chatbot', 'Rule-based automation'],
      rows: [
        ['Handles messy inputs', 'Yes', 'Yes', 'No'],
        ['Takes actions in your systems', 'Yes, multi-step', 'Limited', 'Yes, fixed steps'],
        ['Adapts to new situations', 'Within its guardrails', 'Conversation only', 'No'],
        ['Predictability', 'High with evals and limits', 'Medium', 'Very high'],
        ['Best for', 'Judgment-heavy, multi-step tasks', 'Q&A and simple requests', 'Repetitive, structured tasks'],
      ],
    },
    fit: [
      'Teams with repetitive tasks that need some judgment',
      'Operations spread across several systems',
      'Companies that tried a chatbot and need it to take action',
      'Businesses wanting AI with clear controls and audit trails',
    ],
    industries: ['insurance', 'law-firms', 'real-estate', 'medical-clinics', 'home-services', 'solar'],
    integrations: ['Anthropic Claude', 'OpenAI', 'n8n', 'Make.com', 'LangGraph', 'HubSpot', 'Salesforce', 'GoHighLevel', 'Google Workspace', 'Microsoft 365', 'Slack', 'PostgreSQL'],
    faqs: [
      { q: 'What can a custom AI agent do?', a: 'Any well-defined task that involves reading information, making a judgment and taking actions through software, such as qualifying leads, preparing quotes, triaging support tickets, reconciling records or researching prospects.' },
      { q: 'How do you stop an agent from making mistakes?', a: 'By limiting its tools and permissions, validating inputs and outputs, requiring human approval for sensitive actions, and testing it against an evaluation set before every change.' },
      { q: 'Which AI models do you use?', a: 'We choose the model that fits the task, cost and data requirements, and design agents so the model can be changed later without rebuilding the whole system.' },
      { q: 'Can agents run on our own infrastructure?', a: 'Yes. Agents can run in your cloud account or on self-hosted tools like n8n, keeping data under your control.' },
    ],
    related: ['ai-chatbot-developer', 'n8n-automation', 'rag-chatbot-development', 'workflow-automation'],
  },

  'rag-chatbot-development': {
    title: 'Knowledge Base AI Chatbot (RAG) Development | Voxil AI',
    description: 'Knowledge base AI chatbots built with RAG: answers grounded in your documents, policies and help center, with source citations, access controls and accuracy testing.',
    h1: 'An AI chatbot that answers from <span class="text-gradient-teal">your own documents</span>',
    lead: 'Policies, manuals, help articles and product specs become a chatbot that answers accurately, cites its sources and says “I don’t know” instead of guessing.',
    answer: 'A <strong>knowledge base AI chatbot</strong> uses retrieval-augmented generation (RAG): it searches your approved documents for the most relevant passages and uses them to write an answer, with citations. It keeps answers grounded in your content, can respect access permissions, and is used for customer support and internal knowledge.',
    serviceType: 'RAG chatbot development',
    facts: [
      { label: 'Answers', value: 'With citations' },
      { label: 'Sources', value: 'Docs, sites, drives' },
      { label: 'Setup', value: '3-6 weeks' },
      { label: 'Access', value: 'Permission-aware' },
    ],
    pills: ['Help center bot', 'Internal knowledge', 'Policy Q&A', 'Source citations'],
    whatIs: {
      title: 'Why a generic chatbot isn’t enough',
      paras: [
        'General AI models don’t know your prices, policies or procedures, and when they don’t know, they may guess. For customer support or internal questions, a confident wrong answer is worse than no answer.',
        'RAG solves this by retrieving the relevant parts of your own content before answering. The chatbot answers only from those sources, shows where the answer came from, and hands off or says it doesn’t know when the documents don’t cover the question.',
      ],
    },
    included: [
      'Content audit and document preparation',
      'Ingestion from websites, PDFs, Google Drive, Notion or SharePoint',
      'Retrieval tuning and answer formatting with citations',
      'Access controls for internal or customer-specific content',
      'Accuracy test set and ongoing evaluation',
      'Automatic re-indexing when content changes',
    ],
    featuresTitle: 'Grounded answers <span class="text-gradient-teal">you can trust</span>',
    featuresLead: 'Accuracy is designed and measured, not assumed.',
    features: [
      { icon: 'document', title: 'Any document source', desc: 'Help centers, PDFs, policies, manuals, wikis and drives.' },
      { icon: 'link', title: 'Source citations', desc: 'Every answer links to the passages it came from.' },
      { icon: 'shield', title: 'Permission-aware', desc: 'Users only get answers from documents they’re allowed to see.' },
      { icon: 'question', title: 'Honest fallbacks', desc: 'Says when it doesn’t know and offers a human hand-off.' },
      { icon: 'refresh', title: 'Always current', desc: 'Content is re-indexed automatically when documents change.' },
      { icon: 'chart', title: 'Gap reports', desc: 'See which questions your documents don’t answer yet.' },
    ],
    steps: [
      { title: 'Audit content', desc: 'We find the sources that matter and fix gaps and contradictions.' },
      { title: 'Index and tune', desc: 'Documents are chunked, indexed and retrieval is tuned for your questions.' },
      { title: 'Test accuracy', desc: 'A test set of real questions measures answer quality before launch.' },
      { title: 'Deploy and improve', desc: 'Launch on your site, help desk or Slack, and fill gaps from real questions.' },
    ],
    fit: [
      'Support teams answering the same documented questions daily',
      'Companies with large help centers, manuals or policy libraries',
      'Teams wanting an internal assistant for procedures and knowledge',
      'Regulated businesses that need answers tied to approved sources',
    ],
    industries: ['insurance', 'law-firms', 'medical-clinics', 'real-estate', 'home-services', 'solar'],
    integrations: ['Google Drive', 'Notion', 'SharePoint', 'Confluence', 'Zendesk', 'Intercom', 'Slack', 'Microsoft Teams', 'Pinecone', 'PostgreSQL pgvector', 'OpenAI', 'Anthropic Claude'],
    faqs: [
      { q: 'What is a RAG chatbot?', a: 'RAG stands for retrieval-augmented generation. The chatbot searches your documents for relevant passages and uses them to answer, which keeps answers accurate and lets it cite sources.' },
      { q: 'Can it stop the chatbot from making things up?', a: 'It greatly reduces it. Answers are grounded in retrieved passages, the bot is instructed to say when the documents don’t cover a question, and we measure accuracy with a test set.' },
      { q: 'Can we use it internally for staff?', a: 'Yes. Internal assistants in Slack, Teams or a web app can answer questions about procedures, policies and documentation, respecting each user’s access rights.' },
      { q: 'What happens when our documents change?', a: 'We set up automatic re-indexing so updated or new documents are reflected in answers, usually within minutes or hours.' },
    ],
    related: ['ai-chatbots', 'ai-chatbot-developer', 'ai-customer-support', 'ai-agent-development'],
  },

  'ai-document-processing': {
    title: 'AI Document Processing & Data Extraction | Voxil AI',
    description: 'AI document processing: extract data from invoices, forms, contracts, applications and emails, validate it and push it into your CRM, accounting or database, with human review.',
    h1: 'Stop retyping data from <span class="text-gradient-teal">documents</span>',
    lead: 'Invoices, applications, intake forms, contracts and emailed PDFs are read by AI, checked against your rules and entered into your systems, with people reviewing only the exceptions.',
    answer: '<strong>AI document processing</strong> uses AI to read documents such as invoices, forms, IDs, contracts and applications, extract the fields you need, validate them and send them to your CRM, accounting software or database. Low-confidence or unusual documents are routed to a person for review.',
    serviceType: 'AI document processing',
    facts: [
      { label: 'Formats', value: 'PDF, scans, email' },
      { label: 'Review', value: 'Exceptions only' },
      { label: 'Setup', value: '3-6 weeks' },
      { label: 'Output', value: 'Your systems' },
    ],
    pills: ['Invoices', 'Applications', 'Intake forms', 'Contracts'],
    whatIs: {
      title: 'Manual data entry is slow, costly and error-prone',
      paras: [
        'Teams spend hours copying details from PDFs and emails into other systems: invoice totals into accounting, applicant details into a CRM, policy numbers into spreadsheets. It’s tedious work, and mistakes are easy to make and hard to spot.',
        'AI document processing reads each document, extracts the fields you define, checks them against rules such as totals adding up or required fields being present, and writes them where they belong. Anything uncertain lands in a short review queue instead of slipping through.',
      ],
    },
    included: [
      'Document types and field definitions',
      'Extraction for typed, scanned and handwritten documents',
      'Validation rules and confidence thresholds',
      'Human review queue for exceptions',
      'Integration with CRM, accounting or database',
      'Audit log of every document processed',
    ],
    featuresTitle: 'Accurate extraction, <span class="text-gradient-teal">built-in checks</span>',
    featuresLead: 'Automation where it’s safe, human review where it matters.',
    features: [
      { icon: 'document', title: 'Any layout', desc: 'Handles varying invoice and form layouts without rigid templates.' },
      { icon: 'mail', title: 'Email intake', desc: 'Process attachments as they arrive in a shared inbox.' },
      { icon: 'clipboard', title: 'Validation rules', desc: 'Check totals, dates, IDs and required fields automatically.' },
      { icon: 'user', title: 'Exception review', desc: 'Low-confidence documents go to a simple review screen.' },
      { icon: 'database', title: 'System updates', desc: 'Write results to QuickBooks, Xero, your CRM or a database.' },
      { icon: 'shield', title: 'Secure handling', desc: 'Access controls, retention rules and audit logs for sensitive documents.' },
    ],
    steps: [
      { title: 'Collect samples', desc: 'We gather real examples of each document type and the fields you need.' },
      { title: 'Build extraction', desc: 'Extraction and validation are built and tested on your samples.' },
      { title: 'Connect systems', desc: 'Results flow into your tools, with a review queue for exceptions.' },
      { title: 'Measure and expand', desc: 'Accuracy is tracked and more document types are added.' },
    ],
    fit: [
      'Finance teams entering invoices and receipts by hand',
      'Insurance and lending teams processing applications',
      'Law firms and clinics handling intake forms',
      'Operations teams receiving orders or documents by email',
    ],
    industries: ['insurance', 'law-firms', 'medical-clinics', 'real-estate', 'solar', 'home-services'],
    integrations: ['QuickBooks', 'Xero', 'Google Drive', 'Gmail', 'Outlook', 'SharePoint', 'HubSpot', 'Salesforce', 'Airtable', 'Make.com', 'n8n', 'PostgreSQL'],
    faqs: [
      { q: 'What documents can AI process?', a: 'Invoices, receipts, purchase orders, application forms, intake forms, contracts, IDs, bank statements and most structured or semi-structured business documents, including scans.' },
      { q: 'How accurate is AI data extraction?', a: 'Accuracy depends on document quality and type. We measure it on your real documents, set confidence thresholds and send uncertain fields to human review so errors aren’t silently entered.' },
      { q: 'Can it handle handwriting?', a: 'Often yes, for clear handwriting on forms. Messy or ambiguous handwriting is flagged for review.' },
      { q: 'Is sensitive data safe?', a: 'We use access controls, encryption, retention limits and providers suitable for your data, and keep documents within the systems and regions you require.' },
    ],
    related: ['workflow-automation', 'ai-agent-development', 'api-integration', 'make-automation'],
  },

  'ai-email-automation': {
    title: 'AI Email Automation & Inbox Assistant | Voxil AI',
    description: 'AI email automation for shared inboxes: classify and route emails, draft accurate replies, extract details into your CRM and follow up automatically, with human approval.',
    h1: 'An AI assistant for your <span class="text-gradient-teal">busiest inbox</span>',
    lead: 'Sales, support and booking inboxes are triaged, answered and logged automatically. Your team approves replies in one click, or lets routine ones send on their own.',
    answer: '<strong>AI email automation</strong> reads incoming emails in shared inboxes, classifies and routes them, drafts replies using your knowledge base and the customer’s history, extracts details into your CRM and schedules follow-ups. Replies can require human approval or send automatically for routine requests.',
    serviceType: 'AI email automation',
    facts: [
      { label: 'Inboxes', value: 'Gmail · Outlook' },
      { label: 'Replies', value: 'Drafted in seconds' },
      { label: 'Setup', value: '2-4 weeks' },
      { label: 'Approval', value: 'Your choice' },
    ],
    pills: ['Inbox triage', 'Reply drafting', 'CRM logging', 'Follow-ups'],
    whatIs: {
      title: 'Email is still where a lot of business happens',
      paras: [
        'Quote requests, booking changes, supplier messages and support questions pile up in shared inboxes. Important emails get buried, response times slip and details are retyped into other systems.',
        'An AI inbox assistant sorts every email by type and urgency, routes it to the right person, drafts a reply that uses your policies and the customer’s history, and logs the important details. Your team reviews and sends, and simple requests can be answered automatically.',
      ],
    },
    included: [
      'Email categories, routing rules and priorities',
      'Reply drafting from your knowledge base and CRM',
      'Detail extraction into CRM or helpdesk fields',
      'Approval workflow or auto-send for routine replies',
      'Follow-up reminders for unanswered threads',
      'Weekly volume and response-time reporting',
    ],
    featuresTitle: 'Faster replies, <span class="text-gradient-teal">nothing missed</span>',
    featuresLead: 'Keep the human touch on email while removing the busywork.',
    features: [
      { icon: 'tag', title: 'Smart triage', desc: 'Emails are labeled by type, urgency and owner as they arrive.' },
      { icon: 'chat', title: 'Accurate drafts', desc: 'Replies use your policies, prices and the customer’s history.' },
      { icon: 'database', title: 'CRM logging', desc: 'Names, dates, order numbers and requests are captured automatically.' },
      { icon: 'clock', title: 'Follow-up reminders', desc: 'Threads waiting on a reply are surfaced before they go cold.' },
      { icon: 'user', title: 'Approval control', desc: 'Choose which categories need review and which can send automatically.' },
      { icon: 'chart', title: 'Response metrics', desc: 'Track volume, categories and response times by inbox.' },
    ],
    steps: [
      { title: 'Review the inbox', desc: 'We sample recent emails to define categories and common replies.' },
      { title: 'Connect and configure', desc: 'Connect Gmail or Outlook, your CRM and your knowledge sources.' },
      { title: 'Draft-only pilot', desc: 'The AI drafts replies while your team reviews and edits them.' },
      { title: 'Automate routine replies', desc: 'Categories with consistently good drafts move to auto-send.' },
    ],
    fit: [
      'Teams sharing a sales, support or bookings inbox',
      'Businesses where email response time affects revenue',
      'Offices retyping email details into a CRM',
      'Owners spending evenings catching up on email',
    ],
    industries: ['real-estate', 'law-firms', 'insurance', 'home-services', 'medical-clinics', 'solar'],
    integrations: ['Gmail', 'Google Workspace', 'Outlook', 'Microsoft 365', 'HubSpot', 'Salesforce', 'GoHighLevel', 'Zendesk', 'Front', 'Make.com', 'n8n', 'Slack'],
    faqs: [
      { q: 'Will the AI send emails without our approval?', a: 'Only if you want it to. Most teams start with drafts that require approval, then allow automatic replies for routine categories once quality is proven.' },
      { q: 'Does it work with Gmail and Outlook?', a: 'Yes. We connect to Google Workspace and Microsoft 365 mailboxes, including shared inboxes.' },
      { q: 'How does it know what to say?', a: 'It uses your knowledge base, policies, past replies and the customer’s CRM history, and flags emails it can’t answer confidently.' },
      { q: 'Is our email data private?', a: 'Access is limited to the mailboxes you choose, data handling follows your requirements, and we use providers that don’t train on your data where that’s required.' },
    ],
    related: ['ai-agent-development', 'ai-customer-support', 'crm-automation', 'email-sms-marketing'],
  },

  'speed-to-lead-automation': {
    title: 'Speed-to-Lead Automation: Reply in Seconds | Voxil AI',
    description: 'Speed-to-lead automation: respond to every new lead within seconds by call, SMS and email, 24/7, qualify with AI and book appointments before competitors call back.',
    h1: 'Reply to every lead <span class="text-gradient-teal">in seconds, not hours</span>',
    lead: 'The first business to respond usually wins the conversation. Speed-to-lead automation contacts every new inquiry within seconds, around the clock, and books the ready ones.',
    answer: '<strong>Speed-to-lead automation</strong> responds to new leads within seconds of an inquiry from a form, ad, call or chat. It sends an instant personalized text and email, places an AI or routed call, qualifies the lead and books an appointment, then alerts your team, so no lead waits while competitors respond.',
    serviceType: 'Speed-to-lead automation',
    facts: [
      { label: 'First touch', value: 'Seconds' },
      { label: 'Coverage', value: '24/7' },
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Channels', value: 'Call · SMS · Email' },
    ],
    pills: ['Instant SMS', 'AI callback', 'Lead routing', 'Response-time tracking'],
    whatIs: {
      title: 'Why minutes matter',
      paras: [
        'Research on lead response has found the odds of reaching and qualifying a lead fall steeply after the first few minutes. Leads from ads and quote forms often contact several businesses at once, and the first one to respond sets the terms.',
        'Speed-to-lead automation removes the delay. Every new lead gets an immediate, personalized response and a call within a minute, from an AI agent or a routed team member, and every response time is measured so you can prove it’s working.',
      ],
    },
    included: [
      'Connection of every lead source to one system',
      'Instant personalized SMS and email replies',
      'AI or routed callback within a minute',
      'Qualification and booking into your calendar',
      'Round-robin or territory routing with alerts',
      'Speed-to-lead dashboard by source and rep',
    ],
    featuresTitle: 'Every lead, <span class="text-gradient-teal">answered first</span>',
    featuresLead: 'Built to win the race to the first conversation.',
    features: [
      { icon: 'bolt', title: 'Instant first touch', desc: 'Text and email go out the moment a lead arrives, day or night.' },
      { icon: 'phone', title: 'Callback in under a minute', desc: 'An AI agent calls immediately, or the system rings your team first.' },
      { icon: 'funnel', title: 'All sources connected', desc: 'Website forms, Facebook and Google lead ads, portals and chat.' },
      { icon: 'users', title: 'Smart routing', desc: 'Leads go to the right rep by territory, product or availability.' },
      { icon: 'calendar', title: 'Booking on the spot', desc: 'Qualified leads choose a time before the conversation ends.' },
      { icon: 'clock', title: 'Response-time tracking', desc: 'See speed to lead by source, rep and hour of day.' },
    ],
    steps: [
      { title: 'Map lead sources', desc: 'We list every source and where leads land today.' },
      { title: 'Build the response', desc: 'Instant messages, callback logic and routing rules.' },
      { title: 'Add qualification', desc: 'AI questions and booking rules for qualified leads.' },
      { title: 'Measure', desc: 'A dashboard tracks response times and booked rates from day one.' },
    ],
    fit: [
      'Businesses buying leads from ads, portals or vendors',
      'Sales teams that can’t respond within minutes at all hours',
      'Home services, solar, insurance and real estate',
      'Companies wanting proof of response times by rep',
    ],
    industries: ['solar', 'roofing', 'insurance', 'real-estate', 'home-services', 'hvac'],
    integrations: ['GoHighLevel', 'HubSpot', 'Salesforce', 'Facebook Lead Ads', 'Google Ads', 'Zillow', 'Twilio', 'Vapi', 'Retell AI', 'Calendly', 'Slack'],
    faqs: [
      { q: 'What is speed to lead?', a: 'It’s the time between a lead’s inquiry and your first meaningful response. Shorter response times consistently lead to more conversations and more booked appointments.' },
      { q: 'How fast can automation respond?', a: 'Texts and emails go out within seconds, and an AI callback typically happens within a minute of the inquiry, at any hour.' },
      { q: 'Do we need an AI agent, or can our team take the calls?', a: 'Either. The system can ring your team first and fall back to an AI agent if nobody answers, or let the AI make the first call and transfer hot leads.' },
      { q: 'Is calling leads automatically legal?', a: 'Leads who submit a form with clear consent language can generally be contacted, but automated and AI calls have specific consent rules, such as the TCPA in the US. We build consent capture and calling windows into every setup.' },
    ],
    related: ['lead-capture-system', 'ai-follow-up-system', 'ai-calling-bots', 'ai-lead-reactivation'],
  },
};
