// AI & Automation, service page content.
const link = (href, text) => `<a href="${href}" class="text-primary-600 underline underline-offset-4">${text}</a>`;

export default {
  'ai-chatbots': {
    title: 'AI Chatbot Development | Website & WhatsApp | Voxil AI',
    description:
      'Custom AI chatbots for your website, WhatsApp, Instagram and Messenger, trained on your business, integrated with your CRM, and built to capture leads, book appointments and resolve support.',
    h1: 'AI chatbots trained on <span class="text-gradient-teal">your business</span>',
    lead: 'Branded assistants for your website, WhatsApp, Instagram and in-app, answering in your voice, qualifying visitors, booking appointments and handing to a human the moment it matters.',
    answer:
      'An <strong>AI chatbot</strong> is a conversational assistant powered by a large language model and trained on your own content, website, pricing, policies and documents. Unlike rule-based bots, it understands free-text questions, answers accurately from your approved knowledge, captures lead details and completes actions like booking or order lookups.',
    facts: [
      { label: 'Go-live', value: '2-4 weeks' },
      { label: 'Channels', value: 'Web · WhatsApp · IG' },
      { label: 'Trained on', value: 'Your content' },
      { label: 'Hand-off', value: 'Live chat' },
    ],
    pills: ['Website chat', 'WhatsApp bots', 'Instagram DMs', 'Lead capture'],
    whatIs: {
      title: 'Not the chatbot your visitors learned to ignore',
      paras: [
        'Old decision-tree bots failed because they could only follow scripts. Modern LLM chatbots understand what the visitor actually typed, answer from your real documentation, and ask the follow-up questions a good salesperson would.',
        'We build chatbots as part of your funnel: they capture name, email and phone at the right moment, push qualified leads to your CRM, book calls into your calendar, and alert your team in Slack or SMS when a hot conversation needs a human.',
      ],
    },
    included: [
      'Knowledge base from your site, docs and FAQs',
      'Brand voice, persona and guardrail design',
      'Website widget plus WhatsApp / Instagram / Messenger',
      'Lead capture and CRM integration',
      'Calendar booking and live-chat hand-off',
      'Analytics, transcripts and monthly tuning',
    ],
    features: [
      { icon: 'book', title: 'Trained on your content', desc: 'Answers from your pages, PDFs and policies, and says so when it doesn’t know.' },
      { icon: 'funnel', title: 'Lead qualification', desc: 'Asks the right questions and scores leads before they reach your inbox.' },
      { icon: 'calendar', title: 'Books meetings', desc: 'Offers real time slots and confirms bookings without leaving the chat.' },
      { icon: 'bubble', title: 'Omnichannel', desc: 'One brain across website, WhatsApp, Instagram, Messenger and SMS.' },
      { icon: 'users', title: 'Human hand-off', desc: 'Routes to live chat or creates a ticket with the full transcript attached.' },
      { icon: 'globe', title: 'Multilingual', desc: 'Replies in the visitor’s language automatically, dozens supported.' },
    ],
    steps: [
      { title: 'Audit & scope', desc: 'We review your content and top inquiries to decide what the bot should own.' },
      { title: 'Train & design', desc: 'Knowledge base, persona, conversation goals and guardrails built.' },
      { title: 'Integrate', desc: 'CRM, calendar, helpdesk and messaging channels connected and tested.' },
      { title: 'Launch & tune', desc: 'Go live, review transcripts weekly and improve answers continuously.' },
    ],
    compare: {
      title: 'AI chatbot vs. <span class="text-gradient-teal">rule-based bot</span>',
      lead: 'Why LLM-powered chatbots outperform the button-menu bots of a few years ago.',
      head: ['', 'AI chatbot (LLM)', 'Rule-based bot', 'Contact form'],
      rows: [
        ['Understands free-text questions', 'Yes', 'Keywords only', 'No'],
        ['Answers from your documents', 'Yes', 'Pre-written replies only', 'No'],
        ['Qualifies and books', 'Yes', 'Limited', 'No'],
        ['Available 24/7', 'Yes', 'Yes', 'Yes (but no reply)'],
        ['Setup effort', 'Moderate', 'High (every path scripted)', 'Low'],
        ['Visitor experience', 'Conversational', 'Rigid menus', 'Wait for email'],
      ],
    },
    fit: [
      'Websites with steady traffic but low inquiry conversion',
      'Businesses answering the same questions by chat and email every day',
      'Brands whose customers prefer WhatsApp or Instagram DMs',
      'Teams that need after-hours lead capture and booking',
    ],
    industries: ['real-estate', 'med-spas', 'fitness-gyms', 'law-firms', 'insurance', 'salons-beauty'],
    integrations: ['OpenAI', 'Anthropic Claude', 'WhatsApp Business API', 'Instagram', 'Messenger', 'GoHighLevel', 'HubSpot', 'Salesforce', 'Intercom', 'Zendesk', 'Shopify', 'WordPress', 'Webflow', 'Calendly', 'Slack', 'Zapier', 'Make.com', 'n8n'],
    faqs: [
      { q: 'How much does a custom AI chatbot cost?', a: 'A focused chatbot with a knowledge base and CRM integration is a fixed-price build, plus low monthly usage costs for the AI model and hosting. More channels, languages and system integrations increase scope. We quote after a 30-minute call.' },
      { q: 'Will the chatbot make things up?', a: 'We minimize that risk with retrieval from approved content only, explicit instructions to admit uncertainty, restricted actions and transcript review. For sensitive topics we route to a human by default.' },
      { q: 'Can it work on WhatsApp and Instagram?', a: `Yes. We deploy the same assistant to WhatsApp via the official Business API, Instagram DMs and Facebook Messenger. See ${link('/services/whatsapp-automation/', 'WhatsApp automation')}.` },
      { q: 'Which AI model do you use?', a: 'We choose per project, typically models from OpenAI or Anthropic, balancing quality, speed, cost and data-handling requirements. You can switch models later without rebuilding.' },
      { q: 'Do I need a developer to maintain it?', a: 'No. You can update the knowledge base by editing documents or pages, and we offer optional monthly tuning. You also get full documentation and ownership.' },
    ],
    related: ['whatsapp-automation', 'ai-chatbot-developer', 'ai-customer-support', 'ai-lead-generation'],
  },

  'ai-chatbot-developer': {
    title: 'Hire an AI Chatbot Developer | LLM & RAG | Voxil AI',
    description:
      'Hire experienced AI chatbot developers for custom LLM chatbots, RAG knowledge assistants, AI agents with tool calling and integrations. Fixed-price projects or dedicated monthly engagement.',
    h1: 'Hire an AI chatbot developer who <span class="text-gradient-teal">ships to production</span>',
    lead: 'Custom LLM chatbots, retrieval-augmented (RAG) assistants and tool-using AI agents, engineered with evaluation, security and cost control from day one, not bolted together from a template.',
    answer:
      'An <strong>AI chatbot developer</strong> designs and builds conversational AI systems using large language models. The work spans prompt and conversation design, retrieval-augmented generation (RAG) over your documents, tool and API integrations, evaluation, security, hosting and monitoring, delivering a chatbot that is accurate, safe and maintainable.',
    facts: [
      { label: 'Engagement', value: 'Project or monthly' },
      { label: 'Stack', value: 'LLM · RAG · Tools' },
      { label: 'Code', value: 'You own it' },
      { label: 'Start', value: 'Within 1-2 weeks' },
    ],
    pills: ['RAG', 'Tool calling', 'Evals', 'Custom UI'],
    whatIs: {
      title: 'When a no-code chatbot builder isn’t enough',
      paras: [
        'Chatbot builders are great for simple FAQ bots. You need a developer when the bot must search thousands of documents accurately, call your internal APIs, respect user permissions, run inside your product, or meet security requirements.',
        'Our developers work in TypeScript and Python, use proven frameworks where they help and plain code where they don’t, and ship with automated evaluations so you can measure accuracy before and after every change.',
      ],
    },
    included: [
      'Architecture and model selection',
      'RAG pipeline: ingestion, chunking, embeddings, retrieval',
      'Tool / function calling to your APIs',
      'Custom chat UI or embedding in your app',
      'Evaluation suite and guardrails',
      'Deployment, monitoring and documentation',
    ],
    features: [
      { icon: 'database', title: 'RAG done properly', desc: 'Hybrid search, reranking and citations so answers are grounded and verifiable.' },
      { icon: 'code', title: 'Tool-using agents', desc: 'Agents that call your APIs to look up, create and update records securely.' },
      { icon: 'shield', title: 'Security & permissions', desc: 'Per-user data access, prompt-injection defences and PII handling.' },
      { icon: 'chart', title: 'Evaluations', desc: 'Test sets and automated scoring to catch regressions before release.' },
      { icon: 'currency', title: 'Cost control', desc: 'Model routing, caching and token budgets that keep running costs predictable.' },
      { icon: 'desktop', title: 'Custom interfaces', desc: 'React widgets, in-app assistants, Slack/Teams bots, whatever fits your users.' },
    ],
    steps: [
      { title: 'Technical scoping', desc: 'Requirements, data sources, security constraints and success metrics.' },
      { title: 'Prototype', desc: 'A working slice on your real data within the first sprint.' },
      { title: 'Build & evaluate', desc: 'Iterate against an evaluation set until quality targets are met.' },
      { title: 'Ship & support', desc: 'Deploy, monitor and hand over, or keep us on retainer.' },
    ],
    fit: [
      'SaaS companies adding an AI assistant to their product',
      'Companies with large document libraries or knowledge bases',
      'Teams whose no-code chatbot hit its limits',
      'Agencies that need a white-label AI development partner',
    ],
    industries: ['law-firms', 'insurance', 'medical-clinics', 'real-estate'],
    integrations: ['OpenAI', 'Anthropic Claude', 'Google Gemini', 'LangChain', 'LlamaIndex', 'Pinecone', 'pgvector', 'Supabase', 'Postgres', 'Next.js', 'React', 'Node.js', 'Python', 'FastAPI', 'Vercel', 'AWS', 'Slack', 'Microsoft Teams'],
    faqs: [
      { q: 'Should I hire a freelancer, an agency or build in-house?', a: 'For a first production chatbot, an experienced agency is usually fastest and least risky: you get architecture, development, evaluation and deployment in one fixed scope. For ongoing product work, many clients keep us on a monthly engagement while their team ramps up.' },
      { q: 'What is RAG and do I need it?', a: 'Retrieval-augmented generation lets the chatbot search your documents and answer from them, rather than relying on the model’s general knowledge. If your chatbot must answer about your products, policies or data, you need RAG.' },
      { q: 'Can you work with our existing codebase?', a: 'Yes. We regularly join existing repos, follow your conventions and CI, and work through pull requests your team reviews.' },
      { q: 'How do you measure chatbot accuracy?', a: 'We build an evaluation set of real questions with expected answers, then score retrieval quality and answer correctness automatically, and track it on every change.' },
      { q: 'Who owns the code?', a: 'You do, code, prompts, evaluation sets and infrastructure configuration.' },
    ],
    related: ['ai-chatbots', 'api-integration', 'ai-saas-development', 'ai-automation-consultant'],
  },

  'whatsapp-automation': {
    title: 'WhatsApp Automation & AI Chatbots | Voxil AI',
    description:
      'WhatsApp Business API automation: AI WhatsApp chatbots, lead capture, appointment booking, broadcast campaigns and CRM integration. Official API setup, compliant templates and human hand-off.',
    h1: 'WhatsApp automation that <span class="text-gradient-teal">replies in seconds</span>',
    lead: 'Turn WhatsApp into your fastest sales and support channel, AI replies, lead qualification, bookings, reminders and broadcasts on the official Business API, all synced to your CRM.',
    answer:
      '<strong>WhatsApp automation</strong> uses the official WhatsApp Business Platform (Cloud API) to respond to customers automatically. An AI WhatsApp chatbot answers questions, qualifies leads, books appointments and sends approved template messages such as reminders and follow-ups, while conversations sync to your CRM and hand off to your team when needed.',
    facts: [
      { label: 'Platform', value: 'Official API' },
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Replies', value: 'Instant, 24/7' },
      { label: 'Team inbox', value: 'Included' },
    ],
    pills: ['AI replies', 'Click-to-WhatsApp ads', 'Broadcasts', 'Shared inbox'],
    whatIs: {
      title: 'Your customers are already on WhatsApp',
      paras: [
        'In markets like the UK, UAE, Pakistan and much of Latin America and Europe, WhatsApp is the default way customers contact a business. Leaving those messages for a person to answer manually means slow replies and lost sales.',
        'We set up the official WhatsApp Business Platform (not unofficial tools that risk bans), connect an AI assistant trained on your business, and wire it to your CRM so every conversation becomes a tracked lead, booking or support case.',
      ],
    },
    included: [
      'WhatsApp Business Platform setup and verification',
      'AI chatbot trained on your business',
      'Message templates for reminders and follow-ups',
      'Click-to-WhatsApp ad flows',
      'CRM sync and shared team inbox',
      'Opt-in management and compliance settings',
    ],
    features: [
      { icon: 'bubble', title: 'AI conversations', desc: 'Natural replies to product, pricing and availability questions, in any language.' },
      { icon: 'funnel', title: 'Lead qualification', desc: 'Collects details and scores leads before routing them to sales.' },
      { icon: 'calendar', title: 'Bookings & reminders', desc: 'Book appointments in chat and send template reminders automatically.' },
      { icon: 'megaphone', title: 'Broadcast campaigns', desc: 'Segmented, opt-in broadcasts for offers, re-engagement and updates.' },
      { icon: 'users', title: 'Team inbox', desc: 'Multiple agents on one number with assignment and hand-off from AI.' },
      { icon: 'currency', title: 'Payments & catalogs', desc: 'Share products and payment links directly in the conversation.' },
    ],
    steps: [
      { title: 'Account & number', desc: 'Meta Business verification and WhatsApp Business Platform setup.' },
      { title: 'Design flows', desc: 'Conversation goals, AI knowledge, templates and routing rules.' },
      { title: 'Integrate', desc: 'CRM, calendar, payments and team inbox connected.' },
      { title: 'Launch & grow', desc: 'Go live, add ad flows and broadcasts, and tune from transcripts.' },
    ],
    fit: [
      'Businesses where most inquiries arrive on WhatsApp',
      'Brands running Click-to-WhatsApp ads on Facebook or Instagram',
      'Clinics, salons and real-estate teams booking via chat',
      'Companies serving the UK, Middle East, South Asia or Latin America',
    ],
    industries: ['real-estate', 'med-spas', 'salons-beauty', 'fitness-gyms', 'medical-clinics', 'home-services'],
    integrations: ['WhatsApp Business Platform', 'Meta Business Suite', 'GoHighLevel', 'HubSpot', 'Salesforce', 'Zoho CRM', 'Shopify', 'Stripe', 'Twilio', '360dialog', 'Google Sheets', 'Make.com', 'n8n', 'OpenAI'],
    faqs: [
      { q: 'Is WhatsApp automation allowed?', a: 'Yes, through the official WhatsApp Business Platform. Customers must opt in to receive business-initiated messages, and those must use pre-approved templates. We set this up properly so your number stays in good standing.' },
      { q: 'Can I keep using WhatsApp on my phone?', a: 'A number connected to the Business Platform moves to the API, so it is used through a team inbox rather than the WhatsApp Business app. Many clients use a new number for the automated line and keep their existing app number separate.' },
      { q: 'What does WhatsApp charge?', a: 'Meta charges per conversation or message depending on category (marketing, utility, authentication, service) and country, and the pricing model has changed over time. We estimate your costs during scoping based on current Meta pricing and your volume.' },
      { q: 'Can the bot speak Arabic or Urdu?', a: 'Yes. The AI detects the customer’s language and responds in it, including Arabic, Urdu, Hindi, Spanish and many others.' },
      { q: 'Does it integrate with GoHighLevel?', a: `Yes. We connect WhatsApp to GoHighLevel so conversations appear in the GHL inbox and trigger workflows. See ${link('/services/gohighlevel-ai/', 'GoHighLevel AI')}.` },
    ],
    related: ['ai-chatbots', 'ai-appointment-booking', 'gohighlevel-ai', 'marketing-automation'],
  },

  'gohighlevel-ai': {
    title: 'GoHighLevel AI Setup | Conversation & Voice AI | Voxil AI',
    description:
      'GoHighLevel AI experts: set up Conversation AI, Voice AI, AI Agent Studio and AI-powered workflows in GHL to reply to leads instantly, book appointments and follow up automatically.',
    h1: 'GoHighLevel AI that <span class="text-gradient-teal">works your pipeline</span>',
    lead: 'We configure GoHighLevel’s native AI, Conversation AI, Voice AI, content AI and AI-driven workflows, and extend it with custom agents where GHL’s built-ins stop.',
    answer:
      '<strong>GoHighLevel AI</strong> refers to the AI features inside the GoHighLevel CRM, including Conversation AI for SMS, chat and social replies, Voice AI for answering calls, and AI steps inside workflows. Configured well, they respond to leads instantly, book appointments into GHL calendars and move contacts through your pipeline automatically.',
    facts: [
      { label: 'Platform', value: 'GoHighLevel' },
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Channels', value: 'SMS · Chat · Voice' },
      { label: 'Extends with', value: 'Vapi · Retell' },
    ],
    pills: ['Conversation AI', 'Voice AI', 'AI workflows', 'Custom agents'],
    whatIs: {
      title: 'The AI is included. The configuration isn’t.',
      paras: [
        'Most GoHighLevel accounts have AI features switched off, or switched on with a generic prompt that gives vague answers and never books. The difference between "we tried the AI" and "the AI books appointments" is training, guardrails and workflow design.',
        'We configure GHL’s native AI around your offer and calendars, build the workflows that react to what it learns, and, where you need more control, better voices or complex logic, connect external agents built on Vapi or Retell AI to your GHL account.',
      ],
    },
    included: [
      'Conversation AI bot training and goals',
      'Voice AI agent configuration',
      'AI-powered workflow automation',
      'Calendar booking and pipeline stage rules',
      'Custom Vapi / Retell agents via webhooks (if needed)',
      'Snapshot of the setup for reuse',
    ],
    features: [
      { icon: 'bubble', title: 'Conversation AI', desc: 'Replies to SMS, web chat, Facebook, Instagram and WhatsApp leads in seconds.' },
      { icon: 'phone', title: 'Voice AI', desc: 'Answers inbound calls, captures details and books into GHL calendars.' },
      { icon: 'sliders', title: 'AI workflows', desc: 'Workflows that branch on AI-detected intent, sentiment and extracted data.' },
      { icon: 'calendar', title: 'Booking-first goals', desc: 'Bots trained to move every conversation towards a booked appointment.' },
      { icon: 'code', title: 'Custom agents', desc: 'External agents for advanced logic, integrated through webhooks and custom fields.' },
      { icon: 'copy', title: 'Snapshot-ready', desc: 'Packaged so agencies can deploy the same AI setup across sub-accounts.' },
    ],
    steps: [
      { title: 'Account review', desc: 'We audit pipelines, calendars, workflows and current AI settings.' },
      { title: 'Train the AI', desc: 'Offer, FAQs, objections, tone and booking goals configured.' },
      { title: 'Build workflows', desc: 'Automations that react to AI outcomes and keep the pipeline moving.' },
      { title: 'Test & launch', desc: 'Test conversations on every channel, then launch and monitor.' },
    ],
    fit: [
      'Businesses already on GoHighLevel not using its AI features',
      'Agencies rolling out AI to many client sub-accounts',
      'Teams whose GHL bot gives generic or wrong answers',
      'Anyone who wants instant lead response inside their existing CRM',
    ],
    industries: ['med-spas', 'roofing', 'real-estate', 'fitness-gyms', 'solar', 'chiropractic'],
    integrations: ['GoHighLevel', 'LeadConnector', 'Conversation AI', 'Voice AI', 'Vapi', 'Retell AI', 'Facebook', 'Instagram', 'WhatsApp', 'Google Business Profile', 'Stripe', 'Zapier', 'Make.com', 'n8n'],
    faqs: [
      { q: 'Is GoHighLevel’s AI good enough on its own?', a: 'For many small businesses, yes, when it’s configured properly. For complex qualification, custom integrations or premium voice quality, we connect external agents (e.g. Vapi or Retell AI) that write back into GHL.' },
      { q: 'Does GoHighLevel AI cost extra?', a: 'GoHighLevel prices some AI features as add-ons or usage-based charges, and its pricing changes periodically. We check the current costs for your plan and model them against your lead volume before recommending a setup.' },
      { q: 'Can the AI book appointments in GHL calendars?', a: 'Yes. Both Conversation AI and Voice AI can book into GHL calendars when set up with the right calendar, availability and goals.' },
      { q: 'Can you set this up for all my agency’s clients?', a: `Yes. We build the configuration once and package it as a ${link('/services/ghl-snapshot/', 'GHL snapshot')} for rollout, with per-client customization.` },
      { q: 'Will it work with WhatsApp?', a: 'Yes, once WhatsApp is connected to your GHL account, Conversation AI can reply to WhatsApp messages alongside SMS and social DMs.' },
    ],
    related: ['gohighlevel-automation', 'ghl-expert', 'ai-voice-agents', 'ai-follow-up-system'],
  },

  'ai-lead-generation': {
    title: 'AI Lead Generation Services | Qualify Leads | Voxil AI',
    description:
      'AI lead generation systems that find target prospects, enrich data, personalize outreach, capture inbound leads and qualify them automatically, feeding your CRM with sales-ready opportunities.',
    h1: 'AI lead generation that <span class="text-gradient-teal">fills the pipeline</span>',
    lead: 'Systems that find the right prospects, enrich and personalize at scale, capture every inbound inquiry and qualify it automatically, so your team talks only to people ready to buy.',
    answer:
      '<strong>AI lead generation</strong> uses AI to find, enrich, engage and qualify potential customers. Typical systems combine prospect data sources, AI-written personalized outreach, lead magnets and chat or voice agents that capture and qualify inbound interest, with all leads scored and routed in your CRM.',
    facts: [
      { label: 'Inbound + outbound', value: 'Both' },
      { label: 'Setup', value: '3-6 weeks' },
      { label: 'Data', value: 'Enriched' },
      { label: 'Output', value: 'Sales-ready leads' },
    ],
    pills: ['Prospect research', 'Enrichment', 'Personalized outreach', 'Qualification'],
    whatIs: {
      title: 'More leads is easy. Better leads is the system.',
      paras: [
        'Buying lists and blasting emails gets you volume and spam complaints. AI lead generation works when it combines tight targeting, genuinely relevant personalization, strong inbound capture and fast qualification.',
        'We design the whole system: who to target, where the data comes from, how outreach is personalized, how inbound leads are captured on your site, and how every lead is scored and routed, with deliverability and privacy rules respected throughout.',
      ],
    },
    included: [
      'ICP definition and data-source selection',
      'Enrichment and lead-scoring model',
      'AI-personalized email and LinkedIn outreach',
      'Inbound capture: chat, forms, quizzes',
      'Instant qualification by chat, SMS or voice',
      'CRM routing and pipeline reporting',
    ],
    features: [
      { icon: 'search', title: 'Prospect research', desc: 'AI researches companies and contacts against your ICP criteria.' },
      { icon: 'database', title: 'Data enrichment', desc: 'Fills in firmographics, roles and signals so scoring is meaningful.' },
      { icon: 'mail', title: 'Personalized outreach', desc: 'Relevant first lines and offers generated per prospect, reviewed by rules.' },
      { icon: 'funnel', title: 'Inbound capture', desc: 'Chatbots, quizzes and lead magnets that convert more of your traffic.' },
      { icon: 'bolt', title: 'Instant qualification', desc: 'New leads engaged in seconds and scored automatically.' },
      { icon: 'chart', title: 'Attribution', desc: 'See which sources and messages produce booked meetings and revenue.' },
    ],
    steps: [
      { title: 'Target', desc: 'Define ICP, offers and success metrics.' },
      { title: 'Build the engine', desc: 'Data, enrichment, outreach and capture flows assembled.' },
      { title: 'Warm & test', desc: 'Domains warmed, copy tested, qualification rules tuned.' },
      { title: 'Scale', desc: 'Increase volume on what works; cut what doesn’t.' },
    ],
    fit: [
      'B2B companies with a clear ideal customer profile',
      'Local businesses that need more qualified inbound inquiries',
      'Teams with good offers but inconsistent lead flow',
      'Sales teams drowning in low-quality leads',
    ],
    industries: ['solar', 'insurance', 'roofing', 'real-estate', 'law-firms', 'home-services'],
    integrations: ['Apollo', 'Clay', 'LinkedIn Sales Navigator', 'Instantly', 'Smartlead', 'HubSpot', 'Salesforce', 'GoHighLevel', 'Pipedrive', 'Typeform', 'Facebook Lead Ads', 'Google Ads', 'Zapier', 'Make.com', 'n8n', 'OpenAI'],
    faqs: [
      { q: 'Is AI cold outreach compliant?', a: 'It can be when done carefully: B2B targeting, legitimate interest where applicable, clear identification, easy opt-out, and respect for CAN-SPAM, GDPR, PECR and similar rules. We will not build spam systems or scrape personal data unlawfully.' },
      { q: 'Do you generate leads for local businesses too?', a: `Yes, usually through inbound: ${link('/services/lead-generation-funnel/', 'lead generation funnels')}, ads, chatbots and instant follow-up rather than cold outreach.` },
      { q: 'How fast will I see results?', a: 'Inbound improvements (faster response, better capture) show quickly. Outbound systems need domain warm-up and testing, so expect a few weeks before scaling volume.' },
      { q: 'Do I own the data?', a: 'Yes. Leads, enrichment data and all automations live in your accounts.' },
      { q: 'Can it book meetings automatically?', a: `Yes. Pair lead generation with an ${link('/services/ai-sdr-system/', 'AI SDR system')} to qualify and book meetings without manual effort.` },
    ],
    related: ['ai-sdr-system', 'lead-generation-funnel', 'ai-follow-up-system', 'lead-capture-system'],
  },

  'ai-follow-up-system': {
    title: 'AI Follow-Up System | Lead & Quote Follow-Up | Voxil AI',
    description:
      'An AI follow-up system that texts, emails and calls leads automatically until they respond, follow up on quotes, no-shows and cold leads with personalized, multi-channel sequences.',
    h1: 'An AI follow-up system that <span class="text-gradient-teal">never forgets a lead</span>',
    lead: 'Most sales are lost to silence, not "no". Our AI follow-up system keeps every lead, quote and no-show warm across SMS, email and voice, personalized, persistent and polite, until they book or opt out.',
    answer:
      'An <strong>AI follow-up system</strong> automatically re-engages leads who haven’t responded, new inquiries, open quotes, missed appointments and old contacts. It sends personalized messages across SMS, email, WhatsApp and voice on a schedule, understands replies with AI, answers questions and books appointments, stopping as soon as the person responds or opts out.',
    facts: [
      { label: 'Channels', value: 'SMS · Email · Voice' },
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Replies', value: 'AI-handled' },
      { label: 'Stops on', value: 'Response / opt-out' },
    ],
    pills: ['Quote follow-up', 'No-show recovery', 'Lead nurture', 'Reactivation'],
    whatIs: {
      title: 'The fortune is in the follow-up, if anyone actually does it',
      paras: [
        'Every business knows follow-up matters. Few do it consistently, because it depends on a busy person remembering to send the fourth message. An AI follow-up system removes the memory problem entirely.',
        'Unlike old drip campaigns, the AI reads replies and responds intelligently, answering a question, handling a "not now", or booking a time, so a follow-up becomes a conversation, not just another automated email.',
      ],
    },
    included: [
      'Follow-up strategy per lead stage',
      'Multi-channel sequences: SMS, email, WhatsApp, voice',
      'AI reply handling and booking',
      'Quote and estimate follow-up flows',
      'No-show and cancellation recovery',
      'Opt-out, quiet hours and compliance rules',
    ],
    features: [
      { icon: 'refresh', title: 'Persistent sequences', desc: 'Well-spaced touches over days and weeks, not three emails and done.' },
      { icon: 'bubble', title: 'Understands replies', desc: 'AI answers questions and adapts the next step based on what the lead said.' },
      { icon: 'document', title: 'Quote follow-up', desc: 'Chases open estimates with helpful nudges, FAQs and easy acceptance.' },
      { icon: 'calendar', title: 'No-show recovery', desc: 'Rebooks missed appointments automatically before the lead goes cold.' },
      { icon: 'clock', title: 'Smart timing', desc: 'Respects time zones, quiet hours and channel preferences.' },
      { icon: 'chart', title: 'Recovered-revenue reporting', desc: 'See which bookings and deals came from automated follow-up.' },
    ],
    steps: [
      { title: 'Map lead stages', desc: 'New, quoted, no-show, lost, past customer, each gets a strategy.' },
      { title: 'Write sequences', desc: 'Messages written in your voice with AI reply handling.' },
      { title: 'Connect CRM', desc: 'Triggers and stop-conditions wired to your pipeline.' },
      { title: 'Launch & optimize', desc: 'Measure reply and booking rates; refine messaging.' },
    ],
    fit: [
      'Businesses that send quotes and wait for customers to call back',
      'Teams with high no-show or cancellation rates',
      'Companies with thousands of old leads in the CRM',
      'Sales teams that give up after one or two attempts',
    ],
    industries: ['home-services', 'roofing', 'solar', 'hvac', 'med-spas', 'insurance'],
    integrations: ['GoHighLevel', 'HubSpot', 'Salesforce', 'Pipedrive', 'Jobber', 'Housecall Pro', 'ServiceTitan', 'Twilio', 'WhatsApp Business API', 'Gmail', 'Outlook', 'Vapi', 'Retell AI', 'Zapier', 'Make.com'],
    faqs: [
      { q: 'Won’t automated follow-up annoy people?', a: 'Not when it is well-spaced, relevant and easy to stop. We design sequences that provide value, answers, reminders, useful information, and stop immediately on reply or opt-out.' },
      { q: 'Can it follow up by phone call too?', a: 'Yes. For leads with appropriate consent, an AI voice agent can make follow-up calls as one step in the sequence.' },
      { q: 'Does it work with my existing CRM?', a: 'Yes, GoHighLevel, HubSpot, Salesforce, Pipedrive, and field-service tools like Jobber, Housecall Pro and ServiceTitan.' },
      { q: 'How is this different from an email drip?', a: 'Drips send the same messages regardless of what happens. The AI follow-up system reads replies, answers questions, books appointments and changes course based on the lead’s behavior.' },
      { q: 'What about SMS compliance?', a: 'We build consent tracking, opt-out handling (STOP keywords), quiet hours and US 10DLC registration guidance into every SMS setup.' },
    ],
    related: ['ai-sdr-system', 'email-sms-marketing', 'crm-automation', 'ai-calling-bots'],
  },

  'ai-automation-consultant': {
    title: 'AI Automation Consultant | Strategy & Audits | Voxil AI',
    description:
      'Hire an AI automation consultant to audit your processes, find the highest-ROI automation opportunities, choose the right tools and deliver a practical implementation roadmap.',
    h1: 'An AI automation consultant who <span class="text-gradient-teal">also builds</span>',
    lead: 'Strategy you can act on: we audit your workflows, quantify where AI and automation will pay back fastest, recommend the right tools, and, if you want, build it with you.',
    answer:
      'An <strong>AI automation consultant</strong> helps a business identify which processes to automate with AI, estimates the return on each opportunity, selects suitable tools and vendors, designs the implementation plan and manages risks such as data privacy, accuracy and change management.',
    facts: [
      { label: 'Audit', value: '1-2 weeks' },
      { label: 'Deliverable', value: 'ROI roadmap' },
      { label: 'Vendor-neutral', value: 'Yes' },
      { label: 'Implementation', value: 'Optional' },
    ],
    pills: ['Process audit', 'ROI modeling', 'Tool selection', 'Roadmap'],
    whatIs: {
      title: 'Most AI projects fail on scoping, not technology',
      paras: [
        'Surveys consistently show high AI adoption but uneven results: many companies experiment, fewer capture measurable value. The gap is usually choosing the wrong first project, or automating a broken process.',
        'Our consulting starts with how work actually flows in your business. We interview the team, measure time and error costs, rank opportunities by value and difficulty, and give you a roadmap with clear first steps, not a slide deck of buzzwords.',
      ],
    },
    included: [
      'Stakeholder interviews and process mapping',
      'Time, cost and error baseline',
      'Ranked opportunity list with ROI estimates',
      'Tool and vendor recommendations',
      'Data, privacy and risk assessment',
      '90-day implementation roadmap',
    ],
    features: [
      { icon: 'search', title: 'Process discovery', desc: 'We map how work really happens, including the workarounds nobody documents.' },
      { icon: 'calculator', title: 'ROI modeling', desc: 'Each opportunity sized by hours saved, revenue impact and build cost.' },
      { icon: 'puzzle', title: 'Tool selection', desc: 'Honest comparisons of platforms, no-code, low-code or custom, for your context.' },
      { icon: 'shield', title: 'Risk & governance', desc: 'Data handling, accuracy controls and human oversight designed in.' },
      { icon: 'users', title: 'Change management', desc: 'Training and rollout plans so your team adopts what’s built.' },
      { icon: 'rocket', title: 'Implementation', desc: 'Our engineers can build the roadmap with you, or brief your team.' },
    ],
    steps: [
      { title: 'Discovery', desc: 'Interviews, tool inventory and process walkthroughs.' },
      { title: 'Analysis', desc: 'Baseline metrics and opportunity scoring.' },
      { title: 'Roadmap', desc: 'Prioritized plan with costs, timelines and quick wins.' },
      { title: 'Pilot', desc: 'Optional: build the first automation and measure results.' },
    ],
    fit: [
      'Leadership teams under pressure to "do something with AI"',
      'Operations with lots of manual, repetitive admin',
      'Companies that tried AI tools without clear results',
      'Businesses choosing between competing automation platforms',
    ],
    industries: ['law-firms', 'insurance', 'medical-clinics', 'real-estate', 'home-services'],
    integrations: ['Microsoft 365', 'Google Workspace', 'Salesforce', 'HubSpot', 'GoHighLevel', 'Slack', 'Notion', 'Airtable', 'QuickBooks', 'Xero', 'Zapier', 'Make.com', 'n8n', 'OpenAI', 'Anthropic Claude'],
    faqs: [
      { q: 'What does an AI automation audit cost?', a: 'Audits are fixed-fee and scoped to the size of your business and number of departments. If you proceed to implementation with us, part of the audit fee is typically credited.' },
      { q: 'Are you tied to specific vendors?', a: 'No. We work across GoHighLevel, HubSpot, Make.com, Zapier, n8n, custom code and major AI providers, and recommend what fits your needs and budget.' },
      { q: 'How do you calculate ROI?', a: `We measure current time spent, error rates and lost revenue for each process, estimate the improvement automation can realistically deliver, and compare against build and running costs. Our ${link('/blog/ai-automation-roi-small-business/', 'AI automation ROI guide')} explains the method.` },
      { q: 'What if AI isn’t the right answer?', a: 'We’ll tell you. Sometimes a simple workflow rule, a better form or a process change beats an AI build.' },
      { q: 'Can you train our team?', a: 'Yes. We run practical workshops on using AI tools safely and maintaining the automations we build.' },
    ],
    related: ['workflow-automation', 'ai-chatbot-developer', 'crm-automation', 'n8n-automation'],
  },

  'workflow-automation': {
    title: 'Workflow Automation Services for Business | Voxil AI',
    description:
      'Workflow automation services that eliminate repetitive work across sales, operations, finance and support, using Make.com, Zapier, n8n, GoHighLevel and custom AI steps.',
    h1: 'Workflow automation that <span class="text-gradient-teal">gives your team hours back</span>',
    lead: 'We find the copy-paste, chase-up and data-entry work eating your week, and replace it with reliable automations, with AI steps where judgment used to be required.',
    answer:
      '<strong>Workflow automation</strong> is the use of software to run business processes automatically, moving data between apps, triggering tasks, sending notifications and making rule-based or AI-assisted decisions. It reduces manual work and errors in areas like lead handling, onboarding, invoicing, reporting and support.',
    facts: [
      { label: 'Typical build', value: '1-4 weeks' },
      { label: 'Tools', value: 'Make · Zapier · n8n' },
      { label: 'AI steps', value: 'Included' },
      { label: 'Monitoring', value: 'Built-in' },
    ],
    pills: ['Data sync', 'Document processing', 'Approvals', 'Reporting'],
    whatIs: {
      title: 'If a person copies it, checks it or chases it, automate it',
      paras: [
        'Sales reps typically spend only a fraction of their week actually selling; the rest disappears into admin. Operations and finance teams face the same drag. Workflow automation reclaims that time.',
        'With AI, automation now reaches tasks that used to need a human: reading emails and PDFs, classifying requests, extracting data from documents and drafting responses. We combine rules and AI so workflows are fast and dependable.',
      ],
    },
    included: [
      'Process mapping and automation design',
      'Build in Make.com, Zapier, n8n or code',
      'AI steps: classify, extract, summarize, draft',
      'Error handling, retries and alerts',
      'Documentation and team walkthrough',
      'Optional monitoring retainer',
    ],
    features: [
      { icon: 'swap', title: 'App-to-app sync', desc: 'Keep CRM, billing, project and support tools in sync automatically.' },
      { icon: 'document', title: 'Document processing', desc: 'Extract data from invoices, forms and emails with AI, then route it.' },
      { icon: 'clipboard', title: 'Onboarding', desc: 'Contracts, accounts, welcome sequences and tasks created on sign-up.' },
      { icon: 'bolt', title: 'Approvals', desc: 'Slack or email approvals that unblock work without meetings.' },
      { icon: 'chart', title: 'Automated reporting', desc: 'Daily and weekly KPIs compiled and delivered where your team looks.' },
      { icon: 'shield', title: 'Reliability', desc: 'Every workflow logs, retries and alerts, no silent failures.' },
    ],
    steps: [
      { title: 'Find the drag', desc: 'Short interviews to list repetitive tasks and time spent.' },
      { title: 'Prioritize', desc: 'Rank by hours saved, risk and build effort.' },
      { title: 'Build & test', desc: 'Automations built with test data, error paths and alerts.' },
      { title: 'Hand over', desc: 'Docs, training and optional monitoring.' },
    ],
    compare: {
      title: 'Choosing an <span class="text-gradient-teal">automation platform</span>',
      lead: `We build on all three. Here’s how we choose, more detail in our ${link('/blog/n8n-vs-make-vs-zapier/', 'n8n vs Make vs Zapier guide')}.`,
      head: ['', 'n8n', 'Make.com', 'Zapier'],
      rows: [
        ['Best for', 'Complex, high-volume, self-hosted', 'Visual multi-step scenarios', 'Simple, fast integrations'],
        ['Hosting', 'Cloud or self-hosted', 'Cloud', 'Cloud'],
        ['Pricing model', 'Per execution / self-host', 'Per operation', 'Per task'],
        ['AI agent support', 'Strong (native agent nodes)', 'Good', 'Good'],
        ['Learning curve', 'Steeper', 'Moderate', 'Easiest'],
        ['App library', 'Large + any HTTP API', 'Very large', 'Largest'],
      ],
    },
    fit: [
      'Teams that spend hours on data entry and copy-paste',
      'Growing businesses whose processes live in people’s heads',
      'Companies with many SaaS tools that don’t talk to each other',
      'Operations leaders who want reliability, not fragile hacks',
    ],
    industries: ['law-firms', 'insurance', 'real-estate', 'home-services', 'medical-clinics'],
    integrations: ['Make.com', 'Zapier', 'n8n', 'Google Workspace', 'Microsoft 365', 'Slack', 'Airtable', 'Notion', 'HubSpot', 'Salesforce', 'GoHighLevel', 'QuickBooks', 'Xero', 'Stripe', 'DocuSign', 'PandaDoc', 'OpenAI'],
    faqs: [
      { q: 'Which processes should we automate first?', a: 'Ones that are frequent, rule-based, time-consuming and low-risk if something goes wrong, lead routing, data sync, reporting and onboarding are common first wins.' },
      { q: 'Make, Zapier or n8n?', a: 'It depends on complexity, volume, budget and hosting needs. We recommend per workflow and often use more than one.' },
      { q: 'What happens when an automation breaks?', a: 'We build error handling, retries and alerts into every workflow, so failures are caught and reported instead of silently losing data.' },
      { q: 'Can AI be part of the workflow?', a: 'Yes, classifying incoming requests, extracting data from documents, summarizing calls and drafting replies are all common AI steps.' },
      { q: 'Do we need to change our tools?', a: 'Rarely. We automate around the tools you already use.' },
    ],
    related: ['make-automation', 'zapier-automation', 'n8n-automation', 'crm-automation'],
  },

  'marketing-automation': {
    title: 'Marketing Automation Services | AI Campaigns | Voxil AI',
    description:
      'Marketing automation services: lead nurture, segmentation, lifecycle campaigns, attribution and AI-personalized content across email, SMS, WhatsApp and social, set up in your CRM.',
    h1: 'Marketing automation that <span class="text-gradient-teal">turns clicks into customers</span>',
    lead: 'Lifecycle campaigns, segmentation, nurture and attribution, built in your CRM, personalized with AI, and connected to sales so marketing finally gets credit for the revenue it drives.',
    answer:
      '<strong>Marketing automation</strong> is software-driven delivery of marketing messages and actions based on customer behavior, such as welcome sequences, lead nurturing, abandoned-cart reminders, re-engagement campaigns and lead scoring, across email, SMS, messaging and ads, with results tracked back to pipeline and revenue.',
    facts: [
      { label: 'Setup', value: '2-5 weeks' },
      { label: 'Channels', value: 'Email · SMS · Ads' },
      { label: 'Personalization', value: 'AI-assisted' },
      { label: 'Attribution', value: 'To revenue' },
    ],
    pills: ['Lifecycle campaigns', 'Lead scoring', 'Segmentation', 'Attribution'],
    whatIs: {
      title: 'The right message, triggered by what people actually do',
      paras: [
        'Batch-and-blast campaigns treat every contact the same. Marketing automation responds to behavior, a pricing page visit, a downloaded guide, a missed webinar, with the next most useful message.',
        'We design the lifecycle from first touch to repeat purchase, build it in your CRM, use AI to personalize content at scale, and connect everything to sales so you can see which campaigns produce booked calls and revenue.',
      ],
    },
    included: [
      'Lifecycle and customer-journey map',
      'Segmentation and lead-scoring model',
      'Nurture, welcome and re-engagement sequences',
      'Behavioral triggers and web tracking',
      'Ad audience sync and retargeting',
      'Attribution dashboard',
    ],
    features: [
      { icon: 'trending', title: 'Lifecycle journeys', desc: 'Welcome, nurture, conversion, onboarding and win-back flows.' },
      { icon: 'users', title: 'Segmentation', desc: 'Dynamic segments by behavior, interest, stage and value.' },
      { icon: 'sparkles', title: 'AI personalization', desc: 'Subject lines, content blocks and offers tailored per segment.' },
      { icon: 'funnel', title: 'Lead scoring', desc: 'Engagement and fit scores that tell sales who to call first.' },
      { icon: 'megaphone', title: 'Ad sync', desc: 'Audiences synced to Meta and Google for retargeting and lookalikes.' },
      { icon: 'chart', title: 'Attribution', desc: 'Campaign performance tied to pipeline and revenue, not just opens.' },
    ],
    steps: [
      { title: 'Journey mapping', desc: 'Stages, triggers and goals from first touch to repeat purchase.' },
      { title: 'Data & tracking', desc: 'Tracking, fields and segments set up correctly.' },
      { title: 'Build campaigns', desc: 'Sequences written, designed and automated.' },
      { title: 'Measure & iterate', desc: 'Monthly reviews of conversion and revenue impact.' },
    ],
    fit: [
      'Businesses with leads that aren’t ready to buy yet',
      'Ecommerce and memberships with repeat-purchase potential',
      'Marketing teams that can’t prove ROI to leadership',
      'Companies with a CRM full of contacts and no nurture',
    ],
    industries: ['fitness-gyms', 'med-spas', 'real-estate', 'solar', 'salons-beauty'],
    integrations: ['GoHighLevel', 'HubSpot', 'ActiveCampaign', 'Klaviyo', 'Mailchimp', 'Salesforce Marketing Cloud', 'Meta Ads', 'Google Ads', 'Google Analytics 4', 'Shopify', 'WordPress', 'Twilio', 'Zapier', 'Make.com'],
    faqs: [
      { q: 'Which platform should I use?', a: 'The one that fits your sales process. GoHighLevel suits local and service businesses; HubSpot suits B2B; Klaviyo suits ecommerce. We work in all of them.' },
      { q: 'How is AI used in marketing automation?', a: 'For segmentation, predicting who is likely to convert, generating personalized content variations, optimizing send times and summarizing engagement for sales.' },
      { q: 'Can you migrate our existing campaigns?', a: 'Yes. We audit what’s working, migrate it, and fix what isn’t during the move.' },
      { q: 'How long until we see results?', a: 'Welcome and re-engagement flows often show results within weeks. Full lifecycle programs compound over a few months.' },
      { q: 'Do you write the content?', a: 'Yes, we write sequences in your brand voice, with AI assisting and humans editing.' },
    ],
    related: ['email-sms-marketing', 'seo-paid-ads', 'crm-automation', 'lead-generation-funnel'],
  },

  'email-sms-marketing': {
    title: 'Email & SMS Marketing Automation Services | Voxil AI',
    description:
      'Email and SMS marketing automation: deliverability setup, 10DLC registration, automated sequences, broadcasts and AI-personalized copy that converts, built in GoHighLevel, Klaviyo, HubSpot and more.',
    h1: 'Email & SMS marketing that <span class="text-gradient-teal">lands and converts</span>',
    lead: 'From deliverability and 10DLC registration to automated sequences and broadcasts, we build email and SMS programs that reach the inbox, respect the rules and drive bookings.',
    answer:
      '<strong>Email and SMS marketing automation</strong> sends targeted, triggered messages, welcome series, reminders, promotions, follow-ups and re-engagement, to opted-in contacts. Done well, it requires proper deliverability setup (SPF, DKIM, DMARC), SMS registration (such as US A2P 10DLC), consent management and messages personalized to each segment.',
    facts: [
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Deliverability', value: 'SPF · DKIM · DMARC' },
      { label: 'SMS', value: '10DLC-ready' },
      { label: 'Copy', value: 'Included' },
    ],
    pills: ['Deliverability', 'A2P 10DLC', 'Automated sequences', 'Broadcasts'],
    whatIs: {
      title: 'Two of the highest-ROI channels, when they reach people',
      paras: [
        'Email and SMS remain some of the most cost-effective marketing channels because you own the audience. But inbox providers and carriers have tightened the rules: bulk senders need authenticated domains, and US business texting requires 10DLC registration.',
        'We set up the technical foundations correctly, then build the automations and campaigns on top, welcome series, appointment reminders, review requests, promotions and win-backs, with AI helping personalize copy for each segment.',
      ],
    },
    included: [
      'Domain authentication: SPF, DKIM, DMARC',
      'A2P 10DLC brand and campaign registration support',
      'Consent capture and opt-out handling',
      'Automated sequences and reminders',
      'Broadcast calendar and templates',
      'Performance reporting',
    ],
    features: [
      { icon: 'shield', title: 'Deliverability first', desc: 'Authenticated domains, warm-up and list hygiene to protect inbox placement.' },
      { icon: 'mail', title: 'Automated email', desc: 'Welcome, nurture, post-purchase and win-back flows that run themselves.' },
      { icon: 'bubble', title: 'Two-way SMS', desc: 'Conversational texts with AI replies and instant hand-off.' },
      { icon: 'star', title: 'Review requests', desc: 'Timed review asks that grow your Google rating.' },
      { icon: 'users', title: 'Segmentation', desc: 'Right message to the right contacts based on behavior and stage.' },
      { icon: 'chart', title: 'Reporting', desc: 'Delivery, engagement, bookings and revenue per campaign.' },
    ],
    steps: [
      { title: 'Foundations', desc: 'Domains, registrations, consent and list cleanup.' },
      { title: 'Strategy', desc: 'Sequences and broadcast calendar planned around your goals.' },
      { title: 'Build & write', desc: 'Templates, copy and automations created and tested.' },
      { title: 'Launch & optimize', desc: 'Send, measure, A/B test and improve.' },
    ],
    fit: [
      'Businesses whose emails land in spam or promotions',
      'Anyone texting customers in the US who hasn’t registered 10DLC',
      'Brands with a list they rarely email',
      'Service businesses that want more reviews and repeat bookings',
    ],
    industries: ['salons-beauty', 'med-spas', 'fitness-gyms', 'home-services', 'chiropractic', 'hvac'],
    integrations: ['GoHighLevel', 'Klaviyo', 'HubSpot', 'ActiveCampaign', 'Mailchimp', 'Twilio', 'LeadConnector', 'Google Workspace', 'Microsoft 365', 'Postmark', 'SendGrid', 'Mailgun', 'Shopify', 'Stripe'],
    faqs: [
      { q: 'What is A2P 10DLC and do I need it?', a: 'A2P 10DLC is the US carrier system for business text messaging from standard 10-digit numbers. Businesses sending SMS to US recipients through platforms like Twilio or GoHighLevel generally need to register their brand and campaign, or messages may be filtered or blocked.' },
      { q: 'Why are my emails going to spam?', a: 'Common causes are missing SPF/DKIM/DMARC records, sending to old or purchased lists, high complaint rates and spammy content. We diagnose and fix each.' },
      { q: 'How often should we email or text?', a: 'It depends on your audience and value. We usually recommend automated triggered messages plus a steady, predictable broadcast cadence, then adjust based on engagement and unsubscribes.' },
      { q: 'Can you write the messages?', a: 'Yes. We write campaigns in your voice and use AI to create segment-specific variations, always human-reviewed.' },
      { q: 'Is SMS marketing legal?', a: 'Yes, with prior consent and clear opt-out. In the US, TCPA and carrier rules apply; in the UK and EU, PECR/GDPR. We build compliance into the setup.' },
    ],
    related: ['marketing-automation', 'ai-follow-up-system', 'gohighlevel-automation', 'whatsapp-automation'],
  },

  'seo-paid-ads': {
    title: 'SEO, AEO & Paid Ads for Service Businesses | Voxil AI',
    description:
      'SEO, answer-engine optimization (AEO) and paid ads management for service businesses, Google, Meta and local search campaigns connected to AI follow-up so every lead gets worked.',
    h1: 'SEO & paid ads that feed an <span class="text-gradient-teal">automated pipeline</span>',
    lead: 'Traffic is only half the job. We run SEO, AI-search optimization and paid campaigns that bring qualified leads, and connect them to instant AI follow-up so your ad spend turns into booked appointments.',
    answer:
      '<strong>SEO and paid ads</strong> are the two main ways to get found online. SEO earns organic rankings in Google and visibility in AI answer engines through technical fixes, content and authority; paid ads buy immediate visibility on Google, Meta and other platforms. Combined with fast automated follow-up, they produce a predictable flow of leads.',
    facts: [
      { label: 'Channels', value: 'Google · Meta · AI search' },
      { label: 'Reporting', value: 'Monthly' },
      { label: 'Follow-up', value: 'Automated' },
      { label: 'Contracts', value: 'Month-to-month' },
    ],
    pills: ['Technical SEO', 'Local SEO', 'AEO / GEO', 'Google & Meta Ads'],
    whatIs: {
      title: 'Search changed. Most SEO strategies didn’t.',
      paras: [
        'People now find businesses through Google’s classic results, the local map pack, AI Overviews, and assistants like ChatGPT and Perplexity. Winning across all of them requires fast technical foundations, structured data, answer-first content and a consistent local presence. Our <a href="/blog/get-recommended-by-chatgpt/" class="text-primary-600 underline underline-offset-4">AEO and GEO guide</a> explains how.',
        'Paid ads fill the gap while organic grows. And because leads from any source convert better when contacted fast, we connect every campaign to automated follow-up, chatbots, SMS and AI calls, so no click is wasted.',
      ],
    },
    included: [
      'Technical SEO audit and fixes',
      'Local SEO and Google Business Profile',
      'Answer-engine (AEO) and AI-search (GEO) optimization',
      'Content plan and on-page optimization',
      'Google and Meta ads management',
      'Lead tracking tied to CRM outcomes',
    ],
    features: [
      { icon: 'search', title: 'Technical SEO', desc: 'Speed, indexation, structured data and site architecture fixed properly.' },
      { icon: 'pin', title: 'Local SEO', desc: 'Google Business Profile, citations, reviews and location pages.' },
      { icon: 'sparkles', title: 'AEO & GEO', desc: 'Answer-first content and schema designed to be cited by AI answer engines.' },
      { icon: 'megaphone', title: 'Paid campaigns', desc: 'Google Search, Performance Max, Local Services and Meta lead ads.' },
      { icon: 'bolt', title: 'Instant follow-up', desc: 'Every lead contacted in seconds by chat, SMS or AI voice.' },
      { icon: 'chart', title: 'Revenue reporting', desc: 'Cost per lead, per booking and per sale, not just clicks.' },
    ],
    steps: [
      { title: 'Audit', desc: 'Technical, content, local and ads accounts reviewed.' },
      { title: 'Foundations', desc: 'Tracking, fixes and follow-up automation put in place.' },
      { title: 'Grow', desc: 'Content, links and campaigns launched and iterated.' },
      { title: 'Report', desc: 'Monthly reporting tied to bookings and revenue.' },
    ],
    fit: [
      'Local service businesses competing in the map pack',
      'Companies spending on ads without clear cost-per-booking',
      'Sites with traffic that doesn’t convert into inquiries',
      'Brands that want to appear in AI answers and overviews',
    ],
    industries: ['roofing', 'hvac', 'law-firms', 'med-spas', 'solar', 'home-services'],
    integrations: ['Google Search Console', 'Google Analytics 4', 'Google Business Profile', 'Google Ads', 'Local Services Ads', 'Meta Ads', 'Ahrefs', 'Semrush', 'Screaming Frog', 'GoHighLevel', 'HubSpot', 'CallRail', 'Looker Studio'],
    faqs: [
      { q: 'What is AEO and GEO?', a: 'Answer Engine Optimization (AEO) structures content so it can be pulled directly into answers, featured snippets, voice assistants and AI Overviews. Generative Engine Optimization (GEO) focuses on being cited by AI assistants like ChatGPT, Perplexity and Gemini. Both reward clear, factual, well-structured content with strong entity signals.' },
      { q: 'How long does SEO take?', a: 'Technical fixes and local improvements can show results within weeks; competitive rankings usually take several months of consistent work. Paid ads can produce leads immediately.' },
      { q: 'Do you guarantee rankings?', a: 'No honest agency can guarantee rankings. We commit to the work, the transparency and the metrics, and we report on leads and revenue, not vanity positions.' },
      { q: 'Why connect ads to automation?', a: 'Lead response speed strongly affects conversion. Automated follow-up makes sure ad-generated leads are contacted in seconds, which protects your cost per acquisition.' },
      { q: 'Do I need long contracts?', a: 'No. We work month-to-month after an initial setup period.' },
    ],
    related: ['lead-generation-funnel', 'website-design', 'marketing-automation', 'ai-follow-up-system'],
  },

  'lead-capture-system': {
    title: 'Lead Capture & Qualification Systems | Voxil AI',
    description:
      'Automated lead capture systems that collect inquiries from every channel, score them, route them to the right rep and trigger instant follow-up, so no lead slips through.',
    h1: 'Lead capture systems that <span class="text-gradient-teal">lose nothing</span>',
    lead: 'Every inquiry, web form, call, chat, DM, ad lead, captured in one place, scored against your criteria, routed to the right person and acknowledged instantly.',
    answer:
      'A <strong>lead capture system</strong> collects inquiries from every channel into one CRM, enriches and scores them, routes each lead to the right salesperson or workflow, and triggers an immediate response. It prevents leads from being lost between inboxes, spreadsheets and missed calls, and makes pipeline data reliable.',
    facts: [
      { label: 'Setup', value: '1-3 weeks' },
      { label: 'Sources', value: 'All channels' },
      { label: 'Response', value: 'Instant' },
      { label: 'Routing', value: 'Rules-based' },
    ],
    pills: ['Multi-channel intake', 'Lead scoring', 'Routing', 'Instant response'],
    whatIs: {
      title: 'Leads don’t go cold, they get lost',
      paras: [
        'In most businesses, leads arrive through half a dozen channels and live in as many places: a shared inbox, a spreadsheet, a phone’s voicemail, a Facebook page. Some are answered in minutes, some in days, some never.',
        'We connect every source to one pipeline, apply scoring rules you can read and change, route leads by territory, service or round-robin, and trigger an instant acknowledgment so every inquirer knows they’ve been heard.',
      ],
    },
    included: [
      'Source audit and unified intake',
      'Forms, chat and call capture',
      'Scoring rules and enrichment',
      'Round-robin or rules-based routing',
      'Instant acknowledgment and follow-up triggers',
      'Response-time and conversion reporting',
    ],
    features: [
      { icon: 'funnel', title: 'Unified intake', desc: 'Forms, calls, chat, DMs and ad leads into one pipeline.' },
      { icon: 'sliders', title: 'Readable scoring', desc: 'Rules your team understands, not a black box.' },
      { icon: 'users', title: 'Smart routing', desc: 'By territory, service, language, value or round-robin.' },
      { icon: 'bolt', title: 'Instant response', desc: 'Every lead acknowledged within seconds on their channel.' },
      { icon: 'database', title: 'Deduplication', desc: 'Merges repeat inquiries so reps see one clean record.' },
      { icon: 'chart', title: 'Speed-to-lead reporting', desc: 'Track response time and conversion by source and rep.' },
    ],
    steps: [
      { title: 'Audit sources', desc: 'List every place leads come from today.' },
      { title: 'Design rules', desc: 'Scoring, routing and SLAs agreed with sales.' },
      { title: 'Connect', desc: 'Integrations built and tested source by source.' },
      { title: 'Monitor', desc: 'Dashboards and alerts for missed SLAs.' },
    ],
    fit: [
      'Businesses with leads scattered across inboxes and tools',
      'Sales teams arguing over lead ownership',
      'Companies that can’t say how fast they respond to leads',
      'Growing teams adding reps and territories',
    ],
    industries: ['real-estate', 'insurance', 'solar', 'roofing', 'law-firms', 'home-services'],
    integrations: ['GoHighLevel', 'HubSpot', 'Salesforce', 'Pipedrive', 'Zoho CRM', 'Facebook Lead Ads', 'Google Ads', 'Typeform', 'Gravity Forms', 'CallRail', 'Twilio', 'Slack', 'Zapier', 'Make.com'],
    faqs: [
      { q: 'What CRM should I use?', a: `If you don’t have one, we recommend based on your sales process, see ${link('/services/crm-setup/', 'CRM setup')}. If you do, we build around it.` },
      { q: 'Can it capture phone leads?', a: 'Yes, with call tracking and optional AI answering, phone inquiries become CRM records automatically.' },
      { q: 'How do you score leads?', a: 'By fit (who they are) and intent (what they did or said), using rules you approve and can adjust over time.' },
      { q: 'Can leads be routed to different branches?', a: 'Yes, by postcode or ZIP, service type, language or any field we capture.' },
      { q: 'How quickly can leads be contacted?', a: 'Acknowledgment is instant. With an AI follow-up or voice agent, qualification can start within seconds too.' },
    ],
    related: ['ai-lead-generation', 'crm-automation', 'ai-follow-up-system', 'ai-sdr-system'],
  },
};
