// Markup helpers for generated pages. Every helper returns an HTML string built
// from the dark-premium primitives in src/styles/ui.css, so generated pages
// look identical to the hand-written home page.
import { SITE } from '../../content/site.js';
import { arrow, icon, plus } from './icons.js';

export { arrow, icon };

export const esc = (s = '') =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Strips tags so HTML copy can be reused inside JSON-LD and meta tags.
export const plain = (s = '') =>
  String(s)
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const jsonLd = (data) =>
  `<script type="application/ld+json">${JSON.stringify(data).replace(/</g, '\\u003c')}</script>`;

// ---------------------------------------------------------------------------
// Page shell
// ---------------------------------------------------------------------------
export const page = ({ path, title, description, body, schema = [] }) => `<!doctype html>
<html lang="en">
  <head>
    <Component src="src/components/shared/head-links.htm" />
    <title>${esc(title)}</title>
    <meta name="description" content="${esc(description)}" />
    <link rel="canonical" href="${SITE.url}${path}" />
    ${schema.map(jsonLd).join('\n    ')}
  </head>
  <body class="overflow-x-hidden bg-white">
    <!-- Generated by scripts/build-pages.js, edit the files in content/, not this file. -->
    <Component src="src/components/shared/header.htm" />
    <main>
${body}
      <Component src="src/components/shared/cta.htm" />
    </main>
    <Component src="src/components/shared/footer.htm" />
  </body>
</html>
`;

// ---------------------------------------------------------------------------
// Structured data
// ---------------------------------------------------------------------------
export const ORG_ID = `${SITE.url}/#organization`;

export const breadcrumbSchema = (crumbs) => ({
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: crumbs.map((c, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    name: c.name,
    item: `${SITE.url}${c.url}`,
  })),
});

export const faqSchema = (faqs) => ({
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map((f) => ({
    '@type': 'Question',
    name: plain(f.q),
    acceptedAnswer: { '@type': 'Answer', text: plain(f.a) },
  })),
});

// WebPage node with speakable selectors, so voice assistants and answer
// engines can lift the quick-answer card verbatim.
export const webPageSchema = ({ path, title, description }) => ({
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  '@id': `${SITE.url}${path}#webpage`,
  url: `${SITE.url}${path}`,
  name: title,
  description,
  inLanguage: 'en',
  isPartOf: { '@id': `${SITE.url}/#website` },
  publisher: { '@id': ORG_ID },
  dateModified: SITE.updated,
  speakable: { '@type': 'SpeakableSpecification', cssSelector: ['h1', '.answer-card'] },
});

// ---------------------------------------------------------------------------
// Building blocks
// ---------------------------------------------------------------------------
export const crumbsNav = (crumbs) => `
        <nav aria-label="Breadcrumb" class="crumbs" data-reveal>
          <ol>
            ${crumbs
              .map((c, i) =>
                i === crumbs.length - 1
                  ? `<li aria-current="page">${esc(c.name)}</li>`
                  : `<li><a href="${c.url}">${esc(c.name)}</a></li>`
              )
              .join('\n            ')}
          </ol>
        </nav>`;

export const eyebrow = (text, dot = '#2fc4b6', light = false) =>
  light
    ? `<p data-reveal class="eyebrow-chip-light mb-5"><span class="size-1.5 rounded-full" style="background:${dot}"></span>${text}</p>`
    : `<p data-reveal class="eyebrow-chip mb-5"><span class="pulse-dot" style="--dot: ${dot}"></span>${text}</p>`;

export const ctaButtons = (primary = 'Book a Free Strategy Call', secondary = { label: 'See pricing & scope', href: '/contact.html' }) => `
            <div data-reveal class="mt-8 flex flex-wrap items-center gap-3">
              <a href="/book-meeting.html" class="cta cta-lg cta-coral">${primary}${arrow()}</a>
              ${secondary ? `<a href="${secondary.href}" class="cta cta-lg cta-ghost">${secondary.label}</a>` : ''}
            </div>`;

/**
 * Inner-page hero with breadcrumb and an answer-first card.
 * `answer` is the 40-60 word direct answer answer-engines quote; `facts` are
 * short label/value pairs shown under it.
 */
export const hero = ({ crumbs, eyebrowText, accent = '#2fc4b6', h1, lead, answer, answerLabel = 'Quick answer', facts = [], pills = [], primary, secondary }) => `
    <section class="page-hero">
      <span class="grid-field" aria-hidden="true"></span>
      <span class="orb -top-28 left-[8%] size-[420px] animate-drift" style="--orb: ${accent}; --orb-opacity: 0.28" aria-hidden="true"></span>
      <span class="orb top-1/3 -right-24 size-[380px] animate-drift-slow" style="--orb: #ff6b35; --orb-opacity: 0.18" aria-hidden="true"></span>

      <div class="main-container relative z-10">
        ${crumbsNav(crumbs)}
        <div class="mt-8 grid gap-10 lg:grid-cols-[1.12fr_0.88fr] lg:items-center lg:gap-14">
          <div>
            ${eyebrow(eyebrowText, accent)}
            <h1 data-reveal class="text-heading-4 sm:text-heading-3 lg:text-heading-2 font-semibold tracking-tight text-secondary">${h1}</h1>
            <p data-reveal class="text-tagline-1 mt-5 max-w-2xl text-secondary/65 md:text-lg">${lead}</p>
            ${ctaButtons(primary, secondary)}
            ${
              pills.length
                ? `<div data-reveal class="mt-8 flex flex-wrap gap-2">${pills.map((p) => `<span class="pill">${p}</span>`).join('')}</div>`
                : ''
            }
          </div>
          ${answer ? answerCard({ answer, facts, accent, label: answerLabel }) : ''}
        </div>
      </div>
    </section>`;

export const answerCard = ({ answer, facts = [], accent = '#2fc4b6', label = 'Quick answer' }) => `
          <aside data-reveal class="edge-card">
            <div class="answer-card p-6 md:p-8" style="--accent: ${accent}">
              <p class="text-tagline-3 flex items-center gap-2 font-semibold tracking-[0.14em] text-secondary/50 uppercase">
                <span class="icon-tile size-8 rounded-lg" style="--accent: ${accent}">${icon('sparkles', 'size-4')}</span>
                ${label}
              </p>
              <p class="text-tagline-1 mt-4 leading-relaxed text-secondary/85">${answer}</p>
              ${
                facts.length
                  ? `<dl class="mt-6 grid grid-cols-2 gap-3">${facts
                      .map(
                        (f) => `
                <div class="rounded-xl border border-secondary/[0.08] bg-secondary/[0.03] px-4 py-3">
                  <dt class="text-tagline-3 text-secondary/45">${f.label}</dt>
                  <dd class="text-tagline-2 mt-0.5 font-semibold text-secondary">${f.value}</dd>
                </div>`
                      )
                      .join('')}
              </dl>`
                  : ''
              }
            </div>
          </aside>`;

export const sectionHead = ({ eyebrowText, dot = '#2fc4b6', title, lead, center = false, light = false, id }) => `
        <div class="${center ? 'mx-auto text-center' : ''} mb-12 max-w-2xl md:mb-14"${id ? ` id="${id}"` : ''}>
          ${eyebrowText ? eyebrow(eyebrowText, dot, light) : ''}
          <h2 data-reveal class="text-heading-5 sm:text-heading-4 lg:text-heading-3 font-semibold tracking-tight ${light ? 'text-secondary' : 'text-secondary'}">${title}</h2>
          ${lead ? `<p data-reveal class="text-tagline-1 mt-4 ${light ? 'text-secondary/65' : 'text-secondary/60'}">${lead}</p>` : ''}
        </div>`;

export const featureCard = ({ title, desc, icon: ic = 'sparkles', accent = '#2fc4b6', cls = '' }) => `
          <div data-reveal class="group glass-card glass-card-rail glass-card-bloom ${cls}" style="--accent: ${accent}">
            <span class="icon-tile" style="--accent: ${accent}">${icon(ic)}</span>
            <h3 class="text-heading-6 mt-5 font-semibold text-secondary">${title}</h3>
            <p class="text-tagline-2 mt-2.5 text-secondary/60">${desc}</p>
          </div>`;

export const linkCard = ({ href, title, desc, icon: ic = 'sparkles', accent = '#2fc4b6', cta = 'Learn more', badge }) => `
          <a href="${href}" data-reveal class="group glass-card glass-card-rail glass-card-bloom flex flex-col" style="--accent: ${accent}">
            <div class="flex items-start justify-between gap-3">
              <span class="icon-tile" style="--accent: ${accent}">${icon(ic)}</span>
              ${badge ? `<span class="pill-accent" style="--accent: ${accent}">${badge}</span>` : ''}
            </div>
            <h3 class="text-heading-6 mt-5 font-semibold text-secondary">${title}</h3>
            <p class="text-tagline-2 mt-2.5 flex-1 text-secondary/60">${desc}</p>
            <span class="link-arrow mt-5" style="color: color-mix(in srgb, ${accent} 75%, #0c1220)">${cta}${arrow()}</span>
          </a>`;

// Compact row-link used in dense grids (related services, locations, etc.)
export const chipLink = (href, label, ic) =>
  `<a href="${href}" class="chip-link">${ic ? icon(ic, 'size-4 text-primary-600') : ''}<span>${label}</span>${arrow('size-3.5 chip-link__arrow')}</a>`;

export const faqBlock = ({ faqs, title = 'Frequently asked <span class="text-gradient-teal">questions</span>', lead = 'Straight answers to what buyers ask us most. Don\'t see yours? Ask on a free call.', eyebrowText = 'FAQ' }) => `
    <section class="section-soft section-pad section-seam" id="faq">
      <span class="orb bottom-0 -left-24 size-[380px]" style="--orb: #0f9f93; --orb-opacity: 0.16" aria-hidden="true"></span>
      <div class="main-container relative z-10">
        <div class="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-16">
          <div class="lg:sticky lg:top-28 lg:self-start">
            ${eyebrow(eyebrowText)}
            <h2 data-reveal class="text-heading-5 sm:text-heading-4 font-semibold tracking-tight text-secondary">${title}</h2>
            <p data-reveal class="text-tagline-2 mt-4 text-secondary/55">${lead}</p>
            <a data-reveal href="/book-meeting.html" class="link-arrow mt-5 text-primary-600 hover:text-primary-700">Ask us directly${arrow()}</a>
          </div>
          <div data-accordion class="space-y-3">
            ${faqs
              .map(
                (f, i) => `
            <div class="faq-item${i === 0 ? ' is-open' : ''}">
              <h3 class="text-tagline-1 font-medium">
                <button type="button" class="faq-trigger" aria-expanded="${i === 0}">
                  <span>${f.q}</span>
                  <span class="faq-icon" aria-hidden="true">${plus}</span>
                </button>
              </h3>
              <div class="faq-panel"><div class="faq-panel-inner">${f.a}</div></div>
            </div>`
              )
              .join('')}
          </div>
        </div>
      </div>
    </section>`;

// Vertical numbered steps on a dark band.
export const stepsBlock = ({ steps, accent = '#2fc4b6' }) => `
          <ol class="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
            ${steps
              .map(
                (s, i) => `
            <li data-reveal class="group glass-card" style="--accent: ${accent}">
              <span class="step-num">${String(i + 1).padStart(2, '0')}</span>
              <h3 class="text-heading-6 mt-5 font-semibold text-secondary">${s.title}</h3>
              <p class="text-tagline-2 mt-2.5 text-secondary/60">${s.desc}</p>
            </li>`
              )
              .join('')}
          </ol>`;

export const checkList = (items, accent = '#2fc4b6', light = false) =>
  `<ul class="${light ? 'check-list-light space-y-3' : 'check-list'}" style="--accent: ${accent}">${items.map((i) => `<li>${i}</li>`).join('')}</ul>`;

export const dataTable = ({ head, rows, caption }) => `
          <div data-reveal class="data-table-wrap">
            <table class="data-table">
              ${caption ? `<caption class="sr-only">${caption}</caption>` : ''}
              <thead><tr>${head.map((h) => `<th scope="col">${h}</th>`).join('')}</tr></thead>
              <tbody>
                ${rows.map((r) => `<tr>${r.map((c, i) => (i === 0 ? `<th scope="row">${c}</th>` : `<td>${c}</td>`)).join('')}</tr>`).join('\n                ')}
              </tbody>
            </table>
          </div>`;

export const updatedLine = (date = SITE.updated) => {
  const d = new Date(`${date}T00:00:00Z`);
  const label = d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
  return `<time datetime="${date}">${label}</time>`;
};
